import type { NpcId } from "./npc";

type ConversationSceneConfig = {
  id: string;
  npcId: NpcId;
  title: string;
  titleZh?: string;
  titleEn?: string;
  shortLabel: string;
  shortLabelZh?: string;
  shortLabelEn?: string;
  microEpisodeZh?: string;
  microEpisodeEn?: string;
  starterIntentZh?: string;
  starterIntentEn?: string;
  sampleUserLineJa?: string;
  setup: string;
  userGoal: string;
  npcOpening: string;
  possibleBeats: string[];
  usefulIntents: string[];
  softLanding: string;
  avoid: string[];
  fallbackUserLines: string[];
  responseOptionsJa?: string[];
};

export const CONVERSATION_SCENES = {
  kimura_bento_checkout: {
    id: "kimura_bento_checkout",
    npcId: "kimura",
    title: "便当结账",
    titleZh: "便当结账",
    titleEn: "Bento checkout",
    shortLabel: "便当结账",
    shortLabelZh: "收银台对话",
    shortLabelEn: "Counter chat",
    setup: "用户拿着便当来到便利店收银台，准备完成一段很短的结账对话。",
    userGoal: "顺利结账，并自然听懂或回应店员常见提问。",
    npcOpening: "こちらのお弁当、温めますか？",
    possibleBeats: ["是否加热", "是否需要袋子", "支付方式", "简短收尾"],
    usefulIntents: [
      "请帮我加热",
      "不用加热",
      "需要袋子",
      "不用袋子",
      "可以刷卡吗",
      "就这些",
      "谢谢",
    ],
    softLanding: "完成一小段结账对话后，自然回到随便聊，不做任务完成判定。",
    avoid: [
      "不要做成收银流程考试",
      "不要逐项检查 possibleBeats",
      "不要把用户说错当成错误",
      "不要强行问完所有步骤",
      "不要把 Kimura 写成收银机器人",
    ],
    fallbackUserLines: [
      "はい、お願いします。",
      "温めなくても大丈夫です。",
      "袋もお願いします。",
      "カードで払えますか？",
    ],
    responseOptionsJa: [
      "はい、お願いします。",
      "温めなくても大丈夫です。",
      "袋もお願いします。",
      "カードで払えますか？",
    ],
  },
  kimura_find_item: {
    id: "kimura_find_item",
    npcId: "kimura",
    title: "找商品",
    titleZh: "找商品",
    titleEn: "Find an item",
    shortLabel: "找商品",
    shortLabelZh: "问商品位置",
    shortLabelEn: "Ask where it is",
    setup: "用户在便利店里找商品，但不确定摆放位置，想问店员。",
    userGoal: "询问商品位置，并听懂简单指引。",
    npcOpening: "何か探してる？ 声かけてくれたら案内するよ。",
    possibleBeats: ["询问商品位置", "确认大概区域", "请求再说一遍", "道谢"],
    usefulIntents: [
      "想问某个商品在哪里",
      "想确认是不是这个方向",
      "想请对方再说一遍",
      "想道谢",
    ],
    softLanding: "找到商品后，可以自然回到普通闲聊，或者继续问推荐。",
    avoid: [
      "不要变成店内地图说明",
      "不要长篇解释货架布局",
      "不要把用户当成在完成任务",
      "不要强行要求用户说出具体商品",
    ],
    fallbackUserLines: [
      "お菓子はどこにありますか？",
      "飲み物はどのあたりですか？",
      "すみません、もう一度お願いします。",
      "ありがとうございます。見てみます。",
    ],
    responseOptionsJa: [
      "お菓子はどこにありますか？",
      "飲み物はどのあたりですか？",
      "すみません、もう一度お願いします。",
      "ありがとうございます。見てみます。",
    ],
  },
  kimura_oden_order: {
    id: "kimura_oden_order",
    npcId: "kimura",
    title: "点关东煮",
    titleZh: "点关东煮",
    titleEn: "Order oden",
    shortLabel: "点关东煮",
    shortLabelZh: "点几样小吃",
    shortLabelEn: "Order a snack",
    setup: "用户在收银台旁看到关东煮，想点几样。",
    userGoal: "点几样关东煮，并自然询问推荐。",
    npcOpening: "おでん、まだありますよ。どうします？",
    possibleBeats: ["询问推荐", "点具体食物", "确认数量", "简单结束"],
    usefulIntents: [
      "想问推荐",
      "想点大根和鸡蛋",
      "想要带走",
      "想要芥末或汤",
    ],
    softLanding: "点完关东煮后，可以自然聊到天气、夜晚、便利店小吃或普通闲聊。",
    avoid: [
      "不要变成菜单教学",
      "不要强行推销",
      "不要连续追问太多配料",
      "不要让 Kimura 变成点餐训练机器",
    ],
    fallbackUserLines: [
      "おすすめありますか？",
      "大根とたまごを一つずつお願いします。",
      "持ち帰りでお願いします。",
      "からしもお願いします。",
    ],
    responseOptionsJa: [
      "おすすめありますか？",
      "大根とたまごを一つずつお願いします。",
      "持ち帰りでお願いします。",
      "からしもお願いします。",
    ],
  },
  kimura_payment_method: {
    id: "kimura_payment_method",
    npcId: "kimura",
    title: "问支付方式",
    titleZh: "问支付方式",
    titleEn: "Ask how to pay",
    shortLabel: "问支付方式",
    shortLabelZh: "确认怎么付款",
    shortLabelEn: "Check payment",
    setup: "用户在便利店结账时，想确认可以用哪种方式付款。",
    userGoal: "询问是否可以用卡、手机支付或现金付款。",
    npcOpening: "お支払い、どうします？",
    possibleBeats: [
      "询问能否用卡",
      "询问能否用手机支付",
      "说明想用现金",
      "简单结束寒暄",
    ],
    usefulIntents: [
      "想问能不能刷卡",
      "想问能不能用手机支付",
      "想说用现金",
      "想道谢",
    ],
    responseOptionsJa: [
      "カードで払えますか。",
      "スマホ決済は使えますか。",
      "現金でお願いします。",
      "ありがとうございます。",
    ],
    softLanding: "确认支付方式后，可以自然结束结账或继续闲聊。",
    avoid: [
      "不要讲解复杂支付系统",
      "不要列出过多支付品牌",
      "不要变成收银流程教学",
      "不要检查用户是否完成步骤",
    ],
    fallbackUserLines: [
      "カードで払えますか。",
      "スマホ決済は使えますか。",
      "現金でお願いします。",
      "ありがとうございます。",
    ],
  },
  kimura_discount_sticker: {
    id: "kimura_discount_sticker",
    npcId: "kimura",
    title: "问打折",
    titleZh: "问打折",
    titleEn: "Ask about discounts",
    shortLabel: "问打折",
    shortLabelZh: "确认优惠贴纸",
    shortLabelEn: "Check discount",
    setup: "用户看到便当或熟食上有优惠贴纸，想确认是否已经打折，或想问打折大概什么时候开始。",
    userGoal: "自然地询问商品是否打折、优惠贴纸是什么意思、什么时候可能会降价。",
    npcOpening: "あ、それ値引きシール貼ってあるやつだね。",
    possibleBeats: [
      "确认商品是否已经打折",
      "询问优惠贴纸的意思",
      "询问大概什么时候会打折",
      "自然回应不确定的规则",
    ],
    usefulIntents: [
      "想问这个是不是已经打折",
      "想问优惠贴纸是什么意思",
      "想问一般什么时候会便宜",
      "想礼貌地确认价格",
    ],
    responseOptionsJa: [
      "これはもう値引きされていますか。",
      "このシールはどういう意味ですか。",
      "何時ごろから値引きになることが多いですか。",
      "この値段で合っていますか。",
    ],
    softLanding: "确认价格或优惠后，可以自然回到结账、便当选择或普通闲聊。",
    avoid: [
      "不要假装所有便利店都有固定打折时间",
      "不要给出现实店铺政策断言",
      "不要让用户听起来像在强硬讨价还价",
      "不要变成省钱攻略或购物教学",
      "不要检查用户是否完成步骤",
    ],
    fallbackUserLines: [
      "これはもう値引きされていますか。",
      "このシールはどういう意味ですか。",
      "何時ごろから値引きになることが多いですか。",
      "この値段で合っていますか。",
    ],
  },
  kimura_hot_snack: {
    id: "kimura_hot_snack",
    npcId: "kimura",
    title: "买热柜小食",
    titleZh: "买热柜小食",
    titleEn: "Order a hot snack",
    shortLabel: "买热柜小食",
    shortLabelZh: "点热柜小吃",
    shortLabelEn: "Hot snack order",
    setup: "用户在收银台旁看到热柜里的炸物或小吃，想点一个。",
    userGoal: "自然地询问热柜小食、点一个、确认是否还有。",
    npcOpening: "レジ横のホットスナック、今ならまだありますよ。",
    possibleBeats: [
      "询问还有什么",
      "点一个热柜小食",
      "确认是否现成",
      "简单结束寒暄",
    ],
    usefulIntents: [
      "想问还有什么",
      "想点一个炸鸡或小吃",
      "想问是不是热的",
      "想道谢",
    ],
    responseOptionsJa: [
      "今、何がありますか。",
      "これを一つお願いします。",
      "まだ温かいですか。",
      "じゃあ、それを一つください。",
    ],
    softLanding: "点完热柜小食后，可以自然聊到夜晚、便利店小吃或普通闲聊。",
    avoid: [
      "不要使用真实便利店品牌名",
      "不要变成菜单教学",
      "不要强行推销",
      "不要连续追问太多配料",
      "不要让 Kimura 变成点餐训练机器人",
    ],
    fallbackUserLines: [
      "今、何がありますか。",
      "これを一つお願いします。",
      "まだ温かいですか。",
      "じゃあ、それを一つください。",
    ],
  },
  misaki_order_coffee: {
    id: "misaki_order_coffee",
    npcId: "misaki",
    title: "点咖啡",
    titleZh: "点咖啡",
    titleEn: "Order coffee",
    shortLabel: "点咖啡",
    shortLabelZh: "点一杯饮料",
    shortLabelEn: "Order a drink",
    setup: "用户在咖啡馆想点一杯咖啡。",
    userGoal: "自然地点一杯咖啡，并说明堂食或外带。",
    npcOpening: "いらっしゃいませ。今日は何にしますか？",
    possibleBeats: [
      "点热咖啡或冰咖啡",
      "说明堂食或外带",
      "简单确认",
      "自然道谢",
    ],
    usefulIntents: [
      "想点一杯热咖啡",
      "想点一杯冰咖啡",
      "想说在店里喝",
      "想说外带",
    ],
    responseOptionsJa: [
      "ホットコーヒーを一つお願いします。",
      "アイスコーヒーをお願いします。",
      "店内でお願いします。",
      "持ち帰りでお願いします。",
    ],
    softLanding: "点完咖啡后，可以自然聊到味道、座位或休息。",
    avoid: [
      "不要变成点单考试",
      "不要讲解复杂咖啡知识",
      "不要过度客服化",
      "不要检查用户是否完成步骤",
    ],
    fallbackUserLines: [
      "ホットコーヒーを一つお願いします。",
      "アイスコーヒーをお願いします。",
      "店内でお願いします。",
      "持ち帰りでお願いします。",
    ],
  },
  misaki_ask_recommendation: {
    id: "misaki_ask_recommendation",
    npcId: "misaki",
    title: "问咖啡推荐",
    titleZh: "问咖啡推荐",
    titleEn: "Ask for a recommendation",
    shortLabel: "问推荐",
    shortLabelZh: "问咖啡推荐",
    shortLabelEn: "Coffee suggestion",
    microEpisodeZh: "今天有点困，但不想喝太苦的咖啡。你想让美咲推荐一杯温和一点的。",
    microEpisodeEn: "You feel a little sleepy today, but you do not want coffee that is too bitter. You want Misaki to recommend something mild.",
    starterIntentZh: "想问有没有不太苦、比较温和的推荐。",
    starterIntentEn: "Ask for a mild coffee recommendation that is not too bitter.",
    sampleUserLineJa: "あまり苦くないコーヒーで、おすすめはありますか。",
    setup: "用户不知道点什么，想问美咲有没有推荐。",
    userGoal: "自然地询问推荐，并表达今天想喝什么感觉的咖啡。",
    npcOpening: "今日は少し落ち着いた味の豆もありますよ。気分に合うもの、探しますか？",
    possibleBeats: [
      "询问推荐",
      "表达想要轻一点或香一点",
      "说明今天想休息",
      "简单确认",
    ],
    usefulIntents: [
      "想问推荐",
      "想喝轻一点的味道",
      "想要香气好的咖啡",
      "想说今天想休息一下",
    ],
    responseOptionsJa: [
      "おすすめはありますか。",
      "今日は軽めの味がいいです。",
      "香りがいいものはありますか。",
      "少し休みたい気分です。",
    ],
    softLanding: "选好推荐后，可以自然聊到咖啡味道、休息或店里的安静时间。",
    avoid: [
      "不要变成咖啡讲座",
      "不要列太多专业术语",
      "不要过度安慰用户",
      "不要像心理咨询一样追问情绪",
    ],
    fallbackUserLines: [
      "おすすめはありますか。",
      "今日は軽めの味がいいです。",
      "香りがいいものはありますか。",
      "少し休みたい気分です。",
    ],
  },
  misaki_order_dessert: {
    id: "misaki_order_dessert",
    npcId: "misaki",
    title: "点甜点",
    titleZh: "点甜点",
    titleEn: "Order dessert",
    shortLabel: "点甜点",
    shortLabelZh: "点甜点",
    shortLabelEn: "Dessert",
    setup: "用户在咖啡馆想点一份甜点或小蛋糕。",
    userGoal: "自然地点一份甜点，或询问哪种甜点适合配咖啡。",
    npcOpening: "ケーキも少しありますよ。よかったら一緒に見ますか？",
    possibleBeats: [
      "询问有什么甜点",
      "点一份蛋糕",
      "询问适合配咖啡的甜点",
      "简单确认",
    ],
    usefulIntents: [
      "想问有什么甜点",
      "想点一份蛋糕",
      "想问哪种适合配咖啡",
      "想说只要一个",
    ],
    responseOptionsJa: [
      "デザートは何がありますか。",
      "このケーキを一つお願いします。",
      "コーヒーに合うものはありますか。",
      "一つだけで大丈夫です。",
    ],
    softLanding: "点完甜点后，可以自然聊到咖啡、味道或店里的轻松时间。",
    avoid: [
      "不要变成甜点菜单教学",
      "不要列太多复杂品类",
      "不要强行推销",
      "不要让 Misaki 变成客服机器人",
    ],
    fallbackUserLines: [
      "デザートは何がありますか。",
      "このケーキを一つお願いします。",
      "コーヒーに合うものはありますか。",
      "一つだけで大丈夫です。",
    ],
  },
  misaki_find_seat: {
    id: "misaki_find_seat",
    npcId: "misaki",
    title: "找座位",
    titleZh: "找座位",
    titleEn: "Find a seat",
    shortLabel: "找座位",
    shortLabelZh: "找座位",
    shortLabelEn: "Seat",
    setup: "用户进入咖啡馆后，想确认是否可以坐某个位置，或说明自己是一个人。",
    userGoal: "自然地询问座位、说明一个人来、或说明朋友稍后会来。",
    npcOpening: "お一人ですか？空いている席、いくつかありますよ。",
    possibleBeats: [
      "说明一个人来",
      "询问能不能坐这里",
      "说明朋友稍后会来",
      "简单道谢",
    ],
    usefulIntents: [
      "想说一个人",
      "想问这里能不能坐",
      "想说朋友等会儿来",
      "想道谢",
    ],
    responseOptionsJa: [
      "一人です。",
      "ここに座ってもいいですか。",
      "あとで友達が来ます。",
      "ありがとうございます。ここにします。",
    ],
    softLanding: "找到座位后，可以自然转入点单、咖啡推荐或普通闲聊。",
    avoid: [
      "不要变成座位规则说明",
      "不要过度安慰用户",
      "不要让 Misaki 显得过分亲密",
      "不要把用户状态总结得太重",
    ],
    fallbackUserLines: [
      "一人です。",
      "ここに座ってもいいですか。",
      "あとで友達が来ます。",
      "ありがとうございます。ここにします。",
    ],
  },
  taisho_enter_izakaya: {
    id: "taisho_enter_izakaya",
    npcId: "taisho",
    title: "第一次进店",
    titleZh: "第一次进店",
    titleEn: "Enter the izakaya",
    shortLabel: "第一次进店",
    shortLabelZh: "第一次进店",
    shortLabelEn: "First visit",
    setup: "用户第一次走进居酒屋，不知道怎么自然开口。",
    userGoal: "自然地打招呼、说明人数，并询问是否可以坐下。",
    npcOpening: "いらっしゃい。何名さん？",
    possibleBeats: ["说明人数", "询问能不能坐吧台", "说明第一次来", "简单寒暄"],
    usefulIntents: ["想说一个人", "想问能不能坐这里", "想说第一次来", "想简单打招呼"],
    responseOptionsJa: [
      "一人です。",
      "ここに座ってもいいですか。",
      "初めて来ました。",
      "よろしくお願いします。",
    ],
    softLanding: "坐下后，可以自然转入问推荐、点饮料、点菜或普通闲聊。",
    avoid: [
      "不要变成入店流程教学",
      "不要像餐厅客服",
      "不要让 Taisho 太正式",
      "不要检查用户是否完成步骤",
    ],
    fallbackUserLines: [
      "一人です。",
      "ここに座ってもいいですか。",
      "初めて来ました。",
      "よろしくお願いします。",
    ],
  },
  taisho_first_drink: {
    id: "taisho_first_drink",
    npcId: "taisho",
    title: "先点一杯",
    titleZh: "先点一杯",
    titleEn: "Order a first drink",
    shortLabel: "先点一杯",
    shortLabelZh: "先点一杯",
    shortLabelEn: "First drink",
    setup: "用户坐下后想先点一杯饮料。",
    userGoal: "自然地点一杯饮料，并说明想先慢慢看菜单。",
    npcOpening: "まず飲み物、どうする？",
    possibleBeats: ["点一杯饮料", "询问有什么饮料", "说明先看菜单", "简单确认"],
    usefulIntents: ["想先点一杯", "想问有什么饮料", "想先看菜单", "想简单确认"],
    responseOptionsJa: [
      "まず一杯お願いします。",
      "飲み物は何がありますか。",
      "先にメニューを見てもいいですか。",
      "じゃあ、それでお願いします。",
    ],
    softLanding: "点完第一杯后，可以自然转入问推荐、点小菜或普通闲聊。",
    avoid: [
      "不要变成酒类介绍",
      "不要强行推荐酒",
      "不要列太长饮料菜单",
      "不要催用户点菜",
    ],
    fallbackUserLines: [
      "まず一杯お願いします。",
      "飲み物は何がありますか。",
      "先にメニューを見てもいいですか。",
      "じゃあ、それでお願いします。",
    ],
  },
  taisho_no_alcohol: {
    id: "taisho_no_alcohol",
    npcId: "taisho",
    title: "不喝酒时怎么说",
    titleZh: "不喝酒时怎么说",
    titleEn: "Say you don't drink",
    shortLabel: "不喝酒",
    shortLabelZh: "不喝酒",
    shortLabelEn: "No alcohol",
    setup: "用户在居酒屋不想喝酒，想自然说明自己今天不喝酒。",
    userGoal: "自然地说不喝酒，并询问无酒精饮料或适合配饭的东西。",
    npcOpening: "飲み物、どうする？",
    possibleBeats: ["说明今天不喝酒", "询问无酒精饮料", "点茶或软饮", "自然缓和气氛"],
    usefulIntents: ["想说今天不喝酒", "想问有没有无酒精饮料", "想点茶", "想自然解释"],
    responseOptionsJa: [
      "今日はお酒は飲まないです。",
      "ノンアルコールの飲み物はありますか。",
      "お茶でお願いします。",
      "今日は軽く食べるだけにします。",
    ],
    softLanding: "说明不喝酒后，可以自然转向点菜、吃点热的或普通闲聊。",
    avoid: [
      "不要劝酒",
      "不要调侃用户不喝酒",
      "不要让用户感到压力",
      "不要变成酒类推荐",
    ],
    fallbackUserLines: [
      "今日はお酒は飲まないです。",
      "ノンアルコールの飲み物はありますか。",
      "お茶でお願いします。",
      "今日は軽く食べるだけにします。",
    ],
  },
  taisho_ask_recommendation: {
    id: "taisho_ask_recommendation",
    npcId: "taisho",
    title: "问今日推荐",
    titleZh: "问今日推荐",
    titleEn: "Ask today's recommendation",
    shortLabel: "问推荐",
    shortLabelZh: "问推荐",
    shortLabelEn: "Recommendation",
    setup: "用户坐下后，不知道点什么，想问大将今天有什么推荐。",
    userGoal: "自然地询问推荐，并表达想吃温热、轻一点或下饭的东西。",
    npcOpening: "今日は何か食べたい感じのもの、ある？",
    possibleBeats: ["询问推荐", "表达想吃温热的东西", "表达想吃轻一点的东西", "简单确认"],
    usefulIntents: ["想问今日推荐", "想吃温热的东西", "想吃轻一点", "想让大将推荐"],
    responseOptionsJa: [
      "今日のおすすめはありますか。",
      "温かいものが食べたいです。",
      "軽めのものがいいです。",
      "大将のおすすめでお願いします。",
    ],
    softLanding: "问完推荐后，可以自然进入点菜、聊一天结束或普通闲聊。",
    avoid: [
      "不要列太长菜单",
      "不要变成美食攻略",
      "不要强行推销",
      "不要说教用户该吃什么",
    ],
    fallbackUserLines: [
      "今日のおすすめはありますか。",
      "温かいものが食べたいです。",
      "軽めのものがいいです。",
      "大将のおすすめでお願いします。",
    ],
  },
  taisho_order_small_dish: {
    id: "taisho_order_small_dish",
    npcId: "taisho",
    title: "点一份小菜",
    titleZh: "点一份小菜",
    titleEn: "Order a small dish",
    shortLabel: "点小菜",
    shortLabelZh: "点小菜",
    shortLabelEn: "Small dish",
    setup: "用户想点一份小菜或下酒菜，但不想点太多。",
    userGoal: "自然地点一份小菜、说明只想简单吃点。",
    npcOpening: "ちょっとつまむ感じでいい？",
    possibleBeats: ["表达想简单吃点", "点一份小菜", "询问有什么适合一个人的", "简单确认"],
    usefulIntents: ["想简单吃点", "想点一份小菜", "想问一个人适合点什么", "想说先这样"],
    responseOptionsJa: [
      "軽くつまめるものはありますか。",
      "小さいおかずを一つお願いします。",
      "一人でも食べやすいものはありますか。",
      "とりあえず、それでお願いします。",
    ],
    softLanding: "点完小菜后，可以自然聊到口味、一天结束或继续闲聊。",
    avoid: [
      "不要变成菜单教学",
      "不要连续推很多菜",
      "不要让用户感觉必须继续点",
      "不要让 Taisho 变成点餐训练机器人",
    ],
    fallbackUserLines: [
      "軽くつまめるものはありますか。",
      "小さいおかずを一つお願いします。",
      "一人でも食べやすいものはありますか。",
      "とりあえず、それでお願いします。",
    ],
  },
  taisho_add_order: {
    id: "taisho_add_order",
    npcId: "taisho",
    title: "追加点单",
    titleZh: "追加点单",
    titleEn: "Order more",
    shortLabel: "追加点单",
    shortLabelZh: "追加点单",
    shortLabelEn: "Add order",
    setup: "用户已经点过一轮，想再加点一份菜或一杯饮料。",
    userGoal: "自然地追加点单，或询问能不能再加一份。",
    npcOpening: "もう少し何かいく？",
    possibleBeats: ["想再点一份", "询问还能不能加单", "点同样的东西", "简单确认"],
    usefulIntents: ["想再点一份", "想问还能不能加单", "想点同样的", "想先这样"],
    responseOptionsJa: [
      "もう一品お願いします。",
      "まだ追加できますか。",
      "同じものをもう一つお願いします。",
      "とりあえず、これで大丈夫です。",
    ],
    softLanding: "追加点单后，可以自然继续吃喝、闲聊或慢慢收尾。",
    avoid: [
      "不要强行让用户继续点",
      "不要变成追加销售",
      "不要连续推荐太多菜",
      "不要检查用户是否完成步骤",
    ],
    fallbackUserLines: [
      "もう一品お願いします。",
      "まだ追加できますか。",
      "同じものをもう一つお願いします。",
      "とりあえず、これで大丈夫です。",
    ],
  },
  taisho_tired_day: {
    id: "taisho_tired_day",
    npcId: "taisho",
    title: "今天有点累",
    titleZh: "今天有点累",
    titleEn: "Say you had a tiring day",
    shortLabel: "有点累",
    shortLabelZh: "有点累",
    shortLabelEn: "Tiring day",
    setup: "用户一天结束后坐在居酒屋，想轻轻说一句今天有点累。",
    userGoal: "自然地表达疲惫、吐槽一点今天的事，但不进入沉重咨询。",
    npcOpening: "今日はちょっと疲れてる顔してるな。",
    possibleBeats: ["表达今天有点累", "说今天不太顺", "想吃点热的", "轻轻转回吃喝或闲聊"],
    usefulIntents: ["想说今天有点累", "想说今天不太顺", "想说只想轻松待一会儿", "想吃点温热的东西"],
    responseOptionsJa: [
      "今日はちょっと疲れました。",
      "なんか、今日はうまくいかない日でした。",
      "少しだけゆっくりしたいです。",
      "温かいものが食べたいです。",
    ],
    softLanding: "轻轻接住用户的疲惫后，应自然回到吃喝、店里的气氛或普通闲聊。",
    avoid: [
      "不要变成心理咨询",
      "不要人生说教",
      "不要过度总结用户状态",
      "不要追问沉重私人问题",
      "不要把用户的疲惫放大成严重问题",
    ],
    fallbackUserLines: [
      "今日はちょっと疲れました。",
      "なんか、今日はうまくいかない日でした。",
      "少しだけゆっくりしたいです。",
      "温かいものが食べたいです。",
    ],
  },
  taisho_check_bill: {
    id: "taisho_check_bill",
    npcId: "taisho",
    title: "结账",
    titleZh: "结账",
    titleEn: "Ask for the bill",
    shortLabel: "结账",
    shortLabelZh: "结账",
    shortLabelEn: "Bill",
    setup: "用户吃完后想结账，但不知道怎么自然开口。",
    userGoal: "自然地表示想结账，并简单寒暄离店。",
    npcOpening: "そろそろ締める感じ？",
    possibleBeats: ["表示想结账", "确认金额", "简单道谢", "离店寒暄"],
    usefulIntents: ["想说要结账", "想问总共多少钱", "想道谢", "想说下次再来"],
    responseOptionsJa: [
      "そろそろお会計をお願いします。",
      "全部でいくらですか。",
      "ごちそうさまでした。",
      "また来ます。",
    ],
    softLanding: "结账后，可以自然结束本轮场景或回到普通闲聊。",
    avoid: [
      "不要变成结账流程考试",
      "不要长篇说明付款方式",
      "不要强行总结用户今天吃了什么",
      "不要让 Taisho 说教",
    ],
    fallbackUserLines: [
      "そろそろお会計をお願いします。",
      "全部でいくらですか。",
      "ごちそうさまでした。",
      "また来ます。",
    ],
  },
  haruka_first_lab_greeting: {
    id: "haruka_first_lab_greeting",
    npcId: "haruka",
    title: "第一次进研究室",
    titleZh: "第一次进研究室",
    titleEn: "First lab greeting",
    shortLabel: "第一次进研究室",
    shortLabelZh: "第一次进研究室",
    shortLabelEn: "Lab greeting",
    setup: "用户第一次进入研究室，不知道怎么自然打招呼。",
    userGoal: "自然地向前辈或研究室成员打招呼，并说明自己是第一次来。",
    npcOpening: "初めて研究室に来るときって、少し緊張しますよね。まずは軽く挨拶できれば大丈夫です。",
    possibleBeats: ["说明第一次来", "向前辈打招呼", "询问坐哪里或在哪里等", "简单道谢"],
    usefulIntents: ["想说第一次来研究室", "想向前辈打招呼", "想问在哪里等", "想简单道谢"],
    responseOptionsJa: [
      "初めて研究室に来ました。",
      "よろしくお願いします。",
      "どこで待てばいいですか。",
      "ありがとうございます。",
    ],
    softLanding: "打过招呼后，可以自然转入研究室日常、ゼミ、文献或普通校园闲聊。",
    avoid: [
      "不要变成研究室礼仪课程",
      "不要过度正式",
      "不要像教授训话",
      "不要检查用户是否完成步骤",
    ],
    fallbackUserLines: [
      "初めて研究室に来ました。",
      "よろしくお願いします。",
      "どこで待てばいいですか。",
      "ありがとうございます。",
    ],
  },
  haruka_ask_senpai_help: {
    id: "haruka_ask_senpai_help",
    npcId: "haruka",
    title: "请前辈帮忙看一下",
    titleZh: "请前辈帮忙看一下",
    titleEn: "Ask a senpai for help",
    shortLabel: "请前辈帮忙",
    shortLabelZh: "请前辈帮忙",
    shortLabelEn: "Ask for help",
    setup: "用户想请前辈帮忙看一下资料、表达或准备内容，但不想显得太打扰。",
    userGoal: "自然地向前辈提出一个轻量请教请求。",
    npcOpening: "先輩に聞くときは、少しだけ見てもらえるか、軽く聞くくらいで大丈夫ですよ。",
    possibleBeats: ["说明想请教", "请求看一下", "说明不会占太多时间", "表达感谢"],
    usefulIntents: ["想请教一个问题", "想请对方看一下", "想说不会花太多时间", "想道谢"],
    responseOptionsJa: [
      "少しだけ相談してもいいですか。",
      "この部分を見てもらえますか。",
      "時間があるときで大丈夫です。",
      "ありがとうございます。助かります。",
    ],
    softLanding: "轻量请教后，可以自然转入具体问题、研究室闲聊或普通校园话题。",
    avoid: [
      "不要变成导师指导",
      "不要替用户写完整学术建议",
      "不要长篇规划",
      "不要让 Haruka 变成顾问",
    ],
    fallbackUserLines: [
      "少しだけ相談してもいいですか。",
      "この部分を見てもらえますか。",
      "時間があるときで大丈夫です。",
      "ありがとうございます。助かります。",
    ],
  },
  haruka_paper_question: {
    id: "haruka_paper_question",
    npcId: "haruka",
    title: "文献看不懂",
    titleZh: "文献看不懂",
    titleEn: "Ask about a paper",
    shortLabel: "文献看不懂",
    shortLabelZh: "文献看不懂",
    shortLabelEn: "Paper question",
    setup: "用户读文献时卡住了，想自然地向前辈表达自己哪里不太懂。",
    userGoal: "表达文献有点难、想问从哪里读或怎么理解某部分。",
    npcOpening: "文献って、最初はどこから読めばいいか迷いますよね。全部わからなくても大丈夫です。",
    possibleBeats: ["说明文献有点难", "询问从哪里开始读", "说明某部分不懂", "请求前辈简单提示"],
    usefulIntents: ["想说文献有点难", "想问从哪里开始读", "想说某部分不懂", "想请前辈简单提示"],
    responseOptionsJa: [
      "この論文、少し難しいです。",
      "どこから読めばいいですか。",
      "この部分がまだよくわかりません。",
      "簡単に教えてもらえますか。",
    ],
    softLanding: "问完文献后，可以自然聊到读文献的方法、ゼミ准备或普通校园话题。",
    avoid: [
      "不要变成论文讲解机器人",
      "不要替用户系统讲完整文献",
      "不要长篇学术指导",
      "不要让 Haruka 变成教授",
    ],
    fallbackUserLines: [
      "この論文、少し難しいです。",
      "どこから読めばいいですか。",
      "この部分がまだよくわかりません。",
      "簡単に教えてもらえますか。",
    ],
  },
  haruka_seminar_comment: {
    id: "haruka_seminar_comment",
    npcId: "haruka",
    title: "ゼミ里简单发言",
    titleZh: "ゼミ里简单发言",
    titleEn: "Speak in seminar",
    shortLabel: "ゼミ发言",
    shortLabelZh: "ゼミ发言",
    shortLabelEn: "Seminar comment",
    setup: "用户想在ゼミ里说一句简单想法，但不知道怎么自然开口。",
    userGoal: "练习用轻丁寧的方式表达一个简单看法、疑问或补充。",
    npcOpening: "ゼミでは、完璧な意見じゃなくても、一言だけ言えれば十分なこともありますよ。",
    possibleBeats: ["表达一个简单看法", "提出一个问题", "补充一点", "承认自己还不确定"],
    usefulIntents: ["想说我觉得有意思", "想提出一个问题", "想补充一点", "想说自己还不确定"],
    responseOptionsJa: [
      "この点が面白いと思いました。",
      "一つ質問してもいいですか。",
      "少しだけ補足してもいいですか。",
      "まだ整理できていないのですが、気になりました。",
    ],
    softLanding: "说出一句后，可以自然转入发表、文献、课堂理解或普通校园闲聊。",
    avoid: [
      "不要变成发表训练课",
      "不要要求用户讲完整观点",
      "不要纠正用户发言结构",
      "不要让 Haruka 变成老师",
    ],
    fallbackUserLines: [
      "この点が面白いと思いました。",
      "一つ質問してもいいですか。",
      "少しだけ補足してもいいですか。",
      "まだ整理できていないのですが、気になりました。",
    ],
  },
  haruka_presentation_nerves: {
    id: "haruka_presentation_nerves",
    npcId: "haruka",
    title: "发表前有点紧张",
    titleZh: "发表前有点紧张",
    titleEn: "Before a presentation",
    shortLabel: "发表前紧张",
    shortLabelZh: "发表前紧张",
    shortLabelEn: "Presentation nerves",
    setup: "用户发表前有点紧张，想向前辈轻轻说一下。",
    userGoal: "自然表达紧张、说明自己还没准备好，或请求一点轻量建议。",
    npcOpening: "発表前って、少し緊張しますよね。まず一言目だけ決めておくと、少し楽になりますよ。",
    possibleBeats: ["表达有点紧张", "说明还没完全准备好", "请求轻量建议", "确认开场一句"],
    usefulIntents: ["想说有点紧张", "想说还没准备好", "想请前辈给一点建议", "想练开场一句"],
    responseOptionsJa: [
      "発表が近くて、少し緊張しています。",
      "まだ準備が完全ではありません。",
      "最初に何と言えば自然ですか。",
      "少しだけアドバイスをもらえますか。",
    ],
    softLanding: "轻轻接住紧张后，可以自然回到开场表达、ゼミ氛围或普通校园话题。",
    avoid: [
      "不要变成心理咨询",
      "不要长篇演讲指导",
      "不要给压力",
      "不要把紧张放大成严重问题",
    ],
    fallbackUserLines: [
      "発表が近くて、少し緊張しています。",
      "まだ準備が完全ではありません。",
      "最初に何と言えば自然ですか。",
      "少しだけアドバイスをもらえますか。",
    ],
  },
  haruka_after_class_check: {
    id: "haruka_after_class_check",
    npcId: "haruka",
    title: "课后确认没听懂",
    titleZh: "课后确认没听懂",
    titleEn: "Ask after class",
    shortLabel: "课后确认",
    shortLabelZh: "课后确认",
    shortLabelEn: "After class",
    setup: "用户上课或说明中有一部分没听懂，想在课后自然确认。",
    userGoal: "自然地表示自己没完全听懂，并请求对方再说明一下。",
    npcOpening: "授業のあとに少し確認するのは、全然変じゃないですよ。",
    possibleBeats: ["说明没完全听懂", "请求再说一遍", "确认自己理解是否正确", "表达感谢"],
    usefulIntents: ["想说没完全听懂", "想请对方再说明", "想确认理解是否正确", "想道谢"],
    responseOptionsJa: [
      "すみません、少し確認してもいいですか。",
      "さっきの説明が少し難しかったです。",
      "もう一度説明してもらえますか。",
      "こういう理解で合っていますか。",
    ],
    softLanding: "确认后，可以自然转入课堂、研究室、文献或普通校园闲聊。",
    avoid: [
      "不要变成听力测试",
      "不要纠错用户",
      "不要长篇教学",
      "不要让 Haruka 变成授课老师",
    ],
    fallbackUserLines: [
      "すみません、少し確認してもいいですか。",
      "さっきの説明が少し難しかったです。",
      "もう一度説明してもらえますか。",
      "こういう理解で合っていますか。",
    ],
  },
  aoi_ask_interests: {
    id: "aoi_ask_interests",
    npcId: "aoi",
    title: "问最近喜欢什么",
    titleZh: "问最近喜欢什么",
    titleEn: "Ask what they’re into",
    shortLabel: "问最近喜欢什么",
    shortLabelZh: "问最近喜欢什么",
    shortLabelEn: "Current interests",
    setup: "用户想和同级朋友自然开启一个兴趣话题。",
    userGoal: "自然地问对方最近喜欢什么、有没有推荐，或表达自己有点感兴趣。",
    npcOpening: "最近、何かハマってるものある？",
    possibleBeats: ["问最近喜欢什么", "问有没有推荐", "表达有点感兴趣", "追问从哪里开始"],
    usefulIntents: ["想问最近在喜欢什么", "想问有没有推荐", "想说有点感兴趣", "想问从哪里开始"],
    responseOptionsJa: [
      "最近、何にハマってる？",
      "おすすめある？",
      "それ、ちょっと気になる。",
      "どこから見ればいい？",
    ],
    softLanding: "开启兴趣话题后，可以自然继续聊推荐、作品、活动或普通闲聊。",
    avoid: [
      "不要变成采访",
      "不要连续追问太多",
      "不要恋爱化",
      "不要无证据说用户以前喜欢过某物",
    ],
    fallbackUserLines: [
      "最近、何にハマってる？",
      "おすすめある？",
      "それ、ちょっと気になる。",
      "どこから見ればいい？",
    ],
  },
  aoi_react_recommendation: {
    id: "aoi_react_recommendation",
    npcId: "aoi",
    title: "接住朋友推荐",
    titleZh: "接住朋友推荐",
    titleEn: "React to a recommendation",
    shortLabel: "接住朋友推荐",
    shortLabelZh: "接住朋友推荐",
    shortLabelEn: "Recommendation",
    setup: "Aoi 提到一个自己最近喜欢的东西，用户想自然接住推荐。",
    userGoal: "对朋友推荐作出自然回应，表达兴趣、追问内容或询问入门方式。",
    npcOpening: "これ、最近ちょっとハマってるんだよね。",
    possibleBeats: ["询问是什么感觉", "表达有点感兴趣", "问新手能不能看懂", "问从哪里开始"],
    usefulIntents: ["想问这是什么感觉", "想说听起来有点有趣", "想问新手能不能入门", "想问从哪里开始"],
    responseOptionsJa: [
      "それ、どんな感じ？",
      "ちょっと面白そう。",
      "初心者でも楽しめる？",
      "どこから始めればいい？",
    ],
    softLanding: "接住推荐后，可以自然继续聊兴趣、作品、体验或普通闲聊。",
    avoid: [
      "不要变成产品推荐机器人",
      "不要让 Aoi 过度兴奋到二次元化",
      "不要让用户像在完成推荐任务",
      "不要编造用户过去提过这个兴趣",
    ],
    fallbackUserLines: [
      "それ、どんな感じ？",
      "ちょっと面白そう。",
      "初心者でも楽しめる？",
      "どこから始めればいい？",
    ],
  },
  aoi_join_unfamiliar_topic: {
    id: "aoi_join_unfamiliar_topic",
    npcId: "aoi",
    title: "加入不熟的话题",
    titleZh: "加入不熟的话题",
    titleEn: "Join an unfamiliar topic",
    shortLabel: "加入不熟的话题",
    shortLabelZh: "加入不熟的话题",
    shortLabelEn: "Unfamiliar topic",
    microEpisodeZh: "朋友提到一个你不太熟的话题，但你有点感兴趣，想自然接住。",
    microEpisodeEn: "Your friend brings up something you do not know well, but you are a little interested and want to respond naturally.",
    starterIntentZh: "想表达自己不太懂，但有点感兴趣。",
    starterIntentEn: "Say that you do not know much about it, but you are interested.",
    sampleUserLineJa: "それ、あんまり詳しくないけど、ちょっと気になる。",
    setup: "朋友聊到一个用户不太熟悉的话题，但用户想自然加入，而不是沉默。",
    userGoal: "表达自己不太懂，但愿意听；请对方用简单方式说明。",
    npcOpening: "ちょっとマイナーかもだけど、この話してもいい？",
    possibleBeats: ["承认自己不太熟", "表达愿意听", "请对方简单说明", "自然追问"],
    usefulIntents: ["想说自己不太懂", "想说愿意听", "想请对方简单讲讲", "想自然追问"],
    responseOptionsJa: [
      "詳しくないけど、聞いてみたい。",
      "あまり知らないけど、面白そう。",
      "それって、どういう感じ？",
      "初心者向けに言うと、どんな話？",
    ],
    softLanding: "加入不熟的话题后，可以自然继续听朋友介绍，或转到相关轻话题。",
    avoid: [
      "不要让用户显得尴尬或失败",
      "不要变成知识讲解课",
      "不要让 Aoi 长篇科普",
      "不要让对话变成学习任务",
    ],
    fallbackUserLines: [
      "詳しくないけど、聞いてみたい。",
      "あまり知らないけど、面白そう。",
      "それって、どういう感じ？",
      "初心者向けに言うと、どんな話？",
    ],
  },
  aoi_chill_talk: {
    id: "aoi_chill_talk",
    npcId: "aoi",
    title: "说想放空一下",
    titleZh: "说想放空一下",
    titleEn: "Say you want to chill",
    shortLabel: "说想放空一下",
    shortLabelZh: "说想放空一下",
    shortLabelEn: "Chill talk",
    setup: "用户今天有点累，想在学生ラウンジ里和朋友随便聊几句，不进入沉重话题。",
    userGoal: "自然地说今天想放空、想轻松聊，不把气氛变沉重。",
    npcOpening: "今日はラウンジでちょっとだらっとしたい気分かも。",
    possibleBeats: [
      "说今天想放空",
      "说想轻松聊",
      "说有点累但不是重话题",
      "自然转到轻松话题",
    ],
    usefulIntents: ["想说今天想放空", "想说想随便聊", "想说有点累但不沉重", "想轻松待一会儿"],
    responseOptionsJa: [
      "今日はちょっとだらっとしたい。",
      "何も考えずに話したい気分。",
      "ちょっと疲れたけど、重い話じゃないよ。",
      "ゆるく話してもいい？",
    ],
    softLanding: "轻轻表达状态后，应自然转向兴趣、推荐、放课后安排或普通闲聊。",
    avoid: [
      "不要变成心理咨询",
      "不要追问沉重私人问题",
      "不要过度安慰",
      "不要把 Aoi 写成情绪依赖型陪伴角色",
    ],
    fallbackUserLines: [
      "今日はちょっとだらっとしたい。",
      "何も考えずに話したい気分。",
      "ちょっと疲れたけど、重い話じゃないよ。",
      "ゆるく話してもいい？",
    ],
  },
  aoi_after_class_plan: {
    id: "aoi_after_class_plan",
    npcId: "aoi",
    title: "问下课后安排",
    titleZh: "问下课后安排",
    titleEn: "Ask about after class",
    shortLabel: "问下课后安排",
    shortLabelZh: "问下课后安排",
    shortLabelEn: "After class",
    setup: "用户想自然问同级朋友下课后做什么，或轻轻邀请对方在ラウンジ聊一会儿。",
    userGoal: "自然地问对方接下来做什么，或提出轻量、不带压力的邀约。",
    npcOpening: "このあと、どうする？ラウンジで少し話す？",
    possibleBeats: ["问接下来做什么", "邀请在ラウンジ聊一会儿", "问要不要顺路去哪里", "给对方留余地"],
    usefulIntents: ["想问下课后安排", "想邀请聊一会儿", "想问要不要去哪里", "想自然确认对方是否有空"],
    responseOptionsJa: [
      "このあと、何する？",
      "少しラウンジで話さない？",
      "どこか寄っていく？",
      "今日はまっすぐ帰る？",
    ],
    softLanding: "问完安排后，可以自然转入兴趣、推荐、放课后活动或普通闲聊。",
    avoid: [
      "不要恋爱化",
      "不要约会感",
      "不要让 Aoi 显得过黏",
      "不要让邀约变成任务",
    ],
    fallbackUserLines: [
      "このあと、何する？",
      "少しラウンジで話さない？",
      "どこか寄っていく？",
      "今日はまっすぐ帰る？",
    ],
  },
  aoi_soft_decline: {
    id: "aoi_soft_decline",
    npcId: "aoi",
    title: "委婉说下次吧",
    titleZh: "委婉说下次吧",
    titleEn: "Say maybe next time",
    shortLabel: "委婉说下次吧",
    shortLabelZh: "委婉说下次吧",
    shortLabelEn: "Maybe next time",
    setup: "Aoi 轻轻邀请用户下课后去哪里，用户想自然拒绝但不伤关系。",
    userGoal: "用朋友之间的 casual 语气委婉拒绝、说下次再约，或说明今天有点累。",
    npcOpening: "このあと、少しどこか寄っていく？",
    possibleBeats: ["说明今天有点累", "说下次再约", "表示抱歉但保持轻松", "说只聊一会儿也可以"],
    usefulIntents: ["想说今天有点累", "想说下次再约", "想自然拒绝", "想说只聊一会儿也可以"],
    responseOptionsJa: [
      "今日はちょっと疲れてるから、また今度でもいい？",
      "ごめん、今日はまっすぐ帰るね。",
      "また今度誘って。",
      "少しだけなら大丈夫。",
    ],
    softLanding: "委婉拒绝后，应保持朋友关系自然，不制造尴尬，也不让 Aoi 失落或黏人。",
    avoid: [
      "不要让 Aoi 失落或撒娇",
      "不要恋爱化",
      "不要让用户有拒绝压力",
      "不要把拒绝变成关系危机",
    ],
    fallbackUserLines: [
      "今日はちょっと疲れてるから、また今度でもいい？",
      "ごめん、今日はまっすぐ帰るね。",
      "また今度誘って。",
      "少しだけなら大丈夫。",
    ],
  },
  nana_rental_initial_costs: {
    id: "nana_rental_initial_costs",
    npcId: "nana",
    title: "确认租房初期费用",
    shortLabel: "租房初期费用",
    titleEn: "Asking about rental initial costs",
    shortLabelEn: "Rental costs",
    microEpisodeZh: "你刚看到一间房，月租还可以，但不确定礼金、押金、中介费加起来会不会很高。你想先问清楚初期费用。",
    microEpisodeEn: "You found an apartment with reasonable monthly rent, but you are not sure how much the key money, deposit, and agency fee will add up to. You want to ask about the initial costs first.",
    starterIntentZh: "想问初期费用包括哪些项目。",
    starterIntentEn: "Ask what is included in the initial costs.",
    sampleUserLineJa: "初期費用には、どんなものがありますか。",
    setup: "用户正在向 Nana 确认租房初期费用，包括敷金、礼金和仲介手数料。",
    userGoal: "确认初期费用包含哪些项目和大概金额，同时知道具体金额需要向房源窗口确认。",
    npcOpening: "初期費用は項目が多くて分かりにくいですよね。どの費用が気になっていますか？",
    possibleBeats: [
      "问敷金是什么意思",
      "问礼金是什么",
      "问仲介手数料是多少",
      "问总共要付多少",
    ],
    usefulIntents: [
      "问费用意思",
      "问当前房源是否需要礼金",
      "问总金额",
      "问外国籍是否可以申请",
    ],
    responseOptionsJa: [
      "敷金って、何のためのお金ですか。",
      "この物件では礼金は必要ですか。",
      "全部でいくらくらいかかりますか。",
      "外国籍でも申し込めますか。",
    ],
    softLanding: "问完一两个费用后，可以轻轻提醒：具体金额要以实际房源和窗口说明为准。",
    avoid: [
      "不要给租房法律结论",
      "不要保证真实费用金额",
      "不要假装知道具体房源规则",
      "不要长篇解释日本租房制度",
    ],
    fallbackUserLines: [
      "敷金って、何のためのお金ですか。",
      "この物件では礼金は必要ですか。",
      "全部でいくらくらいかかりますか。",
      "外国籍でも申し込めますか。",
    ],
  },
  nana_apartment_viewing_questions: {
    id: "nana_apartment_viewing_questions",
    npcId: "nana",
    title: "看房时确认条件",
    shortLabel: "看房问条件",
    titleEn: "Asking about apartment conditions",
    shortLabelEn: "Viewing questions",
    microEpisodeZh: "你去看一间房，想先确认走到车站要多久，再看看其他生活条件。",
    microEpisodeEn: "You are viewing an apartment and want to check how long the walk to the station takes before asking about other details.",
    starterIntentZh: "想自然确认从房子走到车站的时间。",
    starterIntentEn: "Ask how long it takes to walk to the station.",
    sampleUserLineJa: "駅からどのくらい歩きますか。",
    setup: "用户准备去看房，正在向 Nana 整理需要确认的车站距离、采光、噪音、家具和网络等条件。",
    userGoal: "确认自己最在意的看房条件，并知道具体情况需要在现场或向中介确认。",
    npcOpening: "内見のときは、駅からの距離や周りの音、ネット環境なども気になりますよね。どの条件から確認したいですか？",
    possibleBeats: [
      "问车站距离",
      "问采光和噪音",
      "问家具和设备",
      "问网络情况",
    ],
    usefulIntents: [
      "问距离和时间",
      "问环境条件",
      "问设备清单",
      "问网络情况",
    ],
    responseOptionsJa: [
      "駅からはどのくらいですか。",
      "日当たりや騒音について確認したいです。",
      "家具付きですか。",
      "インターネットは使えますか。",
    ],
    softLanding: "整理几项后，可以轻轻提醒：看房时不用一次确认完所有事情，先看最在意的点就可以。",
    avoid: [
      "不要保证某个房源的条件",
      "不要判断房源好坏",
      "不要变成房产中介",
      "不要替用户做租房决定",
    ],
    fallbackUserLines: [
      "駅からはどのくらいですか。",
      "日当たりや騒音について確認したいです。",
      "家具付きですか。",
      "インターネットは使えますか。",
    ],
  },
  nana_city_office_procedure: {
    id: "nana_city_office_procedure",
    npcId: "nana",
    title: "刚搬来后的役所手续",
    shortLabel: "役所手续",
    titleEn: "City office procedures after moving",
    shortLabelEn: "City office",
    microEpisodeZh: "你刚搬到新的城市，不太确定接下来要去役所办理哪些手续。",
    microEpisodeEn: "You have just moved to a new city and are not sure which procedures you need to handle at the city office.",
    starterIntentZh: "想先问搬家后需要办理什么手续。",
    starterIntentEn: "Ask which procedures are needed after moving.",
    sampleUserLineJa: "引っ越してきたあと、どんな手続きが必要ですか。",
    setup: "用户刚搬来，正在向 Nana 确认住民登録和其他役所手续。",
    userGoal: "整理需要确认的手续、窗口和材料，同时知道具体要求要以役所通知为准。",
    npcOpening: "引っ越してきたばかりだと、役所で何を確認すればいいか迷いますよね。まず気になっている手続きはありますか？",
    possibleBeats: [
      "说刚搬来",
      "说要办手续",
      "问需要什么材料",
      "问窗口在哪里",
    ],
    usefulIntents: [
      "表达刚搬来",
      "说办什么手续",
      "问所需材料",
      "请求说慢一点",
    ],
    responseOptionsJa: [
      "最近こちらに引っ越してきたので、住民登録をしたいです。",
      "必要な書類を確認したいんですけど。",
      "どの窓口に行けばいいですか。",
      "もう少しゆっくり説明してもらえますか。",
    ],
    softLanding: "整理完后，可以轻轻提醒：具体要带什么材料，要以窗口或官方通知为准。",
    avoid: [
      "不要给具体行政政策结论",
      "不要列出完整手续清单",
      "不要保证某个手续的结果",
      "不要把 Nana 写成行政专家",
    ],
    fallbackUserLines: [
      "最近こちらに引っ越してきたので、住民登録をしたいです。",
      "必要な書類を確認したいんですけど。",
      "どの窓口に行けばいいですか。",
      "もう少しゆっくり説明してもらえますか。",
    ],
  },
  nana_ask_repeat_slowly: {
    id: "nana_ask_repeat_slowly",
    npcId: "nana",
    title: "听不懂时请再说一遍",
    shortLabel: "请再说一遍",
    titleEn: "Asking someone to repeat or slow down",
    shortLabelEn: "Repeat slowly",
    microEpisodeZh: "七海刚才说得有点快，你没听清，想礼貌地请她慢一点再说一次。",
    microEpisodeEn: "Nana spoke a little quickly, and you want to politely ask her to repeat it more slowly.",
    starterIntentZh: "想礼貌地请她慢一点再说一次。",
    starterIntentEn: "Politely ask her to repeat it more slowly.",
    sampleUserLineJa: "すみません、もう一度ゆっくり言っていただけますか。",
    setup: "Nana 正在说明窗口的基本流程，但刚才说得有点快，用户没有听清。",
    userGoal: "让对方重复或放慢语速，并确认自己听到的内容。",
    npcOpening: "君の表情がちょっと困ってるみたいね、何かあったの？",
    possibleBeats: [
      "请再说一遍",
      "请说慢一点",
      "确认自己理解是否正确",
      "表达日语还在学习中",
    ],
    usefulIntents: [
      "请求再说一遍",
      "请求放慢",
      "确认理解",
      "表达日语不熟",
    ],
    responseOptionsJa: [
      "すみません、もう一度お願いします。",
      "もう少しゆっくり言ってもらえますか。",
      "今の内容を確認してもいいですか。",
      "まだ日本語を勉強中なので、もう少しゆっくり話してもらえますか。",
    ],
    softLanding: "Nana 放慢速度重新说明，并让用户不用因为请求重复而感到不好意思。",
    avoid: [
      "不要长篇解释为什么听不懂",
      "不要自我否定过多",
      "不要变成日语学习课",
      "不要让用户感觉麻烦别人",
    ],
    fallbackUserLines: [
      "すみません、もう一度お願いします。",
      "もう少しゆっくり言ってもらえますか。",
      "今の内容を確認してもいいですか。",
      "まだ日本語を勉強中なので、もう少しゆっくり話してもらえますか。",
    ],
  },
  nana_phone_internet_contract: {
    id: "nana_phone_internet_contract",
    npcId: "nana",
    title: "开通手机 / 网络",
    shortLabel: "手机和网络",
    titleEn: "Setting up phone or internet",
    shortLabelEn: "Phone / internet",
    microEpisodeZh: "你刚搬进新家，想在家里用网络，但不清楚应该先申请什么。",
    microEpisodeEn: "You have just moved into a new home and want internet access, but you are not sure what you need to apply for.",
    starterIntentZh: "想问在家使用网络需要申请什么。",
    starterIntentEn: "Ask what you need to apply for to use internet at home.",
    sampleUserLineJa: "家でインターネットを使うには、何を申し込めばいいですか。",
    setup: "用户刚到日本，正在向 Nana 整理手机卡、网络契约、月费和所需证件等问题。",
    userGoal: "确认契约条件、月额费用和所需证件，同时知道具体条件要向店铺或运营方确认。",
    npcOpening: "スマホやネットの契約は、プランや期間が分かりにくいことがありますよね。何を確認したいですか？",
    possibleBeats: [
      "问月费是多少",
      "问需要什么证件",
      "问外国籍是否可以申请",
      "问契约期间和解约费用",
    ],
    usefulIntents: [
      "问每月费用",
      "问所需证件",
      "问外国籍是否可以申请",
      "问契约条件",
    ],
    responseOptionsJa: [
      "月額料金はいくらですか。",
      "契約には何が必要ですか。",
      "外国籍でも契約できますか。",
      "契約期間や解約料について確認したいです。",
    ],
    softLanding: "确认基本问题后，可以提醒用户：具体条件要以店头或契约说明为准。",
    avoid: [
      "不要推荐具体运营商",
      "不要保证契约能通过",
      "不要给金融或信用判断",
      "不要长篇解释日本通信套餐",
    ],
    fallbackUserLines: [
      "月額料金はいくらですか。",
      "契約には何が必要ですか。",
      "外国籍でも契約できますか。",
      "契約期間や解約料について確認したいです。",
    ],
  },
  nana_garbage_rules: {
    id: "nana_garbage_rules",
    npcId: "nana",
    title: "问垃圾分类规则",
    shortLabel: "垃圾分类",
    titleEn: "Ask about garbage rules",
    shortLabelEn: "Garbage rules",
    microEpisodeZh: "你准备扔一袋垃圾，但不确定它应该在哪一天拿出去。",
    microEpisodeEn: "You are ready to take out a bag of garbage, but you are not sure which day it should go out.",
    starterIntentZh: "想确认这类垃圾应该星期几投放。",
    starterIntentEn: "Ask which day this type of garbage should be put out.",
    sampleUserLineJa: "このごみは、何曜日に出せばいいですか。",
    setup: "用户刚开始独立生活，正在向 Nana 询问垃圾分类、投放日期和投放地点。",
    userGoal: "确认垃圾分类、投放日期或投放地点，同时知道具体规则需要向当地确认。",
    npcOpening: "ゴミ出しって、地域によってルールが違うので迷いますよね。どんなごみについて聞きたいですか？",
    possibleBeats: [
      "问垃圾怎么分类",
      "问哪天可以扔",
      "问在哪里扔",
      "问某个物品属于哪类垃圾",
    ],
    usefulIntents: [
      "问分类方法",
      "问投放日期",
      "问投放地点",
      "问具体物品怎么扔",
    ],
    responseOptionsJa: [
      "ゴミの分別について聞きたいです。",
      "燃えるゴミは何曜日に出せますか。",
      "ゴミはどこに出せばいいですか。",
      "これは何ゴミになりますか。",
    ],
    softLanding: "自然回应用户的问题，并轻轻提醒具体规则要以所在地区或公寓说明为准。",
    avoid: [
      "不要断言具体地区规则",
      "不要列完整垃圾分类百科",
      "不要让用户觉得规则很可怕",
      "不要编造真实地名或地区规则",
    ],
    fallbackUserLines: [
      "ゴミの分別について聞きたいです。",
      "燃えるゴミは何曜日に出せますか。",
      "ゴミはどこに出せばいいですか。",
      "これは何ゴミになりますか。",
    ],
  },
  nana_pharmacy_symptoms: {
    id: "nana_pharmacy_symptoms",
    npcId: "nana",
    title: "药局说明症状",
    shortLabel: "药局说明症状",
    titleEn: "Explain symptoms at a pharmacy",
    shortLabelEn: "Pharmacy",
    microEpisodeZh: "你的喉咙有点痛，但没有发烧，想在药局先简单说明现在的情况。",
    microEpisodeEn: "Your throat hurts a little, but you do not have a fever. You want to briefly explain how you feel at a pharmacy.",
    starterIntentZh: "想简单说明喉咙痛，但没有发烧。",
    starterIntentEn: "Say that your throat hurts a little, but you do not have a fever.",
    sampleUserLineJa: "少しのどが痛くて、熱はありません。",
    setup: "用户身体有点不舒服，正在向 Nana 整理去药局时需要说明的症状和想确认的问题。",
    userGoal: "说明当前症状和持续时间，并知道具体用药或就医判断要向专业人员确认。",
    npcOpening: "薬局では、症状といつから続いているかを伝えると聞いてもらいやすいですよ。今、どんな感じですか？",
    possibleBeats: [
      "说明头痛",
      "说明发烧",
      "说明喉咙痛",
      "询问是否需要去医院",
    ],
    usefulIntents: [
      "说明症状",
      "询问有没有适合的药",
      "询问是否需要去医院",
      "请求慢一点说明",
    ],
    responseOptionsJa: [
      "頭が痛いです。",
      "少し熱があります。",
      "のどが痛いです。",
      "病院に行ったほうがいいですか。",
    ],
    softLanding: "自然接住用户的症状信息，并提醒：症状が重いときや不安なときは、医療機関で確認してください。",
    avoid: [
      "不要做医疗诊断",
      "不要推荐具体药物",
      "不要判断病情严重程度",
      "不要替用户决定是否就医",
    ],
    fallbackUserLines: [
      "頭が痛いです。",
      "少し熱があります。",
      "のどが痛いです。",
      "病院に行ったほうがいいですか。",
    ],
  },
  nana_bank_post_office: {
    id: "nana_bank_post_office",
    npcId: "nana",
    title: "银行 / 邮局窗口咨询",
    shortLabel: "银行和邮局",
    titleEn: "Ask at a bank or post office",
    shortLabelEn: "Bank / post office",
    microEpisodeZh: "你想去窗口开一个账户，但不确定需要带哪些证件或材料。",
    microEpisodeEn: "You want to open an account at the counter, but you are not sure which documents or materials you need.",
    starterIntentZh: "想问开户需要准备什么。",
    starterIntentEn: "Ask what is needed to open an account.",
    sampleUserLineJa: "口座を作るには、何が必要ですか。",
    setup: "用户正在向 Nana 整理去银行或邮局窗口时想办理的事项和需要确认的材料。",
    userGoal: "确认办理事项、所需材料和提交窗口，同时知道具体条件要以窗口说明为准。",
    npcOpening: "銀行や郵便局の窓口は、必要な書類が分かりにくいことがありますよね。今日は何を確認したいですか？",
    possibleBeats: [
      "说明想开户",
      "问需要什么证件",
      "说明想寄东西",
      "问怎么填写表格",
    ],
    usefulIntents: [
      "想开户",
      "问所需证件",
      "想寄东西",
      "问填写方式",
    ],
    responseOptionsJa: [
      "口座を作るには、何が必要ですか。",
      "本人確認書類は、これで大丈夫ですか。",
      "荷物を送るには、どの窓口に行けばいいですか。",
      "この書類は、どこに出せばいいですか。",
    ],
    softLanding: "整理后可以提醒用户：具体材料和条件要以窗口说明为准。",
    avoid: [
      "不要给金融建议",
      "不要保证开户或手续成功",
      "不要解释复杂金融制度",
      "不要替用户判断具体业务能不能办理",
    ],
    fallbackUserLines: [
      "口座を作るには、何が必要ですか。",
      "本人確認書類は、これで大丈夫ですか。",
      "荷物を送るには、どの窓口に行けばいいですか。",
      "この書類は、どこに出せばいいですか。",
    ],
  },
} as const satisfies Record<string, ConversationSceneConfig>;

export type ConversationSceneId = keyof typeof CONVERSATION_SCENES;
export type ConversationScene = (typeof CONVERSATION_SCENES)[ConversationSceneId];

export function isConversationSceneId(value: string): value is ConversationSceneId {
  return value in CONVERSATION_SCENES;
}

export function getConversationScene(
  sceneId: string | null | undefined,
): ConversationScene | null {
  if (!sceneId || !isConversationSceneId(sceneId)) return null;
  return CONVERSATION_SCENES[sceneId];
}

export function getConversationScenesForNpc(npcId: NpcId): ConversationScene[] {
  return Object.values(CONVERSATION_SCENES).filter((scene) => scene.npcId === npcId);
}
