import type { NpcId } from "./npc";

type ConversationSceneConfig = {
  id: string;
  npcId: NpcId;
  title: string;
  titleZh?: string;
  titleEn?: string;
  shortLabel: string;
  shortLabelZh?: string;
  shortLabelEn?: string;
  microEpisodeZh?: string;
  microEpisodeEn?: string;
  starterIntentZh?: string;
  starterIntentEn?: string;
  sampleUserLineJa?: string;
  setup: string;
  userGoal: string;
  npcOpening: string;
  possibleBeats: string[];
  usefulIntents: string[];
  softLanding: string;
  avoid: string[];
  fallbackUserLines: string[];
  responseOptionsJa?: string[];
};

export const CONVERSATION_SCENES = {
  kimura_bento_checkout: {
    id: "kimura_bento_checkout",
    npcId: "kimura",
    title: "便当结账",
    titleZh: "便当结账",
    titleEn: "Bento checkout",
    shortLabel: "便当结账",
    shortLabelZh: "收银台对话",
    shortLabelEn: "Counter chat",
    microEpisodeZh: "你拿着便当来到收银台，想请木村帮忙加热。",
    microEpisodeEn: "You bring a bento to the counter and want Kimura to heat it up.",
    starterIntentZh: "想请店员帮忙加热便当。",
    starterIntentEn: "Ask the clerk to heat up the bento.",
    sampleUserLineJa: "これ、温めてもらえますか。",
    setup: "用户拿着便当来到便利店收银台，准备完成一段很短的结账对话。",
    userGoal: "顺利结账，并自然听懂或回应店员常见提问。",
    npcOpening: "こちらのお弁当、温めますか？",
    possibleBeats: ["是否加热", "是否需要袋子", "支付方式", "简短收尾"],
    usefulIntents: [
      "请帮我加热",
      "不用加热",
      "需要袋子",
      "不用袋子",
      "可以刷卡吗",
      "就这些",
      "谢谢",
    ],
    softLanding: "完成一小段结账对话后，自然回到随便聊，不做任务完成判定。",
    avoid: [
      "不要做成收银流程考试",
      "不要逐项检查 possibleBeats",
      "不要把用户说错当成错误",
      "不要强行问完所有步骤",
      "不要把 Kimura 写成收银机器人",
    ],
    fallbackUserLines: [
      "はい、お願いします。",
      "温めなくても大丈夫です。",
      "袋もお願いします。",
      "カードで払えますか？",
    ],
    responseOptionsJa: [
      "はい、お願いします。",
      "温めなくても大丈夫です。",
      "袋もお願いします。",
      "カードで払えますか？",
    ],
  },
  kimura_find_item: {
    id: "kimura_find_item",
    npcId: "kimura",
    title: "找商品",
    titleZh: "找商品",
    titleEn: "Find an item",
    shortLabel: "找商品",
    shortLabelZh: "问商品位置",
    shortLabelEn: "Ask where it is",
    microEpisodeZh: "你在店里找不到想买的饮料，想问木村放在哪里。",
    microEpisodeEn: "You cannot find the drink you want and ask Kimura where it is.",
    starterIntentZh: "想问饮料放在哪里。",
    starterIntentEn: "Ask where the drinks are.",
    sampleUserLineJa: "飲み物はどのあたりですか。",
    setup: "用户在便利店里找商品，但不确定摆放位置，想问店员。",
    userGoal: "询问商品位置，并听懂简单指引。",
    npcOpening: "何か探してる？ 声かけてくれたら案内するよ。",
    possibleBeats: ["询问商品位置", "确认大概区域", "请求再说一遍", "道谢"],
    usefulIntents: [
      "想问某个商品在哪里",
      "想确认是不是这个方向",
      "想请对方再说一遍",
      "想道谢",
    ],
    softLanding: "找到商品后，可以自然回到普通闲聊，或者继续问推荐。",
    avoid: [
      "不要变成店内地图说明",
      "不要长篇解释货架布局",
      "不要把用户当成在完成任务",
      "不要强行要求用户说出具体商品",
    ],
    fallbackUserLines: [
      "お菓子はどこにありますか？",
      "飲み物はどのあたりですか？",
      "すみません、もう一度お願いします。",
      "ありがとうございます。見てみます。",
    ],
    responseOptionsJa: [
      "お菓子はどこにありますか？",
      "飲み物はどのあたりですか？",
      "すみません、もう一度お願いします。",
      "ありがとうございます。見てみます。",
    ],
  },
  kimura_oden_order: {
    id: "kimura_oden_order",
    npcId: "kimura",
    title: "点关东煮",
    titleZh: "点关东煮",
    titleEn: "Order oden",
    shortLabel: "点关东煮",
    shortLabelZh: "点几样小吃",
    shortLabelEn: "Order a snack",
    microEpisodeZh: "你看到收银台旁的关东煮，想点萝卜和鸡蛋。",
    microEpisodeEn: "You see oden by the counter and want to order daikon and an egg.",
    starterIntentZh: "想点两样关东煮。",
    starterIntentEn: "Order two pieces of oden.",
    sampleUserLineJa: "大根とたまごを一つずつお願いします。",
    setup: "用户在收银台旁看到关东煮，想点几样。",
    userGoal: "点几样关东煮，并自然询问推荐。",
    npcOpening: "おでん、まだありますよ。どうします？",
    possibleBeats: ["询问推荐", "点具体食物", "确认数量", "简单结束"],
    usefulIntents: [
      "想问推荐",
      "想点大根和鸡蛋",
      "想要带走",
      "想要芥末或汤",
    ],
    softLanding: "点完关东煮后，可以自然聊到天气、夜晚、便利店小吃或普通闲聊。",
    avoid: [
      "不要变成菜单教学",
      "不要强行推销",
      "不要连续追问太多配料",
      "不要让 Kimura 变成点餐训练机器",
    ],
    fallbackUserLines: [
      "おすすめありますか？",
      "大根とたまごを一つずつお願いします。",
      "持ち帰りでお願いします。",
      "からしもお願いします。",
    ],
    responseOptionsJa: [
      "おすすめありますか？",
      "大根とたまごを一つずつお願いします。",
      "持ち帰りでお願いします。",
      "からしもお願いします。",
    ],
  },
  kimura_payment_method: {
    id: "kimura_payment_method",
    npcId: "kimura",
    title: "问支付方式",
    titleZh: "问支付方式",
    titleEn: "Ask how to pay",
    shortLabel: "问支付方式",
    shortLabelZh: "确认怎么付款",
    shortLabelEn: "Check payment",
    microEpisodeZh: "轮到你结账了，但不确定这里能不能刷卡。",
    microEpisodeEn: "It is your turn to pay, but you are not sure whether cards are accepted.",
    starterIntentZh: "想确认能不能刷卡。",
    starterIntentEn: "Ask whether you can pay by card.",
    sampleUserLineJa: "カードで払えますか。",
    setup: "用户在便利店结账时，想确认可以用哪种方式付款。",
    userGoal: "询问是否可以用卡、手机支付或现金付款。",
    npcOpening: "お支払い、どうします？",
    possibleBeats: [
      "询问能否用卡",
      "询问能否用手机支付",
      "说明想用现金",
      "简单结束寒暄",
    ],
    usefulIntents: [
      "想问能不能刷卡",
      "想问能不能用手机支付",
      "想说用现金",
      "想道谢",
    ],
    responseOptionsJa: [
      "カードで払えますか。",
      "スマホ決済は使えますか。",
      "現金でお願いします。",
      "ありがとうございます。",
    ],
    softLanding: "确认支付方式后，可以自然结束结账或继续闲聊。",
    avoid: [
      "不要讲解复杂支付系统",
      "不要列出过多支付品牌",
      "不要变成收银流程教学",
      "不要检查用户是否完成步骤",
    ],
    fallbackUserLines: [
      "カードで払えますか。",
      "スマホ決済は使えますか。",
      "現金でお願いします。",
      "ありがとうございます。",
    ],
  },
  kimura_discount_sticker: {
    id: "kimura_discount_sticker",
    npcId: "kimura",
    title: "问打折",
    titleZh: "问打折",
    titleEn: "Ask about discounts",
    shortLabel: "问打折",
    shortLabelZh: "确认优惠贴纸",
    shortLabelEn: "Check discount",
    microEpisodeZh: "你看到便当上贴着优惠贴纸，想确认现在的价格。",
    microEpisodeEn: "You see a discount sticker on a bento and want to confirm the current price.",
    starterIntentZh: "想确认便当是否已经打折。",
    starterIntentEn: "Ask whether the bento is already discounted.",
    sampleUserLineJa: "これはもう値引きされていますか。",
    setup: "用户看到便当或熟食上有优惠贴纸，想确认是否已经打折，或想问打折大概什么时候开始。",
    userGoal: "自然地询问商品是否打折、优惠贴纸是什么意思、什么时候可能会降价。",
    npcOpening: "あ、それ値引きシール貼ってあるやつだね。",
    possibleBeats: [
      "确认商品是否已经打折",
      "询问优惠贴纸的意思",
      "询问大概什么时候会打折",
      "自然回应不确定的规则",
    ],
    usefulIntents: [
      "想问这个是不是已经打折",
      "想问优惠贴纸是什么意思",
      "想问一般什么时候会便宜",
      "想礼貌地确认价格",
    ],
    responseOptionsJa: [
      "これはもう値引きされていますか。",
      "このシールはどういう意味ですか。",
      "何時ごろから値引きになることが多いですか。",
      "この値段で合っていますか。",
    ],
    softLanding: "确认价格或优惠后，可以自然回到结账、便当选择或普通闲聊。",
    avoid: [
      "不要假装所有便利店都有固定打折时间",
      "不要给出现实店铺政策断言",
      "不要让用户听起来像在强硬讨价还价",
      "不要变成省钱攻略或购物教学",
      "不要检查用户是否完成步骤",
    ],
    fallbackUserLines: [
      "これはもう値引きされていますか。",
      "このシールはどういう意味ですか。",
      "何時ごろから値引きになることが多いですか。",
      "この値段で合っていますか。",
    ],
  },
  kimura_hot_snack: {
    id: "kimura_hot_snack",
    npcId: "kimura",
    title: "买热柜小食",
    titleZh: "买热柜小食",
    titleEn: "Order a hot snack",
    shortLabel: "买热柜小食",
    shortLabelZh: "点热柜小吃",
    shortLabelEn: "Hot snack order",
    microEpisodeZh: "你看到热柜里还有小食，想买一个带走。",
    microEpisodeEn: "You see some snacks left in the hot case and want to buy one.",
    starterIntentZh: "想点一个热柜小食。",
    starterIntentEn: "Order one snack from the hot case.",
    sampleUserLineJa: "これを一つお願いします。",
    setup: "用户在收银台旁看到热柜里的炸物或小吃，想点一个。",
    userGoal: "自然地询问热柜小食、点一个、确认是否还有。",
    npcOpening: "レジ横のホットスナック、今ならまだありますよ。",
    possibleBeats: [
      "询问还有什么",
      "点一个热柜小食",
      "确认是否现成",
      "简单结束寒暄",
    ],
    usefulIntents: [
      "想问还有什么",
      "想点一个炸鸡或小吃",
      "想问是不是热的",
      "想道谢",
    ],
    responseOptionsJa: [
      "今、何がありますか。",
      "これを一つお願いします。",
      "まだ温かいですか。",
      "じゃあ、それを一つください。",
    ],
    softLanding: "点完热柜小食后，可以自然聊到夜晚、便利店小吃或普通闲聊。",
    avoid: [
      "不要使用真实便利店品牌名",
      "不要变成菜单教学",
      "不要强行推销",
      "不要连续追问太多配料",
      "不要让 Kimura 变成点餐训练机器人",
    ],
    fallbackUserLines: [
      "今、何がありますか。",
      "これを一つお願いします。",
      "まだ温かいですか。",
      "じゃあ、それを一つください。",
    ],
  },
  misaki_order_coffee: {
    id: "misaki_order_coffee",
    npcId: "misaki",
    title: "点咖啡",
    titleZh: "点咖啡",
    titleEn: "Order coffee",
    shortLabel: "点咖啡",
    shortLabelZh: "点一杯饮料",
    shortLabelEn: "Order a drink",
    microEpisodeZh: "你走到柜台，想点一杯热咖啡在店里喝。",
    microEpisodeEn: "You reach the counter and want a hot coffee to drink in the cafe.",
    starterIntentZh: "想点一杯热咖啡。",
    starterIntentEn: "Order a hot coffee.",
    sampleUserLineJa: "ホットコーヒーを一つお願いします。",
    setup: "用户在咖啡馆想点一杯咖啡。",
    userGoal: "自然地点一杯咖啡，并说明堂食或外带。",
    npcOpening: "いらっしゃいませ。今日は何にしますか？",
    possibleBeats: [
      "点热咖啡或冰咖啡",
      "说明堂食或外带",
      "简单确认",
      "自然道谢",
    ],
    usefulIntents: [
      "想点一杯热咖啡",
      "想点一杯冰咖啡",
      "想说在店里喝",
      "想说外带",
    ],
    responseOptionsJa: [
      "ホットコーヒーを一つお願いします。",
      "アイスコーヒーをお願いします。",
      "店内でお願いします。",
      "持ち帰りでお願いします。",
    ],
    softLanding: "点完咖啡后，可以自然聊到味道、座位或休息。",
    avoid: [
      "不要变成点单考试",
      "不要讲解复杂咖啡知识",
      "不要过度客服化",
      "不要检查用户是否完成步骤",
    ],
    fallbackUserLines: [
      "ホットコーヒーを一つお願いします。",
      "アイスコーヒーをお願いします。",
      "店内でお願いします。",
      "持ち帰りでお願いします。",
    ],
  },
  misaki_ask_recommendation: {
    id: "misaki_ask_recommendation",
    npcId: "misaki",
    title: "问咖啡推荐",
    titleZh: "问咖啡推荐",
    titleEn: "Ask for a recommendation",
    shortLabel: "问推荐",
    shortLabelZh: "问咖啡推荐",
    shortLabelEn: "Coffee suggestion",
    microEpisodeZh: "今天有点困，但不想喝太苦的咖啡。你想让美咲推荐一杯温和一点的。",
    microEpisodeEn: "You feel a little sleepy today, but you do not want coffee that is too bitter. You want Misaki to recommend something mild.",
    starterIntentZh: "想问有没有不太苦、比较温和的推荐。",
    starterIntentEn: "Ask for a mild coffee recommendation that is not too bitter.",
    sampleUserLineJa: "あまり苦くないコーヒーで、おすすめはありますか。",
    setup: "用户不知道点什么，想问美咲有没有推荐。",
    userGoal: "自然地询问推荐，并表达今天想喝什么感觉的咖啡。",
    npcOpening: "今日は少し落ち着いた味の豆もありますよ。気分に合うもの、探しますか？",
    possibleBeats: [
      "询问推荐",
      "表达想要轻一点或香一点",
      "说明今天想休息",
      "简单确认",
    ],
    usefulIntents: [
      "想问推荐",
      "想喝轻一点的味道",
      "想要香气好的咖啡",
      "想说今天想休息一下",
    ],
    responseOptionsJa: [
      "おすすめはありますか。",
      "今日は軽めの味がいいです。",
      "香りがいいものはありますか。",
      "少し休みたい気分です。",
    ],
    softLanding: "选好推荐后，可以自然聊到咖啡味道、休息或店里的安静时间。",
    avoid: [
      "不要变成咖啡讲座",
      "不要列太多专业术语",
      "不要过度安慰用户",
      "不要像心理咨询一样追问情绪",
    ],
    fallbackUserLines: [
      "おすすめはありますか。",
      "今日は軽めの味がいいです。",
      "香りがいいものはありますか。",
      "少し休みたい気分です。",
    ],
  },
  misaki_order_dessert: {
    id: "misaki_order_dessert",
    npcId: "misaki",
    title: "点甜点",
    titleZh: "点甜点",
    titleEn: "Order dessert",
    shortLabel: "点甜点",
    shortLabelZh: "点甜点",
    shortLabelEn: "Dessert",
    microEpisodeZh: "你想配咖啡吃一点甜的，正在看看有什么甜点。",
    microEpisodeEn: "You want something sweet with your coffee and are looking at the desserts.",
    starterIntentZh: "想问有什么甜点。",
    starterIntentEn: "Ask what desserts are available.",
    sampleUserLineJa: "デザートは何がありますか。",
    setup: "用户在咖啡馆想点一份甜点或小蛋糕。",
    userGoal: "自然地点一份甜点，或询问哪种甜点适合配咖啡。",
    npcOpening: "ケーキも少しありますよ。よかったら一緒に見ますか？",
    possibleBeats: [
      "询问有什么甜点",
      "点一份蛋糕",
      "询问适合配咖啡的甜点",
      "简单确认",
    ],
    usefulIntents: [
      "想问有什么甜点",
      "想点一份蛋糕",
      "想问哪种适合配咖啡",
      "想说只要一个",
    ],
    responseOptionsJa: [
      "デザートは何がありますか。",
      "このケーキを一つお願いします。",
      "コーヒーに合うものはありますか。",
      "一つだけで大丈夫です。",
    ],
    softLanding: "点完甜点后，可以自然聊到咖啡、味道或店里的轻松时间。",
    avoid: [
      "不要变成甜点菜单教学",
      "不要列太多复杂品类",
      "不要强行推销",
      "不要让 Misaki 变成客服机器人",
    ],
    fallbackUserLines: [
      "デザートは何がありますか。",
      "このケーキを一つお願いします。",
      "コーヒーに合うものはありますか。",
      "一つだけで大丈夫です。",
    ],
  },
  misaki_find_seat: {
    id: "misaki_find_seat",
    npcId: "misaki",
    title: "找座位",
    titleZh: "找座位",
    titleEn: "Find a seat",
    shortLabel: "找座位",
    shortLabelZh: "找座位",
    shortLabelEn: "Seat",
    microEpisodeZh: "你一个人来到咖啡馆，想确认窗边的位置能不能坐。",
    microEpisodeEn: "You come to the cafe alone and want to check whether you can sit by the window.",
    starterIntentZh: "想确认这个位置能不能坐。",
    starterIntentEn: "Ask whether you can sit here.",
    sampleUserLineJa: "ここに座ってもいいですか。",
    setup: "用户进入咖啡馆后，想确认是否可以坐某个位置，或说明自己是一个人。",
    userGoal: "自然地询问座位、说明一个人来、或说明朋友稍后会来。",
    npcOpening: "お一人ですか？空いている席、いくつかありますよ。",
    possibleBeats: [
      "说明一个人来",
      "询问能不能坐这里",
      "说明朋友稍后会来",
      "简单道谢",
    ],
    usefulIntents: [
      "想说一个人",
      "想问这里能不能坐",
      "想说朋友等会儿来",
      "想道谢",
    ],
    responseOptionsJa: [
      "一人です。",
      "ここに座ってもいいですか。",
      "あとで友達が来ます。",
      "ありがとうございます。ここにします。",
    ],
    softLanding: "找到座位后，可以自然转入点单、咖啡推荐或普通闲聊。",
    avoid: [
      "不要变成座位规则说明",
      "不要过度安慰用户",
      "不要让 Misaki 显得过分亲密",
      "不要把用户状态总结得太重",
    ],
    fallbackUserLines: [
      "一人です。",
      "ここに座ってもいいですか。",
      "あとで友達が来ます。",
      "ありがとうございます。ここにします。",
    ],
  },
  taisho_enter_izakaya: {
    id: "taisho_enter_izakaya",
    npcId: "taisho",
    title: "第一次进店",
    titleZh: "第一次进店",
    titleEn: "Enter the izakaya",
    shortLabel: "第一次进店",
    shortLabelZh: "第一次进店",
    shortLabelEn: "First visit",
    microEpisodeZh: "你第一次走进大将的居酒屋，想先说明自己是一个人。",
    microEpisodeEn: "You enter Taisho's izakaya for the first time and want to say you are alone.",
    starterIntentZh: "想说明自己一个人来。",
    starterIntentEn: "Say that you are dining alone.",
    sampleUserLineJa: "一人です。",
    setup: "用户第一次走进居酒屋，不知道怎么自然开口。",
    userGoal: "自然地打招呼、说明人数，并询问是否可以坐下。",
    npcOpening: "いらっしゃい。何名さん？",
    possibleBeats: ["说明人数", "询问能不能坐吧台", "说明第一次来", "简单寒暄"],
    usefulIntents: ["想说一个人", "想问能不能坐这里", "想说第一次来", "想简单打招呼"],
    responseOptionsJa: [
      "一人です。",
      "ここに座ってもいいですか。",
      "初めて来ました。",
      "よろしくお願いします。",
    ],
    softLanding: "坐下后，可以自然转入问推荐、点饮料、点菜或普通闲聊。",
    avoid: [
      "不要变成入店流程教学",
      "不要像餐厅客服",
      "不要让 Taisho 太正式",
      "不要检查用户是否完成步骤",
    ],
    fallbackUserLines: [
      "一人です。",
      "ここに座ってもいいですか。",
      "初めて来ました。",
      "よろしくお願いします。",
    ],
  },
  taisho_first_drink: {
    id: "taisho_first_drink",
    npcId: "taisho",
    title: "先点一杯",
    titleZh: "先点一杯",
    titleEn: "Order a first drink",
    shortLabel: "先点一杯",
    shortLabelZh: "先点一杯",
    shortLabelEn: "First drink",
    microEpisodeZh: "你刚坐下，想先点一杯饮料。",
    microEpisodeEn: "You have just sat down and want to order a drink first.",
    starterIntentZh: "想先点一杯饮料。",
    starterIntentEn: "Order a drink first.",
    sampleUserLineJa: "まず一杯お願いします。",
    setup: "用户坐下后想先点一杯饮料。",
    userGoal: "自然地点一杯饮料，并说明想先慢慢看菜单。",
    npcOpening: "まず飲み物、どうする？",
    possibleBeats: ["点一杯饮料", "询问有什么饮料", "说明先看菜单", "简单确认"],
    usefulIntents: ["想先点一杯", "想问有什么饮料", "想先看菜单", "想简单确认"],
    responseOptionsJa: [
      "まず一杯お願いします。",
      "飲み物は何がありますか。",
      "先にメニューを見てもいいですか。",
      "じゃあ、それでお願いします。",
    ],
    softLanding: "点完第一杯后，可以自然转入问推荐、点小菜或普通闲聊。",
    avoid: [
      "不要变成酒类介绍",
      "不要强行推荐酒",
      "不要列太长饮料菜单",
      "不要催用户点菜",
    ],
    fallbackUserLines: [
      "まず一杯お願いします。",
      "飲み物は何がありますか。",
      "先にメニューを見てもいいですか。",
      "じゃあ、それでお願いします。",
    ],
  },
  taisho_no_alcohol: {
    id: "taisho_no_alcohol",
    npcId: "taisho",
    title: "不喝酒时怎么说",
    titleZh: "不喝酒时怎么说",
    titleEn: "Say you don't drink",
    shortLabel: "不喝酒",
    shortLabelZh: "不喝酒",
    shortLabelEn: "No alcohol",
    microEpisodeZh: "今晚你不想喝酒，想点一杯无酒精饮料。",
    microEpisodeEn: "You do not want alcohol tonight and would like a non-alcoholic drink.",
    starterIntentZh: "想说明今天不喝酒。",
    starterIntentEn: "Say that you are not drinking alcohol today.",
    sampleUserLineJa: "今日はお酒は飲まないです。",
    setup: "用户在居酒屋不想喝酒，想自然说明自己今天不喝酒。",
    userGoal: "自然地说不喝酒，并询问无酒精饮料或适合配饭的东西。",
    npcOpening: "飲み物、どうする？",
    possibleBeats: ["说明今天不喝酒", "询问无酒精饮料", "点茶或软饮", "自然缓和气氛"],
    usefulIntents: ["想说今天不喝酒", "想问有没有无酒精饮料", "想点茶", "想自然解释"],
    responseOptionsJa: [
      "今日はお酒は飲まないです。",
      "ノンアルコールの飲み物はありますか。",
      "お茶でお願いします。",
      "今日は軽く食べるだけにします。",
    ],
    softLanding: "说明不喝酒后，可以自然转向点菜、吃点热的或普通闲聊。",
    avoid: [
      "不要劝酒",
      "不要调侃用户不喝酒",
      "不要让用户感到压力",
      "不要变成酒类推荐",
    ],
    fallbackUserLines: [
      "今日はお酒は飲まないです。",
      "ノンアルコールの飲み物はありますか。",
      "お茶でお願いします。",
      "今日は軽く食べるだけにします。",
    ],
  },
  taisho_ask_recommendation: {
    id: "taisho_ask_recommendation",
    npcId: "taisho",
    title: "问今日推荐",
    titleZh: "问今日推荐",
    titleEn: "Ask today's recommendation",
    shortLabel: "问推荐",
    shortLabelZh: "问推荐",
    shortLabelEn: "Recommendation",
    microEpisodeZh: "你不知道点什么，想问大将今天有什么推荐。",
    microEpisodeEn: "You are not sure what to order and ask Taisho for today's recommendation.",
    starterIntentZh: "想问今天的推荐。",
    starterIntentEn: "Ask for today's recommendation.",
    sampleUserLineJa: "今日のおすすめはありますか。",
    setup: "用户坐下后，不知道点什么，想问大将今天有什么推荐。",
    userGoal: "自然地询问推荐，并表达想吃温热、轻一点或下饭的东西。",
    npcOpening: "今日は何か食べたい感じのもの、ある？",
    possibleBeats: ["询问推荐", "表达想吃温热的东西", "表达想吃轻一点的东西", "简单确认"],
    usefulIntents: ["想问今日推荐", "想吃温热的东西", "想吃轻一点", "想让大将推荐"],
    responseOptionsJa: [
      "今日のおすすめはありますか。",
      "温かいものが食べたいです。",
      "軽めのものがいいです。",
      "大将のおすすめでお願いします。",
    ],
    softLanding: "问完推荐后，可以自然进入点菜、聊一天结束或普通闲聊。",
    avoid: [
      "不要列太长菜单",
      "不要变成美食攻略",
      "不要强行推销",
      "不要说教用户该吃什么",
    ],
    fallbackUserLines: [
      "今日のおすすめはありますか。",
      "温かいものが食べたいです。",
      "軽めのものがいいです。",
      "大将のおすすめでお願いします。",
    ],
  },
  taisho_order_small_dish: {
    id: "taisho_order_small_dish",
    npcId: "taisho",
    title: "点一份小菜",
    titleZh: "点一份小菜",
    titleEn: "Order a small dish",
    shortLabel: "点小菜",
    shortLabelZh: "点小菜",
    shortLabelEn: "Small dish",
    microEpisodeZh: "你只想轻松吃一点，想点一份小菜。",
    microEpisodeEn: "You only want a light bite and would like one small dish.",
    starterIntentZh: "想点一份小菜。",
    starterIntentEn: "Order one small dish.",
    sampleUserLineJa: "小さいおかずを一つお願いします。",
    setup: "用户想点一份小菜或下酒菜，但不想点太多。",
    userGoal: "自然地点一份小菜、说明只想简单吃点。",
    npcOpening: "ちょっとつまむ感じでいい？",
    possibleBeats: ["表达想简单吃点", "点一份小菜", "询问有什么适合一个人的", "简单确认"],
    usefulIntents: ["想简单吃点", "想点一份小菜", "想问一个人适合点什么", "想说先这样"],
    responseOptionsJa: [
      "軽くつまめるものはありますか。",
      "小さいおかずを一つお願いします。",
      "一人でも食べやすいものはありますか。",
      "とりあえず、それでお願いします。",
    ],
    softLanding: "点完小菜后，可以自然聊到口味、一天结束或继续闲聊。",
    avoid: [
      "不要变成菜单教学",
      "不要连续推很多菜",
      "不要让用户感觉必须继续点",
      "不要让 Taisho 变成点餐训练机器人",
    ],
    fallbackUserLines: [
      "軽くつまめるものはありますか。",
      "小さいおかずを一つお願いします。",
      "一人でも食べやすいものはありますか。",
      "とりあえず、それでお願いします。",
    ],
  },
  taisho_add_order: {
    id: "taisho_add_order",
    npcId: "taisho",
    title: "追加点单",
    titleZh: "追加点单",
    titleEn: "Order more",
    shortLabel: "追加点单",
    shortLabelZh: "追加点单",
    shortLabelEn: "Add order",
    microEpisodeZh: "你已经吃了一会儿，想再加点一份菜。",
    microEpisodeEn: "You have been eating for a while and want to add one more dish.",
    starterIntentZh: "想再加点一份菜。",
    starterIntentEn: "Add one more dish to the order.",
    sampleUserLineJa: "もう一品お願いします。",
    setup: "用户已经点过一轮，想再加点一份菜或一杯饮料。",
    userGoal: "自然地追加点单，或询问能不能再加一份。",
    npcOpening: "もう少し何かいく？",
    possibleBeats: ["想再点一份", "询问还能不能加单", "点同样的东西", "简单确认"],
    usefulIntents: ["想再点一份", "想问还能不能加单", "想点同样的", "想先这样"],
    responseOptionsJa: [
      "もう一品お願いします。",
      "まだ追加できますか。",
      "同じものをもう一つお願いします。",
      "とりあえず、これで大丈夫です。",
    ],
    softLanding: "追加点单后，可以自然继续吃喝、闲聊或慢慢收尾。",
    avoid: [
      "不要强行让用户继续点",
      "不要变成追加销售",
      "不要连续推荐太多菜",
      "不要检查用户是否完成步骤",
    ],
    fallbackUserLines: [
      "もう一品お願いします。",
      "まだ追加できますか。",
      "同じものをもう一つお願いします。",
      "とりあえず、これで大丈夫です。",
    ],
  },
  taisho_tired_day: {
    id: "taisho_tired_day",
    npcId: "taisho",
    title: "今天有点累",
    titleZh: "今天有点累",
    titleEn: "Say you had a tiring day",
    shortLabel: "有点累",
    shortLabelZh: "有点累",
    shortLabelEn: "Tiring day",
    microEpisodeZh: "一天结束后你来到店里，想随口说今天有点累。",
    microEpisodeEn: "You arrive after a long day and casually mention that you are tired.",
    starterIntentZh: "想轻轻说今天有点累。",
    starterIntentEn: "Casually say that today was tiring.",
    sampleUserLineJa: "今日はちょっと疲れました。",
    setup: "用户一天结束后坐在居酒屋，想轻轻说一句今天有点累。",
    userGoal: "自然地表达疲惫、吐槽一点今天的事，但不进入沉重咨询。",
    npcOpening: "今日はちょっと疲れてる顔してるな。",
    possibleBeats: ["表达今天有点累", "说今天不太顺", "想吃点热的", "轻轻转回吃喝或闲聊"],
    usefulIntents: ["想说今天有点累", "想说今天不太顺", "想说只想轻松待一会儿", "想吃点温热的东西"],
    responseOptionsJa: [
      "今日はちょっと疲れました。",
      "なんか、今日はうまくいかない日でした。",
      "少しだけゆっくりしたいです。",
      "温かいものが食べたいです。",
    ],
    softLanding: "轻轻接住用户的疲惫后，应自然回到吃喝、店里的气氛或普通闲聊。",
    avoid: [
      "不要变成心理咨询",
      "不要人生说教",
      "不要过度总结用户状态",
      "不要追问沉重私人问题",
      "不要把用户的疲惫放大成严重问题",
    ],
    fallbackUserLines: [
      "今日はちょっと疲れました。",
      "なんか、今日はうまくいかない日でした。",
      "少しだけゆっくりしたいです。",
      "温かいものが食べたいです。",
    ],
  },
  taisho_check_bill: {
    id: "taisho_check_bill",
    npcId: "taisho",
    title: "结账",
    titleZh: "结账",
    titleEn: "Ask for the bill",
    shortLabel: "结账",
    shortLabelZh: "结账",
    shortLabelEn: "Bill",
    microEpisodeZh: "你吃完准备离开，想请大将结账。",
    microEpisodeEn: "You have finished eating and want to ask Taisho for the bill.",
    starterIntentZh: "想请店里结账。",
    starterIntentEn: "Ask for the bill.",
    sampleUserLineJa: "お会計をお願いします。",
    setup: "用户吃完后想结账，但不知道怎么自然开口。",
    userGoal: "自然地表示想结账，并简单寒暄离店。",
    npcOpening: "そろそろ締める感じ？",
    possibleBeats: ["表示想结账", "确认金额", "简单道谢", "离店寒暄"],
    usefulIntents: ["想说要结账", "想问总共多少钱", "想道谢", "想说下次再来"],
    responseOptionsJa: [
      "そろそろお会計をお願いします。",
      "全部でいくらですか。",
      "ごちそうさまでした。",
      "また来ます。",
    ],
    softLanding: "结账后，可以自然结束本轮场景或回到普通闲聊。",
    avoid: [
      "不要变成结账流程考试",
      "不要长篇说明付款方式",
      "不要强行总结用户今天吃了什么",
      "不要让 Taisho 说教",
    ],
    fallbackUserLines: [
      "そろそろお会計をお願いします。",
      "全部でいくらですか。",
      "ごちそうさまでした。",
      "また来ます。",
    ],
  },
  haruka_first_lab_greeting: {
    id: "haruka_first_lab_greeting",
    npcId: "haruka",
    title: "第一次进研究室",
    titleZh: "第一次进研究室",
    titleEn: "First lab greeting",
    shortLabel: "第一次进研究室",
    shortLabelZh: "第一次进研究室",
    shortLabelEn: "Lab greeting",
    microEpisodeZh: "你第一次来到研究室，想先向在场的遥打个招呼。",
    microEpisodeEn: "You arrive at the lab for the first time and want to greet Haruka.",
    starterIntentZh: "想说明自己第一次来研究室。",
    starterIntentEn: "Say that this is your first time in the lab.",
    sampleUserLineJa: "今日、初めて研究室に来ました。",
    setup: "用户第一次进入研究室，不知道怎么自然打招呼。",
    userGoal: "自然地向前辈或研究室成员打招呼，并说明自己是第一次来。",
    npcOpening: "こんにちは。ここに来るのは初めてですか？今は少し静かなので、話しやすいかもしれません。",
    possibleBeats: ["说明第一次来", "向前辈打招呼", "询问坐哪里或在哪里等", "简单道谢"],
    usefulIntents: ["想说第一次来研究室", "想向前辈打招呼", "想问在哪里等", "想简单道谢"],
    responseOptionsJa: [
      "初めて研究室に来ました。",
      "よろしくお願いします。",
      "どこで待てばいいですか。",
      "ありがとうございます。",
    ],
    softLanding: "打过招呼后，可以自然转入研究室日常、ゼミ、文献或普通校园闲聊。",
    avoid: [
      "不要变成研究室礼仪课程",
      "不要过度正式",
      "不要像教授训话",
      "不要检查用户是否完成步骤",
    ],
    fallbackUserLines: [
      "初めて研究室に来ました。",
      "よろしくお願いします。",
      "どこで待てばいいですか。",
      "ありがとうございます。",
    ],
  },
  haruka_ask_senpai_help: {
    id: "haruka_ask_senpai_help",
    npcId: "haruka",
    title: "请前辈帮忙看一下",
    titleZh: "请前辈帮忙看一下",
    titleEn: "Ask a senpai for help",
    shortLabel: "请前辈帮忙",
    shortLabelZh: "请前辈帮忙",
    shortLabelEn: "Ask for help",
    microEpisodeZh: "你手上的资料有一处卡住了，想请遥帮忙看一下。",
    microEpisodeEn: "You are stuck on part of a document and want Haruka to take a quick look.",
    starterIntentZh: "想请前辈帮忙看一下资料。",
    starterIntentEn: "Ask your senpai to look at part of the document.",
    sampleUserLineJa: "この部分、少しだけ見てもらえますか。",
    setup: "用户想请前辈帮忙看一下资料、表达或准备内容，但不想显得太打扰。",
    userGoal: "自然地向前辈提出一个轻量请教请求。",
    npcOpening: "その資料ですか？少しなら一緒に見られますよ。",
    possibleBeats: ["说明想请教", "请求看一下", "说明不会占太多时间", "表达感谢"],
    usefulIntents: ["想请教一个问题", "想请对方看一下", "想说不会花太多时间", "想道谢"],
    responseOptionsJa: [
      "少しだけ相談してもいいですか。",
      "この部分を見てもらえますか。",
      "時間があるときで大丈夫です。",
      "ありがとうございます。助かります。",
    ],
    softLanding: "轻量请教后，可以自然转入具体问题、研究室闲聊或普通校园话题。",
    avoid: [
      "不要变成导师指导",
      "不要替用户写完整学术建议",
      "不要长篇规划",
      "不要让 Haruka 变成顾问",
    ],
    fallbackUserLines: [
      "少しだけ相談してもいいですか。",
      "この部分を見てもらえますか。",
      "時間があるときで大丈夫です。",
      "ありがとうございます。助かります。",
    ],
  },
  haruka_paper_question: {
    id: "haruka_paper_question",
    npcId: "haruka",
    title: "文献看不懂",
    titleZh: "文献看不懂",
    titleEn: "Ask about a paper",
    shortLabel: "文献看不懂",
    shortLabelZh: "文献看不懂",
    shortLabelEn: "Paper question",
    microEpisodeZh: "你读文献时卡在一段内容上，想问遥她怎么看。",
    microEpisodeEn: "You are stuck on part of a paper and want to ask Haruka about it.",
    starterIntentZh: "想说明有一部分还没看懂。",
    starterIntentEn: "Say that there is a section you still do not understand.",
    sampleUserLineJa: "この文献のここが、まだよく分かっていません。",
    setup: "用户读文献时卡住了，想自然地向前辈表达自己哪里不太懂。",
    userGoal: "表达文献有点难、想问从哪里读或怎么理解某部分。",
    npcOpening: "その文献、少し難しそうですね。今どのあたりを見ていますか？",
    possibleBeats: ["说明文献有点难", "询问从哪里开始读", "说明某部分不懂", "请求前辈简单提示"],
    usefulIntents: ["想说文献有点难", "想问从哪里开始读", "想说某部分不懂", "想请前辈简单提示"],
    responseOptionsJa: [
      "この論文、少し難しいです。",
      "どこから読めばいいですか。",
      "この部分がまだよくわかりません。",
      "簡単に教えてもらえますか。",
    ],
    softLanding: "问完文献后，可以自然聊到读文献的方法、ゼミ准备或普通校园话题。",
    avoid: [
      "不要变成论文讲解机器人",
      "不要替用户系统讲完整文献",
      "不要长篇学术指导",
      "不要让 Haruka 变成教授",
    ],
    fallbackUserLines: [
      "この論文、少し難しいです。",
      "どこから読めばいいですか。",
      "この部分がまだよくわかりません。",
      "簡単に教えてもらえますか。",
    ],
  },
  haruka_seminar_comment: {
    id: "haruka_seminar_comment",
    npcId: "haruka",
    title: "ゼミ里简单发言",
    titleZh: "ゼミ里简单发言",
    titleEn: "Speak in seminar",
    shortLabel: "ゼミ发言",
    shortLabelZh: "ゼミ发言",
    shortLabelEn: "Seminar comment",
    microEpisodeZh: "ゼミ讨论到一个你在意的点，你想补充一句或问一个问题。",
    microEpisodeEn: "A point in the seminar discussion catches your attention, and you want to add a brief comment or question.",
    starterIntentZh: "想在ゼミ里问一个问题。",
    starterIntentEn: "Ask one question during the seminar.",
    sampleUserLineJa: "一つ質問してもいいですか。",
    setup: "用户想在ゼミ里说一句简单想法，但不知道怎么自然开口。",
    userGoal: "练习用轻丁寧的方式表达一个简单看法、疑问或补充。",
    npcOpening: "さっきの話、少し気になるところがありましたか？",
    possibleBeats: ["表达一个简单看法", "提出一个问题", "补充一点", "承认自己还不确定"],
    usefulIntents: ["想说我觉得有意思", "想提出一个问题", "想补充一点", "想说自己还不确定"],
    responseOptionsJa: [
      "この点が面白いと思いました。",
      "一つ質問してもいいですか。",
      "少しだけ補足してもいいですか。",
      "まだ整理できていないのですが、気になりました。",
    ],
    softLanding: "说出一句后，可以自然转入发表、文献、课堂理解或普通校园闲聊。",
    avoid: [
      "不要变成发表训练课",
      "不要要求用户讲完整观点",
      "不要纠正用户发言结构",
      "不要让 Haruka 变成老师",
    ],
    fallbackUserLines: [
      "この点が面白いと思いました。",
      "一つ質問してもいいですか。",
      "少しだけ補足してもいいですか。",
      "まだ整理できていないのですが、気になりました。",
    ],
  },
  haruka_presentation_nerves: {
    id: "haruka_presentation_nerves",
    npcId: "haruka",
    title: "发表前有点紧张",
    titleZh: "发表前有点紧张",
    titleEn: "Before a presentation",
    shortLabel: "发表前紧张",
    shortLabelZh: "发表前紧张",
    shortLabelEn: "Presentation nerves",
    microEpisodeZh: "发表快开始了，你有点紧张，想和遥轻轻说一下。",
    microEpisodeEn: "Your presentation is about to start, and you want to briefly tell Haruka that you are nervous.",
    starterIntentZh: "想说发表前有点紧张。",
    starterIntentEn: "Say that you are a little nervous before the presentation.",
    sampleUserLineJa: "発表が近くて、少し緊張しています。",
    setup: "用户发表前有点紧张，想向前辈轻轻说一下。",
    userGoal: "自然表达紧张、说明自己还没准备好，或请求一点轻量建议。",
    npcOpening: "もうすぐ発表ですね。少し緊張していますか？",
    possibleBeats: ["表达有点紧张", "说明还没完全准备好", "请求轻量建议", "确认开场一句"],
    usefulIntents: ["想说有点紧张", "想说还没准备好", "想请前辈给一点建议", "想练开场一句"],
    responseOptionsJa: [
      "発表が近くて、少し緊張しています。",
      "まだ準備が完全ではありません。",
      "最初に何と言えば自然ですか。",
      "少しだけアドバイスをもらえますか。",
    ],
    softLanding: "轻轻接住紧张后，可以自然回到开场表达、ゼミ氛围或普通校园话题。",
    avoid: [
      "不要变成心理咨询",
      "不要长篇演讲指导",
      "不要给压力",
      "不要把紧张放大成严重问题",
    ],
    fallbackUserLines: [
      "発表が近くて、少し緊張しています。",
      "まだ準備が完全ではありません。",
      "最初に何と言えば自然ですか。",
      "少しだけアドバイスをもらえますか。",
    ],
  },
  haruka_after_class_check: {
    id: "haruka_after_class_check",
    npcId: "haruka",
    title: "课后确认没听懂",
    titleZh: "课后确认没听懂",
    titleEn: "Ask after class",
    shortLabel: "课后确认",
    shortLabelZh: "课后确认",
    shortLabelEn: "After class",
    microEpisodeZh: "下课后你还有一处没听懂，想请遥再说明一下。",
    microEpisodeEn: "After class, there is one part you did not understand, and you want Haruka to explain it again.",
    starterIntentZh: "想请前辈再说明一次。",
    starterIntentEn: "Ask your senpai to explain it again.",
    sampleUserLineJa: "もう一度説明してもらえますか。",
    setup: "用户上课或说明中有一部分没听懂，想在课后自然确认。",
    userGoal: "自然地表示自己没完全听懂，并请求对方再说明一下。",
    npcOpening: "授業のあとに少し確認するのは、全然変じゃないですよ。",
    possibleBeats: ["说明没完全听懂", "请求再说一遍", "确认自己理解是否正确", "表达感谢"],
    usefulIntents: ["想说没完全听懂", "想请对方再说明", "想确认理解是否正确", "想道谢"],
    responseOptionsJa: [
      "すみません、少し確認してもいいですか。",
      "さっきの説明が少し難しかったです。",
      "もう一度説明してもらえますか。",
      "こういう理解で合っていますか。",
    ],
    softLanding: "确认后，可以自然转入课堂、研究室、文献或普通校园闲聊。",
    avoid: [
      "不要变成听力测试",
      "不要纠错用户",
      "不要长篇教学",
      "不要让 Haruka 变成授课老师",
    ],
    fallbackUserLines: [
      "すみません、少し確認してもいいですか。",
      "さっきの説明が少し難しかったです。",
      "もう一度説明してもらえますか。",
      "こういう理解で合っていますか。",
    ],
  },
  aoi_ask_interests: {
    id: "aoi_ask_interests",
    npcId: "aoi",
    title: "问最近喜欢什么",
    titleZh: "问最近喜欢什么",
    titleEn: "Ask what they’re into",
    shortLabel: "问最近喜欢什么",
    shortLabelZh: "问最近喜欢什么",
    shortLabelEn: "Current interests",
    microEpisodeZh: "你和葵在共享空间碰到，想随口问她最近喜欢什么。",
    microEpisodeEn: "You run into Aoi in the shared space and casually ask what she is into lately.",
    starterIntentZh: "想问朋友最近喜欢什么。",
    starterIntentEn: "Ask what your friend is into lately.",
    sampleUserLineJa: "最近、何にハマってる？",
    setup: "用户想和同级朋友自然开启一个兴趣话题。",
    userGoal: "自然地问对方最近喜欢什么、有没有推荐，或表达自己有点感兴趣。",
    npcOpening: "最近、何かハマってるものある？",
    possibleBeats: ["问最近喜欢什么", "问有没有推荐", "表达有点感兴趣", "追问从哪里开始"],
    usefulIntents: ["想问最近在喜欢什么", "想问有没有推荐", "想说有点感兴趣", "想问从哪里开始"],
    responseOptionsJa: [
      "最近、何にハマってる？",
      "おすすめある？",
      "それ、ちょっと気になる。",
      "どこから見ればいい？",
    ],
    softLanding: "开启兴趣话题后，可以自然继续聊推荐、作品、活动或普通闲聊。",
    avoid: [
      "不要变成采访",
      "不要连续追问太多",
      "不要恋爱化",
      "不要无证据说用户以前喜欢过某物",
    ],
    fallbackUserLines: [
      "最近、何にハマってる？",
      "おすすめある？",
      "それ、ちょっと気になる。",
      "どこから見ればいい？",
    ],
  },
  aoi_react_recommendation: {
    id: "aoi_react_recommendation",
    npcId: "aoi",
    title: "接住朋友推荐",
    titleZh: "接住朋友推荐",
    titleEn: "React to a recommendation",
    shortLabel: "接住朋友推荐",
    shortLabelZh: "接住朋友推荐",
    shortLabelEn: "Recommendation",
    microEpisodeZh: "葵提到最近喜欢的东西，你觉得有点意思，想继续问问。",
    microEpisodeEn: "Aoi mentions something she likes lately, and you want to ask more about it.",
    starterIntentZh: "想表达有点兴趣并继续追问。",
    starterIntentEn: "Show interest and ask a little more.",
    sampleUserLineJa: "それ、ちょっと面白そう。どんな感じ？",
    setup: "Aoi 提到一个自己最近喜欢的东西，用户想自然接住推荐。",
    userGoal: "对朋友推荐作出自然回应，表达兴趣、追问内容或询问入门方式。",
    npcOpening: "これ、最近ちょっとハマってるんだよね。",
    possibleBeats: ["询问是什么感觉", "表达有点感兴趣", "问新手能不能看懂", "问从哪里开始"],
    usefulIntents: ["想问这是什么感觉", "想说听起来有点有趣", "想问新手能不能入门", "想问从哪里开始"],
    responseOptionsJa: [
      "それ、どんな感じ？",
      "ちょっと面白そう。",
      "初心者でも楽しめる？",
      "どこから始めればいい？",
    ],
    softLanding: "接住推荐后，可以自然继续聊兴趣、作品、体验或普通闲聊。",
    avoid: [
      "不要变成产品推荐机器人",
      "不要让 Aoi 过度兴奋到二次元化",
      "不要让用户像在完成推荐任务",
      "不要编造用户过去提过这个兴趣",
    ],
    fallbackUserLines: [
      "それ、どんな感じ？",
      "ちょっと面白そう。",
      "初心者でも楽しめる？",
      "どこから始めればいい？",
    ],
  },
  aoi_join_unfamiliar_topic: {
    id: "aoi_join_unfamiliar_topic",
    npcId: "aoi",
    title: "加入不熟的话题",
    titleZh: "加入不熟的话题",
    titleEn: "Join an unfamiliar topic",
    shortLabel: "加入不熟的话题",
    shortLabelZh: "加入不熟的话题",
    shortLabelEn: "Unfamiliar topic",
    microEpisodeZh: "朋友提到一个你不太熟的话题，但你有点感兴趣，想自然接住。",
    microEpisodeEn: "Your friend brings up something you do not know well, but you are a little interested and want to respond naturally.",
    starterIntentZh: "想表达自己不太懂，但有点感兴趣。",
    starterIntentEn: "Say that you do not know much about it, but you are interested.",
    sampleUserLineJa: "それ、あんまり詳しくないけど、ちょっと気になる。",
    setup: "朋友聊到一个用户不太熟悉的话题，但用户想自然加入，而不是沉默。",
    userGoal: "表达自己不太懂，但愿意听；请对方用简单方式说明。",
    npcOpening: "ちょっとマイナーかもだけど、この話してもいい？",
    possibleBeats: ["承认自己不太熟", "表达愿意听", "请对方简单说明", "自然追问"],
    usefulIntents: ["想说自己不太懂", "想说愿意听", "想请对方简单讲讲", "想自然追问"],
    responseOptionsJa: [
      "詳しくないけど、聞いてみたい。",
      "あまり知らないけど、面白そう。",
      "それって、どういう感じ？",
      "初心者向けに言うと、どんな話？",
    ],
    softLanding: "加入不熟的话题后，可以自然继续听朋友介绍，或转到相关轻话题。",
    avoid: [
      "不要让用户显得尴尬或失败",
      "不要变成知识讲解课",
      "不要让 Aoi 长篇科普",
      "不要让对话变成学习任务",
    ],
    fallbackUserLines: [
      "詳しくないけど、聞いてみたい。",
      "あまり知らないけど、面白そう。",
      "それって、どういう感じ？",
      "初心者向けに言うと、どんな話？",
    ],
  },
  aoi_chill_talk: {
    id: "aoi_chill_talk",
    npcId: "aoi",
    title: "说想放空一下",
    titleZh: "说想放空一下",
    titleEn: "Say you want to chill",
    shortLabel: "说想放空一下",
    shortLabelZh: "说想放空一下",
    shortLabelEn: "Chill talk",
    microEpisodeZh: "今天有点累，你想在学生ラウンジ和葵随便聊几句。",
    microEpisodeEn: "You are a little tired today and want to chat casually with Aoi in the student lounge.",
    starterIntentZh: "想说今天只想轻松聊聊。",
    starterIntentEn: "Say that you only want a relaxed chat today.",
    sampleUserLineJa: "今日はちょっとだらっと話したい。",
    setup: "用户今天有点累，想在学生ラウンジ里和朋友随便聊几句，不进入沉重话题。",
    userGoal: "自然地说今天想放空、想轻松聊，不把气氛变沉重。",
    npcOpening: "今日はラウンジでちょっとだらっとしたい気分かも。",
    possibleBeats: [
      "说今天想放空",
      "说想轻松聊",
      "说有点累但不是重话题",
      "自然转到轻松话题",
    ],
    usefulIntents: ["想说今天想放空", "想说想随便聊", "想说有点累但不沉重", "想轻松待一会儿"],
    responseOptionsJa: [
      "今日はちょっとだらっとしたい。",
      "何も考えずに話したい気分。",
      "ちょっと疲れたけど、重い話じゃないよ。",
      "ゆるく話してもいい？",
    ],
    softLanding: "轻轻表达状态后，应自然转向兴趣、推荐、放课后安排或普通闲聊。",
    avoid: [
      "不要变成心理咨询",
      "不要追问沉重私人问题",
      "不要过度安慰",
      "不要把 Aoi 写成情绪依赖型陪伴角色",
    ],
    fallbackUserLines: [
      "今日はちょっとだらっとしたい。",
      "何も考えずに話したい気分。",
      "ちょっと疲れたけど、重い話じゃないよ。",
      "ゆるく話してもいい？",
    ],
  },
  aoi_after_class_plan: {
    id: "aoi_after_class_plan",
    npcId: "aoi",
    title: "问下课后安排",
    titleZh: "问下课后安排",
    titleEn: "Ask about after class",
    shortLabel: "问下课后安排",
    shortLabelZh: "问下课后安排",
    shortLabelEn: "After class",
    microEpisodeZh: "下课了，你想随口问葵接下来准备做什么。",
    microEpisodeEn: "Class is over, and you casually ask Aoi what she is doing next.",
    starterIntentZh: "想问朋友下课后的安排。",
    starterIntentEn: "Ask what your friend is doing after class.",
    sampleUserLineJa: "このあと、何する？",
    setup: "用户想自然问同级朋友下课后做什么，或轻轻邀请对方在ラウンジ聊一会儿。",
    userGoal: "自然地问对方接下来做什么，或提出轻量、不带压力的邀约。",
    npcOpening: "このあと、どうする？ラウンジで少し話す？",
    possibleBeats: ["问接下来做什么", "邀请在ラウンジ聊一会儿", "问要不要顺路去哪里", "给对方留余地"],
    usefulIntents: ["想问下课后安排", "想邀请聊一会儿", "想问要不要去哪里", "想自然确认对方是否有空"],
    responseOptionsJa: [
      "このあと、何する？",
      "少しラウンジで話さない？",
      "どこか寄っていく？",
      "今日はまっすぐ帰る？",
    ],
    softLanding: "问完安排后，可以自然转入兴趣、推荐、放课后活动或普通闲聊。",
    avoid: [
      "不要恋爱化",
      "不要约会感",
      "不要让 Aoi 显得过黏",
      "不要让邀约变成任务",
    ],
    fallbackUserLines: [
      "このあと、何する？",
      "少しラウンジで話さない？",
      "どこか寄っていく？",
      "今日はまっすぐ帰る？",
    ],
  },
  aoi_soft_decline: {
    id: "aoi_soft_decline",
    npcId: "aoi",
    title: "委婉说下次吧",
    titleZh: "委婉说下次吧",
    titleEn: "Say maybe next time",
    shortLabel: "委婉说下次吧",
    shortLabelZh: "委婉说下次吧",
    shortLabelEn: "Maybe next time",
    microEpisodeZh: "葵邀请你下课后一起去哪里，但你今天有点累，想改天再约。",
    microEpisodeEn: "Aoi invites you to go somewhere after class, but you are tired and want to go another time.",
    starterIntentZh: "想轻松地说今天不去，下次再约。",
    starterIntentEn: "Casually decline for today and suggest another time.",
    sampleUserLineJa: "今日はちょっと疲れてるから、また今度でもいい？",
    setup: "Aoi 轻轻邀请用户下课后去哪里，用户想自然拒绝但不伤关系。",
    userGoal: "用朋友之间的 casual 语气委婉拒绝、说下次再约，或说明今天有点累。",
    npcOpening: "このあと、少しどこか寄っていく？",
    possibleBeats: ["说明今天有点累", "说下次再约", "表示抱歉但保持轻松", "说只聊一会儿也可以"],
    usefulIntents: ["想说今天有点累", "想说下次再约", "想自然拒绝", "想说只聊一会儿也可以"],
    responseOptionsJa: [
      "今日はちょっと疲れてるから、また今度でもいい？",
      "ごめん、今日はまっすぐ帰るね。",
      "また今度誘って。",
      "少しだけなら大丈夫。",
    ],
    softLanding: "委婉拒绝后，应保持朋友关系自然，不制造尴尬，也不让 Aoi 失落或黏人。",
    avoid: [
      "不要让 Aoi 失落或撒娇",
      "不要恋爱化",
      "不要让用户有拒绝压力",
      "不要把拒绝变成关系危机",
    ],
    fallbackUserLines: [
      "今日はちょっと疲れてるから、また今度でもいい？",
      "ごめん、今日はまっすぐ帰るね。",
      "また今度誘って。",
      "少しだけなら大丈夫。",
    ],
  },
  nana_rental_initial_costs: {
    id: "nana_rental_initial_costs",
    npcId: "nana",
    title: "确认租房初期费用",
    shortLabel: "租房初期费用",
    titleEn: "Asking about rental initial costs",
    shortLabelEn: "Rental costs",
    microEpisodeZh: "你刚看到一间房，月租还可以，但不确定礼金、押金、中介费加起来会不会很高。你想先问清楚初期费用。",
    microEpisodeEn: "You found an apartment with reasonable monthly rent, but you are not sure how much the key money, deposit, and agency fee will add up to. You want to ask about the initial costs first.",
    starterIntentZh: "想问初期费用包括哪些项目。",
    starterIntentEn: "Ask what is included in the initial costs.",
    sampleUserLineJa: "初期費用には、どんなものがありますか。",
    setup: "用户正在向 Nana 确认租房初期费用，包括敷金、礼金和仲介手数料。",
    userGoal: "确认初期费用包含哪些项目和大概金额，同时知道具体金额需要向房源窗口确认。",
    npcOpening: "初期費用は項目が多くて分かりにくいですよね。どの費用が気になっていますか？",
    possibleBeats: [
      "问敷金是什么意思",
      "问礼金是什么",
      "问仲介手数料是多少",
      "问总共要付多少",
    ],
    usefulIntents: [
      "问费用意思",
      "问当前房源是否需要礼金",
      "问总金额",
      "问外国籍是否可以申请",
    ],
    responseOptionsJa: [
      "敷金って、何のためのお金ですか。",
      "この物件では礼金は必要ですか。",
      "全部でいくらくらいかかりますか。",
      "外国籍でも申し込めますか。",
    ],
    softLanding: "问完一两个费用后，可以轻轻提醒：具体金额要以实际房源和窗口说明为准。",
    avoid: [
      "不要给租房法律结论",
      "不要保证真实费用金额",
      "不要假装知道具体房源规则",
      "不要长篇解释日本租房制度",
    ],
    fallbackUserLines: [
      "敷金って、何のためのお金ですか。",
      "この物件では礼金は必要ですか。",
      "全部でいくらくらいかかりますか。",
      "外国籍でも申し込めますか。",
    ],
  },
  nana_apartment_viewing_questions: {
    id: "nana_apartment_viewing_questions",
    npcId: "nana",
    title: "看房时确认条件",
    shortLabel: "看房问条件",
    titleEn: "Asking about apartment conditions",
    shortLabelEn: "Viewing questions",
    microEpisodeZh: "你去看一间房，想先确认走到车站要多久，再看看其他生活条件。",
    microEpisodeEn: "You are viewing an apartment and want to check how long the walk to the station takes before asking about other details.",
    starterIntentZh: "想自然确认从房子走到车站的时间。",
    starterIntentEn: "Ask how long it takes to walk to the station.",
    sampleUserLineJa: "駅からどのくらい歩きますか。",
    setup: "用户准备去看房，正在向 Nana 整理需要确认的车站距离、采光、噪音、家具和网络等条件。",
    userGoal: "确认自己最在意的看房条件，并知道具体情况需要在现场或向中介确认。",
    npcOpening: "内見のときは、駅からの距離や周りの音、ネット環境なども気になりますよね。どの条件から確認したいですか？",
    possibleBeats: [
      "问车站距离",
      "问采光和噪音",
      "问家具和设备",
      "问网络情况",
    ],
    usefulIntents: [
      "问距离和时间",
      "问环境条件",
      "问设备清单",
      "问网络情况",
    ],
    responseOptionsJa: [
      "駅からはどのくらいですか。",
      "日当たりや騒音について確認したいです。",
      "家具付きですか。",
      "インターネットは使えますか。",
    ],
    softLanding: "整理几项后，可以轻轻提醒：看房时不用一次确认完所有事情，先看最在意的点就可以。",
    avoid: [
      "不要保证某个房源的条件",
      "不要判断房源好坏",
      "不要变成房产中介",
      "不要替用户做租房决定",
    ],
    fallbackUserLines: [
      "駅からはどのくらいですか。",
      "日当たりや騒音について確認したいです。",
      "家具付きですか。",
      "インターネットは使えますか。",
    ],
  },
  nana_city_office_procedure: {
    id: "nana_city_office_procedure",
    npcId: "nana",
    title: "刚搬来后的役所手续",
    shortLabel: "役所手续",
    titleEn: "City office procedures after moving",
    shortLabelEn: "City office",
    microEpisodeZh: "你刚搬到新的城市，不太确定接下来要去役所办理哪些手续。",
    microEpisodeEn: "You have just moved to a new city and are not sure which procedures you need to handle at the city office.",
    starterIntentZh: "想先问搬家后需要办理什么手续。",
    starterIntentEn: "Ask which procedures are needed after moving.",
    sampleUserLineJa: "引っ越してきたあと、どんな手続きが必要ですか。",
    setup: "用户刚搬来，正在向 Nana 确认住民登録和其他役所手续。",
    userGoal: "整理需要确认的手续、窗口和材料，同时知道具体要求要以役所通知为准。",
    npcOpening: "引っ越してきたばかりだと、役所で何を確認すればいいか迷いますよね。まず気になっている手続きはありますか？",
    possibleBeats: [
      "说刚搬来",
      "说要办手续",
      "问需要什么材料",
      "问窗口在哪里",
    ],
    usefulIntents: [
      "表达刚搬来",
      "说办什么手续",
      "问所需材料",
      "请求说慢一点",
    ],
    responseOptionsJa: [
      "最近こちらに引っ越してきたので、住民登録をしたいです。",
      "必要な書類を確認したいんですけど。",
      "どの窓口に行けばいいですか。",
      "もう少しゆっくり説明してもらえますか。",
    ],
    softLanding: "整理完后，可以轻轻提醒：具体要带什么材料，要以窗口或官方通知为准。",
    avoid: [
      "不要给具体行政政策结论",
      "不要列出完整手续清单",
      "不要保证某个手续的结果",
      "不要把 Nana 写成行政专家",
    ],
    fallbackUserLines: [
      "最近こちらに引っ越してきたので、住民登録をしたいです。",
      "必要な書類を確認したいんですけど。",
      "どの窓口に行けばいいですか。",
      "もう少しゆっくり説明してもらえますか。",
    ],
  },
  nana_ask_repeat_slowly: {
    id: "nana_ask_repeat_slowly",
    npcId: "nana",
    title: "听不懂时请再说一遍",
    shortLabel: "请再说一遍",
    titleEn: "Asking someone to repeat or slow down",
    shortLabelEn: "Repeat slowly",
    microEpisodeZh: "七海刚才说得有点快，你没听清，想礼貌地请她慢一点再说一次。",
    microEpisodeEn: "Nana spoke a little quickly, and you want to politely ask her to repeat it more slowly.",
    starterIntentZh: "想礼貌地请她慢一点再说一次。",
    starterIntentEn: "Politely ask her to repeat it more slowly.",
    sampleUserLineJa: "すみません、もう一度ゆっくり言っていただけますか。",
    setup: "Nana 正在说明窗口的基本流程，但刚才说得有点快，用户没有听清。",
    userGoal: "让对方重复或放慢语速，并确认自己听到的内容。",
    npcOpening: "受付が終わったら、この番号を持って待合スペースでお待ちください。あ、君の表情がちょっと困ってるみたいね、何かあったの？",
    possibleBeats: [
      "请再说一遍",
      "请说慢一点",
      "确认自己理解是否正确",
      "表达日语还在学习中",
    ],
    usefulIntents: [
      "请求再说一遍",
      "请求放慢",
      "确认理解",
      "表达日语不熟",
    ],
    responseOptionsJa: [
      "すみません、もう一度お願いします。",
      "もう少しゆっくり言ってもらえますか。",
      "今の内容を確認してもいいですか。",
      "まだ日本語を勉強中なので、もう少しゆっくり話してもらえますか。",
    ],
    softLanding: "Nana 放慢速度重新说明，并让用户不用因为请求重复而感到不好意思。",
    avoid: [
      "不要长篇解释为什么听不懂",
      "不要自我否定过多",
      "不要变成日语学习课",
      "不要让用户感觉麻烦别人",
    ],
    fallbackUserLines: [
      "すみません、もう一度お願いします。",
      "もう少しゆっくり言ってもらえますか。",
      "今の内容を確認してもいいですか。",
      "まだ日本語を勉強中なので、もう少しゆっくり話してもらえますか。",
    ],
  },
  nana_phone_internet_contract: {
    id: "nana_phone_internet_contract",
    npcId: "nana",
    title: "开通手机 / 网络",
    shortLabel: "手机和网络",
    titleEn: "Setting up phone or internet",
    shortLabelEn: "Phone / internet",
    microEpisodeZh: "你刚搬进新家，想在家里用网络，但不清楚应该先申请什么。",
    microEpisodeEn: "You have just moved into a new home and want internet access, but you are not sure what you need to apply for.",
    starterIntentZh: "想问在家使用网络需要申请什么。",
    starterIntentEn: "Ask what you need to apply for to use internet at home.",
    sampleUserLineJa: "家でインターネットを使うには、何を申し込めばいいですか。",
    setup: "用户刚到日本，正在向 Nana 整理手机卡、网络契约、月费和所需证件等问题。",
    userGoal: "确认契约条件、月额费用和所需证件，同时知道具体条件要向店铺或运营方确认。",
    npcOpening: "スマホやネットの契約は、プランや期間が分かりにくいことがありますよね。何を確認したいですか？",
    possibleBeats: [
      "问月费是多少",
      "问需要什么证件",
      "问外国籍是否可以申请",
      "问契约期间和解约费用",
    ],
    usefulIntents: [
      "问每月费用",
      "问所需证件",
      "问外国籍是否可以申请",
      "问契约条件",
    ],
    responseOptionsJa: [
      "月額料金はいくらですか。",
      "契約には何が必要ですか。",
      "外国籍でも契約できますか。",
      "契約期間や解約料について確認したいです。",
    ],
    softLanding: "确认基本问题后，可以提醒用户：具体条件要以店头或契约说明为准。",
    avoid: [
      "不要推荐具体运营商",
      "不要保证契约能通过",
      "不要给金融或信用判断",
      "不要长篇解释日本通信套餐",
    ],
    fallbackUserLines: [
      "月額料金はいくらですか。",
      "契約には何が必要ですか。",
      "外国籍でも契約できますか。",
      "契約期間や解約料について確認したいです。",
    ],
  },
  nana_garbage_rules: {
    id: "nana_garbage_rules",
    npcId: "nana",
    title: "问垃圾分类规则",
    shortLabel: "垃圾分类",
    titleEn: "Ask about garbage rules",
    shortLabelEn: "Garbage rules",
    microEpisodeZh: "你准备扔一袋垃圾，但不确定它应该在哪一天拿出去。",
    microEpisodeEn: "You are ready to take out a bag of garbage, but you are not sure which day it should go out.",
    starterIntentZh: "想确认这类垃圾应该星期几投放。",
    starterIntentEn: "Ask which day this type of garbage should be put out.",
    sampleUserLineJa: "このごみは、何曜日に出せばいいですか。",
    setup: "用户刚开始独立生活，正在向 Nana 询问垃圾分类、投放日期和投放地点。",
    userGoal: "确认垃圾分类、投放日期或投放地点，同时知道具体规则需要向当地确认。",
    npcOpening: "ゴミ出しって、地域によってルールが違うので迷いますよね。どんなごみについて聞きたいですか？",
    possibleBeats: [
      "问垃圾怎么分类",
      "问哪天可以扔",
      "问在哪里扔",
      "问某个物品属于哪类垃圾",
    ],
    usefulIntents: [
      "问分类方法",
      "问投放日期",
      "问投放地点",
      "问具体物品怎么扔",
    ],
    responseOptionsJa: [
      "ゴミの分別について聞きたいです。",
      "燃えるゴミは何曜日に出せますか。",
      "ゴミはどこに出せばいいですか。",
      "これは何ゴミになりますか。",
    ],
    softLanding: "自然回应用户的问题，并轻轻提醒具体规则要以所在地区或公寓说明为准。",
    avoid: [
      "不要断言具体地区规则",
      "不要列完整垃圾分类百科",
      "不要让用户觉得规则很可怕",
      "不要编造真实地名或地区规则",
    ],
    fallbackUserLines: [
      "ゴミの分別について聞きたいです。",
      "燃えるゴミは何曜日に出せますか。",
      "ゴミはどこに出せばいいですか。",
      "これは何ゴミになりますか。",
    ],
  },
  nana_pharmacy_symptoms: {
    id: "nana_pharmacy_symptoms",
    npcId: "nana",
    title: "药局说明症状",
    shortLabel: "药局说明症状",
    titleEn: "Explain symptoms at a pharmacy",
    shortLabelEn: "Pharmacy",
    microEpisodeZh: "你的喉咙有点痛，但没有发烧，想在药局先简单说明现在的情况。",
    microEpisodeEn: "Your throat hurts a little, but you do not have a fever. You want to briefly explain how you feel at a pharmacy.",
    starterIntentZh: "想简单说明喉咙痛，但没有发烧。",
    starterIntentEn: "Say that your throat hurts a little, but you do not have a fever.",
    sampleUserLineJa: "少しのどが痛くて、熱はありません。",
    setup: "用户身体有点不舒服，正在向 Nana 整理去药局时需要说明的症状和想确认的问题。",
    userGoal: "说明当前症状和持续时间，并知道具体用药或就医判断要向专业人员确认。",
    npcOpening: "薬局では、症状といつから続いているかを伝えると聞いてもらいやすいですよ。今、どんな感じですか？",
    possibleBeats: [
      "说明头痛",
      "说明发烧",
      "说明喉咙痛",
      "询问是否需要去医院",
    ],
    usefulIntents: [
      "说明症状",
      "询问有没有适合的药",
      "询问是否需要去医院",
      "请求慢一点说明",
    ],
    responseOptionsJa: [
      "頭が痛いです。",
      "少し熱があります。",
      "のどが痛いです。",
      "病院に行ったほうがいいですか。",
    ],
    softLanding: "自然接住用户的症状信息，并提醒：症状が重いときや不安なときは、医療機関で確認してください。",
    avoid: [
      "不要做医疗诊断",
      "不要推荐具体药物",
      "不要判断病情严重程度",
      "不要替用户决定是否就医",
    ],
    fallbackUserLines: [
      "頭が痛いです。",
      "少し熱があります。",
      "のどが痛いです。",
      "病院に行ったほうがいいですか。",
    ],
  },
  nana_bank_post_office: {
    id: "nana_bank_post_office",
    npcId: "nana",
    title: "银行 / 邮局窗口咨询",
    shortLabel: "银行和邮局",
    titleEn: "Ask at a bank or post office",
    shortLabelEn: "Bank / post office",
    microEpisodeZh: "你想去窗口开一个账户，但不确定需要带哪些证件或材料。",
    microEpisodeEn: "You want to open an account at the counter, but you are not sure which documents or materials you need.",
    starterIntentZh: "想问开户需要准备什么。",
    starterIntentEn: "Ask what is needed to open an account.",
    sampleUserLineJa: "口座を作るには、何が必要ですか。",
    setup: "用户正在向 Nana 整理去银行或邮局窗口时想办理的事项和需要确认的材料。",
    userGoal: "确认办理事项、所需材料和提交窗口，同时知道具体条件要以窗口说明为准。",
    npcOpening: "銀行や郵便局の窓口は、必要な書類が分かりにくいことがありますよね。今日は何を確認したいですか？",
    possibleBeats: [
      "说明想开户",
      "问需要什么证件",
      "说明想寄东西",
      "问怎么填写表格",
    ],
    usefulIntents: [
      "想开户",
      "问所需证件",
      "想寄东西",
      "问填写方式",
    ],
    responseOptionsJa: [
      "口座を作るには、何が必要ですか。",
      "本人確認書類は、これで大丈夫ですか。",
      "荷物を送るには、どの窓口に行けばいいですか。",
      "この書類は、どこに出せばいいですか。",
    ],
    softLanding: "整理后可以提醒用户：具体材料和条件要以窗口说明为准。",
    avoid: [
      "不要给金融建议",
      "不要保证开户或手续成功",
      "不要解释复杂金融制度",
      "不要替用户判断具体业务能不能办理",
    ],
    fallbackUserLines: [
      "口座を作るには、何が必要ですか。",
      "本人確認書類は、これで大丈夫ですか。",
      "荷物を送るには、どの窓口に行けばいいですか。",
      "この書類は、どこに出せばいいですか。",
    ],
  },
  ren_back_to_kotomachi: {
    id: "ren_back_to_kotomachi",
    npcId: "ren",
    title: "刚回到言街",
    titleZh: "刚回到言街",
    titleEn: "Back in Kotomachi",
    shortLabel: "駅前",
    shortLabelZh: "駅前",
    shortLabelEn: "Back again",
    microEpisodeZh: "Ren 刚从别的城市回来，你可以问他去了哪里。",
    microEpisodeEn: "Ren has just come back from another city. You can ask where he went.",
    starterIntentZh: "询问他刚去了哪里。",
    starterIntentEn: "Ask where he has just been.",
    sampleUserLineJa: "どこに行っていたんですか？",
    setup: "Ren has just returned from a short trip and runs into the user near Kotomachi Station.",
    userGoal: "Ask where Ren has just been and keep the conversation on the feeling of returning, not on travel tips.",
    npcOpening: "ただいま、というほど長く出ていたわけじゃないんですけどね。言街に戻ってくると、少し落ち着きます。",
    possibleBeats: [
      "Ask where Ren went and why he chose that place.",
      "Compare how the other city felt with Kotomachi.",
      "Let Ren mention one small impression without taking over the conversation.",
      "Return to the quiet feeling of coming back to Kotomachi.",
    ],
    usefulIntents: [
      "ask where Ren went",
      "ask what that city felt like",
      "say that returning to a familiar place feels calming",
      "compare one city with another",
    ],
    softLanding: "そういう戻ってくる感じって、少し安心しますよね。また今度、行ってみたい街の話もしたいです。",
    avoid: [
      "Do not let Ren tell a long travel story.",
      "Do not generate travel plans or route advice.",
      "Do not turn the scene into recommendations or rankings.",
    ],
    fallbackUserLines: [
      "どこに行っていたんですか？",
      "その街はどんな感じでしたか？",
      "言街に戻ると落ち着きますか？",
    ],
    responseOptionsJa: [
      "どこに行っていたんですか？",
      "その街はどんな感じでしたか？",
      "言街に戻ると落ち着きますか？",
    ],
  },
  ren_place_to_visit: {
    id: "ren_place_to_visit",
    npcId: "ren",
    title: "最近想去的地方",
    titleZh: "最近想去的地方",
    titleEn: "A place you want to visit",
    shortLabel: "行きたい場所",
    shortLabelZh: "行きたい場所",
    shortLabelEn: "Want to go",
    microEpisodeZh: "Ren 问你最近想去哪里，不一定是很远的地方。",
    microEpisodeEn: "Ren asks where you would like to go lately. It does not have to be far away.",
    starterIntentZh: "说一个你最近想去的地方。",
    starterIntentEn: "Talk about a place you want to visit.",
    sampleUserLineJa: "最近、海の近くに行ってみたいです。",
    setup: "Ren lightly asks whether there is somewhere the user wants to go, even if it is only a nearby place.",
    userGoal: "Name a place you want to visit and say a little about the kind of atmosphere you want.",
    npcOpening: "最近、どこか行ってみたい場所はありますか？遠くじゃなくても、少し気になる街とか。",
    possibleBeats: [
      "Ask what kind of place the user wants to visit.",
      "Ask why that place feels appealing right now.",
      "Compare near places with far places in a low-pressure way.",
      "Let Ren add one small observation about walking or atmosphere.",
    ],
    usefulIntents: [
      "say where I want to go",
      "explain why I want to go there",
      "describe a quiet or lively place",
      "say I want to go somewhere nearby",
    ],
    softLanding: "そういう場所の話をすると、少し出かけたくなりますね。また今度、行ってみたい街の話をしましょう。",
    avoid: [
      "Do not immediately recommend sightseeing spots.",
      "Do not create a travel itinerary.",
      "Do not ask about budget, hotels, or transportation.",
    ],
    fallbackUserLines: [
      "最近、海の近くに行ってみたいです。",
      "静かな街に行ってみたいです。",
      "近くでもいいので、少し出かけたいです。",
    ],
    responseOptionsJa: [
      "最近、海の近くに行ってみたいです。",
      "静かな街に行ってみたいです。",
      "近くでもいいので、少し出かけたいです。",
    ],
  },
  ren_planner_or_wanderer: {
    id: "ren_planner_or_wanderer",
    npcId: "ren",
    title: "计划派还是随性派",
    titleZh: "计划派还是随性派",
    titleEn: "Planner or wanderer",
    shortLabel: "旅のタイプ",
    shortLabelZh: "旅のタイプ",
    shortLabelEn: "Travel style",
    microEpisodeZh: "Ren 问你旅行时更喜欢计划好，还是随性一点。",
    microEpisodeEn: "Ren asks whether you prefer planning trips carefully or deciding as you go.",
    starterIntentZh: "表达自己旅行时的习惯。",
    starterIntentEn: "Talk about your travel style.",
    sampleUserLineJa: "どちらかというと、気分で決めるタイプです。",
    setup: "Ren asks whether the user likes planning a trip in advance or deciding things while walking around.",
    userGoal: "Describe your travel style and explain what feels easier or more comfortable for you.",
    npcOpening: "旅行のとき、きっちり計画するタイプですか？それとも、歩きながら決めるタイプですか？",
    possibleBeats: [
      "Ask which style feels more comfortable for the user.",
      "Ask whether too much planning feels tiring.",
      "Let Ren mention that he often leaves some space in his plans.",
      "Keep the comparison gentle instead of judging which style is better.",
    ],
    usefulIntents: [
      "say I prefer planned travel",
      "say I prefer spontaneous travel",
      "explain why I like that style",
      "say fixed schedules can feel tiring",
    ],
    softLanding: "旅の仕方って、人によってちょうどいい形がありますよね。また別の街の話も聞かせてください。",
    avoid: [
      "Do not score or classify the user.",
      "Do not say one travel style is better.",
      "Do not give travel-management advice.",
    ],
    fallbackUserLines: [
      "どちらかというと、気分で決めるタイプです。",
      "少し計画してから行くほうが安心です。",
      "予定を決めすぎると、少し疲れます。",
    ],
    responseOptionsJa: [
      "どちらかというと、気分で決めるタイプです。",
      "少し計画してから行くほうが安心です。",
      "予定を決めすぎると、少し疲れます。",
    ],
  },
  ren_city_you_like: {
    id: "ren_city_you_like",
    npcId: "ren",
    title: "喜欢的城市",
    titleZh: "喜欢的城市",
    titleEn: "A city you like",
    shortLabel: "好きな街",
    shortLabelZh: "好きな街",
    shortLabelEn: "Favorite city",
    microEpisodeZh: "Ren 问你喜欢什么样的城市，可以从氛围说起。",
    microEpisodeEn: "Ren asks what kind of city you like. You can start with the atmosphere.",
    starterIntentZh: "描述你喜欢的城市类型。",
    starterIntentEn: "Describe the kind of city you like.",
    sampleUserLineJa: "静かで歩きやすい街が好きです。",
    setup: "Ren asks the user about a city or neighborhood they like, focusing on atmosphere and walking feel rather than famous spots.",
    userGoal: "Describe the kind of city you like and explain what makes it feel comfortable for you.",
    npcOpening: "好きな街ってありますか？有名な場所じゃなくても、なんとなく落ち着く場所でも。",
    possibleBeats: [
      "Ask what kind of atmosphere the user likes.",
      "Ask whether the user prefers quiet or lively places.",
      "Let Ren mention one small detail like bookstores, cafes, or walkable streets.",
      "Keep the focus on personal preference instead of famous attractions.",
    ],
    usefulIntents: [
      "describe a city I like",
      "explain why I like a place",
      "compare quiet and lively places",
      "talk about cafes, bookstores, or walkable streets",
    ],
    softLanding: "好きな街の話って、その人らしさが少し出ますよね。また別の場所の話もしたいです。",
    avoid: [
      "Do not make city rankings.",
      "Do not list sightseeing spots.",
      "Do not turn the conversation into a city guide.",
    ],
    fallbackUserLines: [
      "静かで歩きやすい街が好きです。",
      "にぎやかすぎない街が好きです。",
      "カフェや本屋がある街が好きです。",
    ],
    responseOptionsJa: [
      "静かで歩きやすい街が好きです。",
      "にぎやかすぎない街が好きです。",
      "カフェや本屋がある街が好きです。",
    ],
  },
  ren_solo_trip: {
    id: "ren_solo_trip",
    npcId: "ren",
    title: "一个人旅行",
    titleZh: "一个人旅行",
    titleEn: "Traveling alone",
    shortLabel: "一人旅",
    shortLabelZh: "一人旅",
    shortLabelEn: "Solo trip",
    microEpisodeZh: "Ren 提到一个人旅行的感觉，你可以说自己是否想试试。",
    microEpisodeEn: "Ren talks about the feeling of traveling alone. You can say whether you want to try it.",
    starterIntentZh: "表达对一个人旅行的感受。",
    starterIntentEn: "Talk about how you feel about traveling alone.",
    sampleUserLineJa: "一人旅は少し不安ですが、興味があります。",
    setup: "Ren brings up the mix of freedom and unease in solo travel and invites the user to react.",
    userGoal: "Say how you feel about traveling alone and whether it sounds appealing, difficult, or both.",
    npcOpening: "一人で知らない街を歩くと、少し不安だけど、自由な感じもありますよね。",
    possibleBeats: [
      "Ask whether solo travel sounds exciting or uneasy.",
      "Ask what part of it feels difficult for the user.",
      "Let Ren share a small feeling without glorifying freedom.",
      "Keep the scene grounded and low-pressure.",
    ],
    usefulIntents: [
      "say I am interested in solo travel",
      "say solo travel feels a little scary",
      "say walking alone in a new city sounds fun",
      "say I feel safer traveling with someone",
    ],
    softLanding: "一人でも誰かとでも、そのときに合う形がありますよね。また気になる場所の話もしましょう。",
    avoid: [
      "Do not preach that people should be freer.",
      "Do not encourage risky behavior.",
      "Do not turn Ren into a life coach.",
    ],
    fallbackUserLines: [
      "一人旅は少し不安ですが、興味があります。",
      "一人で知らない街を歩くのは楽しそうです。",
      "誰かと一緒のほうが安心です。",
    ],
    responseOptionsJa: [
      "一人旅は少し不安ですが、興味があります。",
      "一人で知らない街を歩くのは楽しそうです。",
      "誰かと一緒のほうが安心です。",
    ],
  },
  ren_small_travel_trouble: {
    id: "ren_small_travel_trouble",
    npcId: "ren",
    title: "旅行中的小麻烦",
    titleZh: "旅行中的小麻烦",
    titleEn: "A small travel trouble",
    shortLabel: "旅の困りごと",
    shortLabelZh: "旅の困りごと",
    shortLabelEn: "Travel trouble",
    microEpisodeZh: "Ren 聊起旅行中的小麻烦，你可以说一个简单经历。",
    microEpisodeEn: "Ren brings up small travel troubles. You can share a simple experience.",
    starterIntentZh: "讲一个旅行中遇到的小问题。",
    starterIntentEn: "Share a small trouble you had while traveling.",
    sampleUserLineJa: "前に旅行したとき、道に迷ったことがあります。",
    setup: "Ren brings up the small troubles that stay in memory after a trip, such as getting lost or taking the wrong train.",
    userGoal: "Share one small travel trouble and keep the focus on the experience, not on solving it.",
    npcOpening: "旅先で少し困ったことって、あとから思い出すと意外と覚えていますよね。",
    possibleBeats: [
      "Ask what happened in that small trouble.",
      "Ask how the user felt at that moment.",
      "Let Ren lightly say he remembers those small moments too.",
      "Keep the conversation anecdotal rather than solution-oriented.",
    ],
    usefulIntents: [
      "talk about a small travel trouble",
      "say I got lost once",
      "say I took the wrong train",
      "say I had trouble because of language",
    ],
    softLanding: "そういう小さな出来事って、あとで思い返すと印象に残りますよね。また別の旅の話も聞きたいです。",
    avoid: [
      "Do not turn it into emergency help.",
      "Do not provide long solutions.",
      "Do not correct the user's story like an essay.",
    ],
    fallbackUserLines: [
      "前に旅行したとき、道に迷ったことがあります。",
      "電車を乗り間違えたことがあります。",
      "言葉がうまく通じなくて、少し困りました。",
    ],
    responseOptionsJa: [
      "前に旅行したとき、道に迷ったことがあります。",
      "電車を乗り間違えたことがあります。",
      "言葉がうまく通じなくて、少し困りました。",
    ],
  },
  ren_why_stay_here: {
    id: "ren_why_stay_here",
    npcId: "ren",
    title: "为什么留在言街",
    titleZh: "为什么留在言街",
    titleEn: "Why stay here",
    shortLabel: "言街にいる理由",
    shortLabelZh: "言街にいる理由",
    shortLabelEn: "Why Kotomachi",
    microEpisodeZh: "Ren 提到言街让他想留下，你可以问原因。",
    microEpisodeEn: "Ren says Kotomachi makes him want to stay. You can ask why.",
    starterIntentZh: "询问他为什么暂时住在言街。",
    starterIntentEn: "Ask why he decided to stay in Kotomachi for a while.",
    sampleUserLineJa: "どうして言街に住もうと思ったんですか？",
    setup: "Ren mentions that Kotomachi is not a big town, but it has a feeling that makes him want to return and stay for a while.",
    userGoal: "Ask why Ren decided to stay in Kotomachi and keep the conversation on the town's atmosphere rather than a dramatic backstory.",
    npcOpening: "言街って、大きな街ではないけど、戻ってきたくなる感じがあるんです。",
    possibleBeats: [
      "Ask what Ren likes about Kotomachi.",
      "Ask whether he still wants to visit other cities.",
      "Let Ren mention quiet streets or the feeling of coming back.",
      "End by returning softly to the user's own favorite places.",
    ],
    usefulIntents: [
      "ask why Ren stayed in Kotomachi",
      "ask what he likes about Kotomachi",
      "ask whether he wants to visit another city again",
      "talk about what makes a place feel comfortable",
    ],
    softLanding: "戻ってきたくなる場所って、人によって少し違いますよね。また今度、そういう街の話をしましょう。",
    avoid: [
      "Do not write a heavy life story.",
      "Do not preach about belonging.",
      "Do not let Ren monologue for too long.",
    ],
    fallbackUserLines: [
      "どうして言街に住もうと思ったんですか？",
      "言街のどんなところが好きですか？",
      "また別の街に行きたいと思いますか？",
    ],
    responseOptionsJa: [
      "どうして言街に住もうと思ったんですか？",
      "言街のどんなところが好きですか？",
      "また別の街に行きたいと思いますか？",
    ],
  },
  mao_first_day_greeting: {
    id: "mao_first_day_greeting",
    npcId: "mao",
    title: "第一天来打工",
    titleZh: "第一天来打工",
    titleEn: "First day at part-time work",
    shortLabel: "初日",
    shortLabelZh: "第一天",
    shortLabelEn: "First day",
    microEpisodeZh: "你第一次来到言街的多功能空间帮忙，有点紧张，但想先自然地和真央打招呼。",
    microEpisodeEn: "You are helping at Kotomachi's community space for the first time and want to greet Mao naturally.",
    starterIntentZh: "初次打招呼，表达请多关照。",
    starterIntentEn: "Greet your part-time senpai politely on your first day.",
    sampleUserLineJa: "今日からお世話になります。よろしくお願いします。",
    setup: "You arrive at Kotomachi's community space for your first part-time shift. You want to greet Mao naturally before starting.",
    userGoal: "Say a polite first greeting and show that you are ready to start without sounding stiff or formal-business.",
    npcOpening: "こんにちは。今日から来てくれてありがとう。まずは一緒に場所を確認していこうか。",
    possibleBeats: [
      "Greet Mao politely.",
      "Say you feel a little nervous.",
      "Ask what to do first.",
      "Let Mao ease the atmosphere.",
    ],
    usefulIntents: [
      "greet a part-time senpai",
      "say I am a little nervous",
      "ask what to do first",
      "say please take care of me",
    ],
    softLanding: "最初に一言あるだけで、少し落ち着きますよね。続きは、やりながら少しずつ聞いていけば大丈夫です。",
    avoid: [
      "Do not turn this into a business Japanese lesson.",
      "Do not act like a boss, HR, or career coach.",
      "Do not use overly formal business keigo.",
      "Keep the scene as soft context, not a task flow.",
    ],
    fallbackUserLines: [
      "今日からお世話になります。よろしくお願いします。",
      "はい、お願いします。",
      "少し緊張しています。",
    ],
    responseOptionsJa: [
      "はい、お願いします。",
      "まずは何をすればいいですか。",
      "少し緊張しています。",
    ],
  },
  mao_ask_to_explain_again: {
    id: "mao_ask_to_explain_again",
    npcId: "mao",
    title: "没听懂说明",
    titleZh: "没听懂说明",
    titleEn: "Ask for the explanation again",
    shortLabel: "もう一度",
    shortLabelZh: "再说一次",
    shortLabelEn: "Explain again",
    microEpisodeZh: "真央刚刚说明了一件事，但你没有完全听懂，想礼貌地请她再说一遍。",
    microEpisodeEn: "Mao explained something, but you did not fully understand and want to ask her to explain again.",
    starterIntentZh: "请求再说明一次。",
    starterIntentEn: "Ask for the explanation again politely.",
    sampleUserLineJa: "すみません、もう一度教えていただいてもいいですか。",
    setup: "Mao just explained a task, but you did not fully catch it. You want to ask again without sounding too heavy.",
    userGoal: "Ask Mao to explain again politely and keep the tone natural for a light workplace scene.",
    npcOpening: "あ、分かりにくかったね。どこが少し曖昧だった？",
    possibleBeats: [
      "Ask Mao to repeat it.",
      "Point to the unclear part.",
      "Say the wording felt difficult.",
      "Let Mao rephrase it more simply.",
    ],
    usefulIntents: [
      "ask to explain again",
      "say one part was unclear",
      "say the words felt difficult",
      "ask to hear the whole thing once more",
    ],
    softLanding: "聞き直しても大丈夫だと思えると、少し話しやすくなりますよね。分かったところからまた進めましょう。",
    avoid: [
      "Do not turn this into a business Japanese lesson.",
      "Do not act like a strict trainer or teacher.",
      "Do not score or correct the user in the main chat.",
      "Keep the scene as soft context, not a task flow.",
    ],
    fallbackUserLines: [
      "すみません、もう一度教えていただいてもいいですか。",
      "この部分が少し分からなくて。",
      "全体をもう一度聞いてもいいですか。",
    ],
    responseOptionsJa: [
      "この部分が少し分からなくて。",
      "全体をもう一度聞いてもいいですか。",
      "言葉が少し難しくて。",
    ],
  },
  mao_confirm_task_understanding: {
    id: "mao_confirm_task_understanding",
    npcId: "mao",
    title: "确认任务理解",
    titleZh: "确认任务理解",
    titleEn: "Confirm task understanding",
    shortLabel: "確認",
    shortLabelZh: "确认理解",
    shortLabelEn: "Confirm",
    microEpisodeZh: "你大概明白了要做什么，但想先复述一下，确认自己没有理解错。",
    microEpisodeEn: "You roughly understand the task, but want to repeat it back to make sure.",
    starterIntentZh: "复述任务并确认。",
    starterIntentEn: "Repeat the task back and confirm.",
    sampleUserLineJa: "つまり、先にここを確認すればいいですか。",
    setup: "You think you understand Mao's instructions, but want to repeat the key point back before moving on.",
    userGoal: "Confirm the task naturally so you can avoid mistakes without sounding too formal.",
    npcOpening: "そう、まずはそこを確認して。終わったら声をかけてね。",
    possibleBeats: [
      "Repeat the first step back.",
      "Ask if your understanding is right.",
      "Say you will report after finishing.",
      "Ask whether you can ask again if needed.",
    ],
    usefulIntents: [
      "confirm my understanding",
      "repeat the task back",
      "say I will report after finishing",
      "ask if I can ask again later",
    ],
    softLanding: "一度言い換えて確認できると、次の一歩が少し楽になりますよね。そのまま自然に作業へ戻れます。",
    avoid: [
      "Do not turn this into a test of perfect understanding.",
      "Do not act like a boss checking performance.",
      "Do not use overly formal business keigo.",
      "Keep the scene as soft context, not a task flow.",
    ],
    fallbackUserLines: [
      "つまり、先にここを確認すればいいですか。",
      "分かりました。終わったら報告します。",
      "確認して、何かあれば聞いてもいいですか。",
    ],
    responseOptionsJa: [
      "分かりました。終わったら報告します。",
      "確認して、何かあれば聞いてもいいですか。",
      "ありがとうございます。やってみます。",
    ],
  },
  mao_ask_to_check: {
    id: "mao_ask_to_check",
    npcId: "mao",
    title: "请前辈看一下",
    titleZh: "请前辈看一下",
    titleEn: "Ask Mao to check",
    shortLabel: "見てもらう",
    shortLabelZh: "看一下",
    shortLabelEn: "Check",
    microEpisodeZh: "你完成了一部分工作，但有点不确定，想请真央帮你看一下。",
    microEpisodeEn: "You finished part of the task but feel unsure and want Mao to check it.",
    starterIntentZh: "请求前辈检查。",
    starterIntentEn: "Ask your senpai to check your work.",
    sampleUserLineJa: "ここまでできたんですが、一度見てもらえますか。",
    setup: "You finished part of the work and want Mao to look at it before you continue.",
    userGoal: "Ask Mao to check what you have done so far in a polite but easygoing way.",
    npcOpening: "いいね、ちょっと見てみる。どこが少し不安だった？",
    possibleBeats: [
      "Ask Mao to look at your work.",
      "Point out the part you feel unsure about.",
      "Ask whether she can check the whole thing.",
      "Thank her briefly.",
    ],
    usefulIntents: [
      "ask Mao to check my work",
      "say which part feels uncertain",
      "ask for a quick look",
      "thank Mao",
    ],
    softLanding: "一度見てもらえると、少し安心して続けやすいですよね。必要なら、また短く確認すれば十分です。",
    avoid: [
      "Do not turn this into a business Japanese lesson.",
      "Do not act like a boss doing a formal review.",
      "Do not score or correct the user in the main chat.",
      "Keep the scene as soft context, not a task flow.",
    ],
    fallbackUserLines: [
      "ここまでできたんですが、一度見てもらえますか。",
      "この部分が少し自信なくて。",
      "全体を見ていただけますか。",
    ],
    responseOptionsJa: [
      "この部分が少し自信なくて。",
      "全体を見ていただけますか。",
      "ありがとうございます。",
    ],
  },
  mao_report_progress: {
    id: "mao_report_progress",
    npcId: "mao",
    title: "汇报进度",
    titleZh: "汇报进度",
    titleEn: "Report progress",
    shortLabel: "進み具合",
    shortLabelZh: "汇报进度",
    shortLabelEn: "Report",
    microEpisodeZh: "你做到一半，想简短告诉真央现在进展到哪里了。",
    microEpisodeEn: "You are partway through and want to briefly tell Mao your progress.",
    starterIntentZh: "简短汇报进度。",
    starterIntentEn: "Briefly report your progress.",
    sampleUserLineJa: "ここまで終わりました。次は何をすればいいですか。",
    setup: "You want to update Mao in the middle of work and ask what to do next.",
    userGoal: "Briefly report your progress and move the conversation to the next small step.",
    npcOpening: "ありがとう。次はここをやってみて。終わったらまた声をかけてね。",
    possibleBeats: [
      "Say what you have finished.",
      "Ask what to do next.",
      "Mention it may take some time.",
      "Ask Mao to check again later.",
    ],
    usefulIntents: [
      "report progress",
      "ask what to do next",
      "say it may take time",
      "ask for another check later",
    ],
    softLanding: "途中で一言伝えられると、仕事の流れも少しつかみやすくなります。また次の一言につなげれば十分です。",
    avoid: [
      "Do not turn this into a formal work report.",
      "Do not act like a boss or evaluator.",
      "Do not use overly formal business keigo.",
      "Keep the scene as soft context, not a task flow.",
    ],
    fallbackUserLines: [
      "ここまで終わりました。次は何をすればいいですか。",
      "分かりました。やってみます。",
      "終わったら、また確認をお願いします。",
    ],
    responseOptionsJa: [
      "分かりました。やってみます。",
      "少し時間がかかるかもしれません。",
      "終わったら、また確認をお願いします。",
    ],
  },
  mao_task_might_be_late: {
    id: "mao_task_might_be_late",
    npcId: "mao",
    title: "任务可能来不及",
    titleZh: "任务可能来不及",
    titleEn: "Say the task may take longer",
    shortLabel: "時間がかかる",
    shortLabelZh: "需要时间",
    shortLabelEn: "Need time",
    microEpisodeZh: "你发现手上的事情可能比预想更花时间，想提前告诉真央。",
    microEpisodeEn: "The task may take longer than expected, and you want to tell Mao early.",
    starterIntentZh: "委婉说明还需要一点时间。",
    starterIntentEn: "Say politely that you may need more time.",
    sampleUserLineJa: "すみません、もう少し時間がかかりそうです。",
    setup: "The task is taking longer than you expected. You want to tell Mao before it becomes awkward.",
    userGoal: "Let Mao know you may need more time and keep the tone calm and usable.",
    npcOpening: "あ、そうか。どのくらい時間がかかる見込み？",
    possibleBeats: [
      "Say you may need more time.",
      "Give a rough amount of time.",
      "Explain it is a little more complex than expected.",
      "Show that you are still working on it.",
    ],
    usefulIntents: [
      "say I need more time",
      "give a rough time estimate",
      "say the task is a bit complex",
      "say I am hurrying",
    ],
    softLanding: "少し早めに伝えられると、それだけで気持ちが楽になりますよね。必要なら、そのあとに短く状況を足せば十分です。",
    avoid: [
      "Do not turn this into a business Japanese lesson.",
      "Do not act like a boss, HR, or career coach.",
      "Do not use overly formal business keigo.",
      "Keep the scene as soft context, not a task flow.",
    ],
    fallbackUserLines: [
      "すみません、もう少し時間がかかりそうです。",
      "もう10分くらいかもしれません。",
      "少し複雑で、時間がかかっています。",
    ],
    responseOptionsJa: [
      "もう10分くらいかもしれません。",
      "少し複雑で、時間がかかっています。",
      "急いでやってみます。",
    ],
  },
  mao_made_a_mistake: {
    id: "mao_made_a_mistake",
    npcId: "mao",
    title: "出错了",
    titleZh: "出错了",
    titleEn: "Say you may have made a mistake",
    shortLabel: "間違いかも",
    shortLabelZh: "出错了",
    shortLabelEn: "Mistake",
    microEpisodeZh: "你发现自己可能弄错了一处，想先道歉并请真央一起确认。",
    microEpisodeEn: "You may have made a mistake and want to apologize lightly and ask Mao to check.",
    starterIntentZh: "道歉并请求确认。",
    starterIntentEn: "Apologize lightly and ask for confirmation.",
    sampleUserLineJa: "すみません、ここを間違えてしまったかもしれません。",
    setup: "You notice that you may have made a mistake. You want to tell Mao early and check it together.",
    userGoal: "Apologize lightly, point out the possible mistake, and ask Mao to help confirm it.",
    npcOpening: "あ、そうか。どこが少し違ってた？一緒に見てみよう。",
    possibleBeats: [
      "Say you may have made a mistake.",
      "Point to the part that went wrong.",
      "Ask to check it again.",
      "Ask whether you can fix it and show it again.",
    ],
    usefulIntents: [
      "say I made a mistake",
      "ask Mao to check again",
      "ask if I can fix it",
      "point out the wrong part",
    ],
    softLanding: "間違いに気づいた時に一言言えるだけでも十分ですよね。そこから一緒に直せば大丈夫です。",
    avoid: [
      "Do not turn this into a harsh correction scene.",
      "Do not act like a boss or evaluator.",
      "Do not score or correct the user in the main chat.",
      "Keep the scene as soft context, not a task flow.",
    ],
    fallbackUserLines: [
      "すみません、ここを間違えてしまったかもしれません。",
      "この部分を間違えてしまいました。",
      "もう一度確認してもいいですか。",
    ],
    responseOptionsJa: [
      "この部分を間違えてしまいました。",
      "もう一度確認してもいいですか。",
      "修正して、また見てもらえますか。",
    ],
  },
  mao_customer_asked_unknown_question: {
    id: "mao_customer_asked_unknown_question",
    npcId: "mao",
    title: "访客问了不知道的问题",
    titleZh: "访客问了不知道的问题",
    titleEn: "Ask Mao about a visitor question",
    shortLabel: "訪客の質問",
    shortLabelZh: "访客问题",
    shortLabelEn: "Visitor question",
    microEpisodeZh: "有访客问了一个你不知道怎么回答的问题，你想先向真央求助。",
    microEpisodeEn: "A visitor asked something you do not know how to answer, so you want to ask Mao for help.",
    starterIntentZh: "向前辈求助。",
    starterIntentEn: "Ask your senpai how to answer.",
    sampleUserLineJa: "お客様に聞かれたんですが、どう答えればいいですか。",
    setup: "A visitor asked you something you do not know. You want to ask Mao before giving a wrong answer.",
    userGoal: "Ask Mao how to respond to a visitor question without turning the moment into a heavy problem.",
    npcOpening: "何を聞かれた？少し教えてみて。",
    possibleBeats: [
      "Say a visitor asked something.",
      "Tell Mao what the visitor asked.",
      "Ask what sounds natural to say.",
      "Say you were not sure and got stuck.",
    ],
    usefulIntents: [
      "ask Mao how to answer",
      "say what the visitor asked",
      "ask what sounds natural",
      "say I got stuck",
    ],
    softLanding: "分からない時にすぐ聞けるだけでも十分ですよね。次は、その一言だけ覚えておけば大丈夫です。",
    avoid: [
      "Do not turn this into a customer-service manual.",
      "Do not act like a boss, HR, or trainer.",
      "Do not use overly formal business keigo.",
      "Keep the scene as soft context, not a task flow.",
    ],
    fallbackUserLines: [
      "お客様に聞かれたんですが、どう答えればいいですか。",
      "この内容を聞かれました。",
      "どう答えるのが自然ですか。",
    ],
    responseOptionsJa: [
      "この内容を聞かれました。",
      "どう答えるのが自然ですか。",
      "少し分からなくて、困ってしまいました。",
    ],
  },
  mao_offer_to_help: {
    id: "mao_offer_to_help",
    npcId: "mao",
    title: "主动帮忙",
    titleZh: "主动帮忙",
    titleEn: "Offer to help",
    shortLabel: "手伝います",
    shortLabelZh: "主动帮忙",
    shortLabelEn: "Help",
    microEpisodeZh: "你手上的事情做完了，想自然地问还有没有能帮忙的地方。",
    microEpisodeEn: "You finished your task and want to ask if there is anything else you can help with.",
    starterIntentZh: "主动问有没有能做的事。",
    starterIntentEn: "Ask if there is anything you can help with.",
    sampleUserLineJa: "何か手伝えることはありますか。",
    setup: "You finished your part and want to ask Mao if there is anything else you can do.",
    userGoal: "Offer help naturally without sounding too eager or too formal.",
    npcOpening: "ありがとう。今は少し余裕があるから、ここをやってみて。",
    possibleBeats: [
      "Ask if there is anything else to do.",
      "Accept the next small task.",
      "Thank Mao briefly.",
      "Say it may take a little time.",
    ],
    usefulIntents: [
      "offer to help",
      "accept the next task",
      "thank Mao",
      "say it may take a little time",
    ],
    softLanding: "終わったあとに一言聞けると、場の流れにも入りやすいですよね。小さく手伝うところからで十分です。",
    avoid: [
      "Do not turn this into a formal workplace evaluation.",
      "Do not act like a boss or career coach.",
      "Do not use overly formal business keigo.",
      "Keep the scene as soft context, not a task flow.",
    ],
    fallbackUserLines: [
      "何か手伝えることはありますか。",
      "分かりました。やってみます。",
      "ありがとうございます。",
    ],
    responseOptionsJa: [
      "分かりました。やってみます。",
      "ありがとうございます。",
      "少し時間がかかるかもしれません。",
    ],
  },
  mao_late_or_contact: {
    id: "mao_late_or_contact",
    npcId: "mao",
    title: "迟到 / 临时联系",
    titleZh: "迟到 / 临时联系",
    titleEn: "Say you may be late",
    shortLabel: "遅れそう",
    shortLabelZh: "可能迟到",
    shortLabelEn: "Late",
    microEpisodeZh: "你可能会迟到一点，想提前联系真央说明情况。",
    microEpisodeEn: "You may be a little late and want to tell Mao ahead of time.",
    starterIntentZh: "提前说明迟到。",
    starterIntentEn: "Tell Mao ahead of time that you may be late.",
    sampleUserLineJa: "すみません、少し遅れそうです。",
    setup: "You think you may be late and want to contact Mao before arriving.",
    userGoal: "Let Mao know you may be late and add a short reason or time estimate naturally.",
    npcOpening: "あ、そうか。どのくらい遅れる見込み？",
    possibleBeats: [
      "Say you may be late.",
      "Give a rough delay estimate.",
      "Mention traffic or another small reason.",
      "Say you are hurrying.",
    ],
    usefulIntents: [
      "say I may be late",
      "give a delay estimate",
      "mention a reason",
      "say I am on my way",
    ],
    softLanding: "早めに一言入れられるだけでも十分ですよね。そのあとに短く状況を足せば自然です。",
    avoid: [
      "Do not turn this into a strict attendance warning.",
      "Do not act like a boss or HR.",
      "Do not use overly formal business keigo.",
      "Keep the scene as soft context, not a task flow.",
    ],
    fallbackUserLines: [
      "すみません、少し遅れそうです。",
      "もう5分くらい遅れるかもしれません。",
      "急いで行きます。",
    ],
    responseOptionsJa: [
      "もう5分くらい遅れるかもしれません。",
      "交通が少し混んでいて。",
      "急いで行きます。",
    ],
  },
  mao_shift_change: {
    id: "mao_shift_change",
    npcId: "mao",
    title: "换班 / 调整时间",
    titleZh: "换班 / 调整时间",
    titleEn: "Ask about changing a shift",
    shortLabel: "シフト相談",
    shortLabelZh: "调整时间",
    shortLabelEn: "Shift",
    microEpisodeZh: "下周的安排有变化，你想委婉地和真央商量排班。",
    microEpisodeEn: "Your schedule changed next week, and you want to ask Mao about changing a shift.",
    starterIntentZh: "委婉请求调整排班。",
    starterIntentEn: "Politely ask about changing a shift.",
    sampleUserLineJa: "来週のシフトを少し相談してもいいですか。",
    setup: "Something changed in your schedule for next week. You want to ask Mao about it in a calm way.",
    userGoal: "Bring up a shift change politely and explain that your schedule has changed.",
    npcOpening: "いいよ。何か予定が変わった？",
    possibleBeats: [
      "Ask if you can talk about next week's shift.",
      "Say your schedule changed.",
      "Ask whether one day can be adjusted.",
      "Thank Mao for listening.",
    ],
    usefulIntents: [
      "ask to discuss a shift",
      "say my schedule changed",
      "ask to adjust one day",
      "thank Mao",
    ],
    softLanding: "予定の相談は、一言出せるだけでも少し気が楽になりますよね。細かい話はそのあとで十分です。",
    avoid: [
      "Do not turn this into HR or contract advice.",
      "Do not act like a boss or career coach.",
      "Do not use overly formal business keigo.",
      "Keep the scene as soft context, not a task flow.",
    ],
    fallbackUserLines: [
      "来週のシフトを少し相談してもいいですか。",
      "少し予定が変わってしまいました。",
      "この日を変更してもいいですか。",
    ],
    responseOptionsJa: [
      "少し予定が変わってしまいました。",
      "この日を変更してもいいですか。",
      "ありがとうございます。",
    ],
  },
  mao_leave_after_work: {
    id: "mao_leave_after_work",
    npcId: "mao",
    title: "下班离开",
    titleZh: "下班离开",
    titleEn: "Leave after work",
    shortLabel: "お先に失礼します",
    shortLabelZh: "下班寒暄",
    shortLabelEn: "Leaving",
    microEpisodeZh: "今天的工作结束了，你想自然地和真央打声招呼再离开。",
    microEpisodeEn: "The work is done for today, and you want to say a natural goodbye before leaving.",
    starterIntentZh: "自然收尾寒暄。",
    starterIntentEn: "Say goodbye naturally after work.",
    sampleUserLineJa: "お先に失礼します。今日はありがとうございました。",
    setup: "Your work is done for today. You want to say a natural goodbye to Mao before leaving.",
    userGoal: "Close the interaction warmly and politely without sounding like a scripted business phrase.",
    npcOpening: "ありがとう、今日もお疲れさま。また来てね。",
    possibleBeats: [
      "Say you are leaving first.",
      "Thank Mao for today.",
      "Return a short good-bye.",
      "Mention next time lightly.",
    ],
    usefulIntents: [
      "say I am leaving now",
      "thank Mao for today",
      "say good work today",
      "mention next time lightly",
    ],
    softLanding: "終わりに一言あるだけで、その日のやり取りがきれいにまとまりますよね。また次の場面にも自然につながります。",
    avoid: [
      "Do not turn this into a business Japanese lesson.",
      "Do not act like a boss, HR, or career coach.",
      "Do not use overly formal business keigo.",
      "Keep the scene as soft context, not a task flow.",
    ],
    fallbackUserLines: [
      "お先に失礼します。今日はありがとうございました。",
      "ありがとうございます。また次回お願いします。",
      "お疲れさまです。",
    ],
    responseOptionsJa: [
      "ありがとうございます。また次回お願いします。",
      "お疲れさまです。",
      "また来週お願いします。",
    ],
  },
  saku_owl_at_window: {
    id: "saku_owl_at_window",
    npcId: "saku",
    title: "猫头鹰在窗边",
    titleZh: "猫头鹰在窗边",
    titleEn: "The owl at the window",
    shortLabel: "窗边的モク",
    shortLabelZh: "窗边的モク",
    shortLabelEn: "Moku at the window",
    microEpisodeZh: "夜里，モク一直停在窗边，看着街角的方向。你有点好奇它到底在看什么。",
    microEpisodeEn: "At night, Moku keeps sitting by the window and looking toward the street corner. You wonder what it is watching.",
    starterIntentZh: "问朔，モク在看什么。",
    starterIntentEn: "Ask Saku what Moku is watching.",
    sampleUserLineJa: "モクが窓の外を見てる。何を見てるんだろう。",
    setup: "Moku is sitting by the window at night, staring at one spot outside.",
    userGoal: "The user wants to ask what Moku is looking at and enter Saku's world gently.",
    npcOpening: "さっきから同じ場所を見てるね。たぶん、誰かが言い忘れた言葉を探してるんだと思う。",
    possibleBeats: [
      "Saku notices Moku watching the street.",
      "Saku suggests Moku may be looking for forgotten words.",
      "The user can ask what forgotten words are.",
      "The scene stays small and quiet.",
    ],
    usefulIntents: [
      "ask what someone is looking at",
      "describe a strange small observation",
      "ask about forgotten words",
      "react softly to something mysterious",
    ],
    softLanding: "Saku may end by saying that some words come back when they are ready.",
    avoid: [
      "Do not turn Moku into a magical familiar explanation.",
      "Do not say Saku is a wizard.",
      "Do not give the user a quest.",
      "Do not make the scene scary.",
      "Do not overexplain lore.",
    ],
    fallbackUserLines: [
      "モクは何を見てるんですか。",
      "何かあるんですか。",
      "少し気になります。",
    ],
    responseOptionsJa: [
      "言い忘れた言葉って、どんなものですか。",
      "モクには見えるんですか。",
      "少し不思議ですね。",
    ],
  },
  saku_weird_dream: {
    id: "saku_weird_dream",
    npcId: "saku",
    title: "做了一个奇怪的梦",
    titleZh: "做了一个奇怪的梦",
    titleEn: "A strange dream",
    shortLabel: "変な夢",
    shortLabelZh: "奇怪的梦",
    shortLabelEn: "Strange dream",
    microEpisodeZh: "你做了一个奇怪的梦。醒来以后，梦里的感觉还留着，但你说不太清楚。",
    microEpisodeEn: "You had a strange dream. After waking up, the feeling remains, but you cannot quite explain it.",
    starterIntentZh: "告诉朔，你做了一个奇怪的梦。",
    starterIntentEn: "Tell Saku you had a strange dream.",
    sampleUserLineJa: "変な夢を見ました。起きてもまだ少し残っています。",
    setup: "The user had a strange dream and wants to describe the lingering feeling.",
    userGoal: "The user practices describing vague dreamlike impressions.",
    npcOpening: "夢の中の言葉って、起きてからも少しだけ残ることがあるよね。どんな感じだった？",
    possibleBeats: [
      "Saku accepts the dream without interpreting too much.",
      "The user describes one image or feeling.",
      "Saku offers a small phrase to express the after-feeling.",
      "The scene stays ambiguous and gentle.",
    ],
    usefulIntents: [
      "describe a dream",
      "say something is hard to explain",
      "talk about a lingering feeling",
      "use なんとなく / うまく言えないけど",
    ],
    softLanding: "Saku may say that some dreams leave only one small sentence behind.",
    avoid: [
      "Do not interpret the dream like fortune telling.",
      "Do not diagnose the user.",
      "Do not make the dream scary.",
      "Do not turn it into a quest or prophecy.",
      "Do not overexplain.",
    ],
    fallbackUserLines: [
      "変な夢を見ました。",
      "まだ少し覚えています。",
      "うまく言えない感じです。",
    ],
    responseOptionsJa: [
      "うまく言えないけど、少し懐かしい感じでした。",
      "夢の中で、知らない道を歩いていました。",
      "意味があるのか分かりません。",
    ],
  },
  saku_street_rumor: {
    id: "saku_street_rumor",
    npcId: "saku",
    title: "听说街上有怪事",
    titleZh: "听说街上有怪事",
    titleEn: "A strange street rumor",
    shortLabel: "街のうわさ",
    shortLabelZh: "街上传闻",
    shortLabelEn: "Street rumor",
    microEpisodeZh: "你听说言街最近有一点奇怪的传闻。你想问问朔有没有听过。",
    microEpisodeEn: "You heard a strange rumor about Kotomachi and want to ask Saku if he knows anything.",
    starterIntentZh: "向朔提起街上的怪传闻。",
    starterIntentEn: "Bring up a strange street rumor to Saku.",
    sampleUserLineJa: "この町で、変なうわさを聞きました。",
    setup: "The user heard a rumor about Kotomachi and brings it to Saku.",
    userGoal: "The user practices hearsay and rumor expressions.",
    npcOpening: "うわさは、全部うそでも全部ほんとうでもないからね。どんな話だった？",
    possibleBeats: [
      "Saku listens without confirming everything.",
      "The user describes the rumor.",
      "Saku gives a small, ambiguous response.",
      "The conversation stays light and non-scary.",
    ],
    usefulIntents: [
      "say I heard that...",
      "describe a rumor",
      "ask if something is true",
      "react to uncertainty",
    ],
    softLanding: "Saku may say that rumors sometimes remember things people forget.",
    avoid: [
      "Do not confirm supernatural facts too directly.",
      "Do not make Saku a lore exposition machine.",
      "Do not make the rumor scary.",
      "Do not introduce a magic organization.",
      "Do not use IP-like terms.",
    ],
    fallbackUserLines: [
      "変なうわさを聞きました。",
      "本当か分かりません。",
      "少し気になります。",
    ],
    responseOptionsJa: [
      "夜に変な紙を見た人がいるらしいです。",
      "時計が少し遅れるって聞きました。",
      "モクのことを聞きました。",
    ],
  },
  saku_forgot_something: {
    id: "saku_forgot_something",
    npcId: "saku",
    title: "好像忘了什么",
    titleZh: "好像忘了什么",
    titleEn: "I feel like I forgot something",
    shortLabel: "忘れた気がする",
    shortLabelZh: "好像忘了",
    shortLabelEn: "Forgot something",
    microEpisodeZh: "你觉得自己好像忘了一件重要的事，但又想不起来具体是什么。",
    microEpisodeEn: "You feel like you forgot something important, but cannot remember what it was.",
    starterIntentZh: "告诉朔，你好像忘了什么。",
    starterIntentEn: "Tell Saku you feel like you forgot something.",
    sampleUserLineJa: "何か大事なことを忘れている気がします。",
    setup: "The user has a vague feeling of having forgotten something important.",
    userGoal: "The user practices expressing uncertainty and vague memory.",
    npcOpening: "忘れた言葉って、急に戻ってくることがあるよ。どんな感じのものだった？",
    possibleBeats: [
      "Saku does not diagnose or pressure the user.",
      "The user describes the shape of the forgotten thing.",
      "Saku frames it as a forgotten word, not a problem.",
      "The scene ends softly.",
    ],
    usefulIntents: [
      "say I feel like...",
      "describe a vague memory",
      "talk about forgotten words",
      "express uncertainty",
    ],
    softLanding: "Saku may say that if the word is important, it may return when the user is ready.",
    avoid: [
      "Do not diagnose memory loss.",
      "Do not make it psychological counseling.",
      "Do not make it scary.",
      "Do not claim Saku can restore memories with magic.",
      "Do not overpromise.",
    ],
    fallbackUserLines: [
      "何か忘れている気がします。",
      "言葉が出てきません。",
      "大事なことだった気がします。",
    ],
    responseOptionsJa: [
      "言葉だった気がします。",
      "誰かに言いたかったことかもしれません。",
      "思い出せそうで、思い出せません。",
    ],
  },
  saku_owl_brought_note: {
    id: "saku_owl_brought_note",
    npcId: "saku",
    title: "猫头鹰叼来了纸条",
    titleZh: "猫头鹰叼来了纸条",
    titleEn: "The owl brought a note",
    shortLabel: "モクの紙",
    shortLabelZh: "モク的纸条",
    shortLabelEn: "Moku's note",
    microEpisodeZh: "モク叼来了一张折好的纸条。纸条没有署名，你想问朔这是什么。",
    microEpisodeEn: "Moku brought a folded note. It has no name on it, so you ask Saku what it might be.",
    starterIntentZh: "问朔，モク带来的纸条是什么。",
    starterIntentEn: "Ask Saku about the note Moku brought.",
    sampleUserLineJa: "モクが折りたたんだ紙を持ってきました。誰が書いたんだろう。",
    setup: "Moku brings a folded note with no name on it.",
    userGoal: "The user asks what the note might be and practices curiosity.",
    npcOpening: "名前がない紙は、すぐに捨てないほうがいいよ。誰かの言い忘れたことかもしれない。",
    possibleBeats: [
      "Saku warns gently not to throw it away immediately.",
      "The user wonders who wrote it.",
      "The note may contain an unsaid word.",
      "The scene stays small and mysterious.",
    ],
    usefulIntents: [
      "ask who wrote something",
      "describe a note",
      "ask whether it is okay to read something",
      "express curiosity",
    ],
    softLanding: "Saku may suggest keeping the note until its owner is ready.",
    avoid: [
      "Do not make the note a quest item.",
      "Do not reveal a secret organization.",
      "Do not make Moku a formal messenger system.",
      "Do not make it scary.",
      "Do not use spell or magic-school language.",
    ],
    fallbackUserLines: [
      "この紙、誰のものですか。",
      "読んでもいいですか。",
      "名前が書いてありません。",
    ],
    responseOptionsJa: [
      "中を読んでもいいですか。",
      "誰かのものかもしれませんね。",
      "少し気になります。",
    ],
  },
  saku_receipt_message: {
    id: "saku_receipt_message",
    npcId: "saku",
    title: "收据上多出一句话",
    titleZh: "收据上多出一句话",
    titleEn: "A line appeared on the receipt",
    shortLabel: "変なレシート",
    shortLabelZh: "奇怪收据",
    shortLabelEn: "Odd receipt",
    microEpisodeZh: "你从贩卖机附近捡到一张收据，上面多了一句你不记得见过的话。",
    microEpisodeEn: "You found a receipt near the vending machine. A line appeared on it that you do not remember seeing.",
    starterIntentZh: "告诉朔，收据上多了一句话。",
    starterIntentEn: "Tell Saku a strange line appeared on the receipt.",
    sampleUserLineJa: "レシートに、知らない一文が増えていました。",
    setup: "A strange line appears on a receipt near the vending machine.",
    userGoal: "The user describes an ordinary object with an unusual sentence on it.",
    npcOpening: "レシートは、ときどき余計なことまで覚えてるんだ。どんな一文だった？",
    possibleBeats: [
      "Saku treats the receipt as strange but not frightening.",
      "The user reads or describes the line.",
      "Saku suggests it may be a word someone forgot to say.",
      "The scene connects softly to the vending machine secret.",
    ],
    usefulIntents: [
      "describe something written on a receipt",
      "say I don't know who wrote it",
      "say it feels strange but not scary",
      "ask what a sentence might mean",
    ],
    softLanding: "Saku may say the line should be kept until someone is ready to say it.",
    avoid: [
      "Do not make the receipt a cursed object.",
      "Do not make it horror.",
      "Do not turn it into a puzzle or quest.",
      "Do not overexplain the vending machine secret.",
      "Do not mention direct magic terms.",
    ],
    fallbackUserLines: [
      "変なレシートを見つけました。",
      "知らない一文があります。",
      "これ、どういう意味ですか。",
    ],
    responseOptionsJa: [
      "「まだ言ってない」と書いてありました。",
      "誰が書いたのか分かりません。",
      "少し気味が悪いというより、不思議です。",
    ],
  },
  saku_self_turning_book: {
    id: "saku_self_turning_book",
    npcId: "saku",
    title: "自己翻开的旧书",
    titleZh: "自己翻开的旧书",
    titleEn: "The old book opened by itself",
    shortLabel: "開いた古い本",
    shortLabelZh: "自己翻开的书",
    shortLabelEn: "The opened book",
    microEpisodeZh: "一本旧书自己翻到了陌生的一页。你不确定那一页为什么会打开。",
    microEpisodeEn: "An old book opened by itself to an unfamiliar page. You are not sure why.",
    starterIntentZh: "告诉朔，旧书自己翻开了。",
    starterIntentEn: "Tell Saku that an old book opened by itself.",
    sampleUserLineJa: "古い本が、勝手に知らないページを開きました。",
    setup: "An old book opens by itself to a page the user does not recognize.",
    userGoal: "The user describes a strange book event without turning it into a magic lesson.",
    npcOpening: "風で開いたんじゃないかな。……窓、閉まってるけど。そのページ、君を待ってたのかもしれない。",
    possibleBeats: [
      "Saku first offers an ordinary explanation, then lets it sound slightly unconvincing.",
      "Saku focuses on the words on the page rather than explaining the mechanism.",
      "The user can ask why the page opened or what the words mean.",
    ],
    usefulIntents: [
      "say something happened by itself",
      "describe an unfamiliar page",
      "ask why this page opened",
      "talk about words that feel meaningful",
    ],
    softLanding: "Saku may say that some pages open before people are ready to understand them.",
    avoid: [
      "Do not call it a magic book.",
      "Do not explain a magic system.",
      "Do not teach spells.",
      "Do not make the book an RPG item.",
      "Do not make Saku fully honest when directly asked about hidden-world mechanics.",
    ],
    fallbackUserLines: [
      "古い本が勝手に開きました。",
      "知らないページでした。",
      "この言葉、少し気になります。",
    ],
    responseOptionsJa: [
      "少しだけ読めます。",
      "知らない言葉が多いです。",
      "どうしてこのページなんでしょう。",
    ],
  },
  saku_unknown_creature: {
    id: "saku_unknown_creature",
    npcId: "saku",
    title: "没人认识的小动物",
    titleZh: "没人认识的小动物",
    titleEn: "The creature no one recognizes",
    shortLabel: "知らない小さな生き物",
    shortLabelZh: "陌生小动物",
    shortLabelEn: "Unknown creature",
    microEpisodeZh: "街边出现了一只没人认识的小动物。它不吓人，只是低头收集硬币、钥匙和亮闪闪的小东西。朔好像认识它。",
    microEpisodeEn: "A small creature no one recognizes appears by the street. It is not scary; it keeps collecting coins, keys, and shiny little things. Saku seems to know it.",
    starterIntentZh: "告诉朔，街边有只奇怪但不吓人的小动物。",
    starterIntentEn: "Tell Saku there is a strange but harmless little creature by the street.",
    sampleUserLineJa: "見たことのない小さな生き物が、道の端で光るものを集めていました。",
    setup: "A small unknown creature is collecting shiny things near the street.",
    userGoal: "The user describes a harmless strange creature and asks Saku about it.",
    npcOpening: "ああ、あの子か。また光るものを集めてるんだね。怖がらなくていいよ、たぶん向こうも少し困ってる。",
    possibleBeats: [
      "Saku seems to know the creature but does not explain exactly what it is.",
      "The creature likes coins, keys, buttons, hairpins, bottle caps, and shiny scraps.",
      "Saku hints that he looks after it or keeps it temporarily.",
      "The user can ask whether it is safe to approach or whether it took something.",
    ],
    usefulIntents: [
      "describe a creature you have never seen",
      "say it is collecting something shiny",
      "ask whether it is safe to approach",
      "say someone or something looks confused",
    ],
    softLanding: "Saku may suggest leaving one small shiny object nearby and giving it space.",
    avoid: [
      "Do not name or reference Niffler or any IP creature.",
      "Do not call it a magical creature directly.",
      "Do not create a creature encyclopedia.",
      "Do not make Saku a magical creature expert.",
      "Do not turn the scene into a capture task.",
      "Do not make the creature scary or hostile.",
    ],
    fallbackUserLines: [
      "見たことのない生き物がいました。",
      "光るものを集めていました。",
      "近づいても大丈夫ですか。",
    ],
    responseOptionsJa: [
      "何を集めているんですか。",
      "近づいても大丈夫ですか。",
      "朔はあの子を知っているんですか。",
    ],
  },
} as const satisfies Record<string, ConversationSceneConfig>;

export type ConversationSceneId = keyof typeof CONVERSATION_SCENES;
// 用稳定的配置类型导出场景形状，避免巨大字面量 union 在部分页面里被错误推窄。
export type ConversationScene = ConversationSceneConfig;

export function isConversationSceneId(value: string): value is ConversationSceneId {
  return value in CONVERSATION_SCENES;
}

export function getConversationScene(
  sceneId: string | null | undefined,
): ConversationScene | null {
  if (!sceneId || !isConversationSceneId(sceneId)) return null;
  return CONVERSATION_SCENES[sceneId];
}

export function getConversationScenesForNpc(npcId: NpcId): ConversationScene[] {
  return Object.values(CONVERSATION_SCENES).filter((scene) => scene.npcId === npcId);
}

function hasFeaturedSceneFields(scene: ConversationScene): boolean {
  return Boolean(
    scene.id
      && scene.npcId
      && scene.sampleUserLineJa
      && (scene.microEpisodeZh || scene.microEpisodeEn),
  );
}

function getFeaturedSceneDaySeed(date: Date): number {
  const year = date.getFullYear();
  const month = date.getMonth() + 1;
  const day = date.getDate();
  return year * 10000 + month * 100 + day;
}

export function getFeaturedConversationScenes(
  count = 1,
  now = new Date(),
): ConversationScene[] {
  if (count <= 0) return [];

  const eligibleScenes = Object.values(CONVERSATION_SCENES)
    .filter(hasFeaturedSceneFields)
    .filter((scene) => scene.npcId !== "saku")
    .sort((left, right) => left.id.localeCompare(right.id));

  if (eligibleScenes.length === 0) return [];

  const startIndex = getFeaturedSceneDaySeed(now) % eligibleScenes.length;
  const sceneCount = Math.min(count, eligibleScenes.length);

  return Array.from({ length: sceneCount }, (_, offset) => {
    return eligibleScenes[(startIndex + offset) % eligibleScenes.length];
  });
}
