import type { UiLanguage } from "@/lib/ui-language";

export const UI_COPY = {
  zh: {
    common: {
      close: "关闭",
      working: "正在处理…",
      genericError: "处理失败，可以联系开发者解决~。",
    },
    languageToggle: {
      ariaLabel: "切换界面语言",
      zh: "中文",
      en: "EN",
    },
    home: {
      talkToNpc: (npcName: string) => `和${npcName}聊天`,
      cta: "选一个想去的地方，和街上的人聊聊天。",
      talkAction: "去聊聊",
    },
    sidebar: {
      residents: "街上的人",
      learningSection: "学习",
      reviewTitle: "回顾卡片",
      reviewSubtitle: "ふりかえり",
      reviewDescription: "把最近聊天整理成学习回顾",
      createReview: "生成回顾卡",
      creatingReview: "生成中…",
      emptyReview: "聊一会儿后，可以从「+」生成回顾卡，把最近聊天整理成学习内容。",
      backToMap: "返回首页",
      backToMapJp: "首页に戻る",
      navigationLabel: "街上的人导航",
      openMenu: "打开菜单",
      closeMenu: "关闭菜单",
      moreActions: "更多操作",
      reviewDisabledHint: "需要先聊几句，才能生成回顾卡",
      savedSectionTitle: "学习收藏",
      savedTitle: "收藏",
      savedSubtitle: "表达和词语",
      savedCount: (n: number) => `${n} 条收藏`,
      savedAll: "全部",
      savedExpressions: "表达",
      savedWords: "词语",
      savedDelete: "删除",
      savedEmpty: "暂无收藏。你可以从查词或表达提示里保存内容。",
      savedOpen: "查看收藏",
      savedBadgeLookup: "查过的词",
      savedBadgeSummary: "来自对话",
      savedBadgeFeedback: "来自表达提示",
      savedOriginalLabel: "原表达",
      savedNoteLabel: "学习点",
      savedExpressionBadge: "表达",
      savedWordBadge: "词语",
      reviewWordsTitle: "复习单词",
      reviewWordsEmptyHint: "划词查词并收藏后可复习",
    },
    chat: {
      typing: "正在回复…",
      placeholder: "输入消息，日中英都可以…",
      translate: "翻译",
      translating: "翻译中…",
      translationFailed: "翻译失败，可以联系开发者解决~。",
      send: "发送",
      sending: "发送中…",
      switchToVoice: "切换到语音输入",
      switchToText: "切换到文字输入",
      voiceInput: "语音输入",
      textInput: "文字输入",
      startRecording: "开始录音",
      stopRecording: "停止录音",
      holdToTalk: "长按说话",
      recordingRelease: "录音中…松开发送",
      noSpeech: "没听清，可以再说一次，或直接输入文字。",
      sttError: "语音识别失败，可以继续用文字输入。",
      micError: "无法访问麦克风，请在浏览器里允许录音权限。",
      onboardingHintLine1: "不用说完整日语。中 / 英 / 日混着说也可以。",
      onboardingHintLine2: "选中聊天里的词句后，可以点查词并保存。",
      onboardingHintLine3: "发送后把鼠标移到自己的消息上，可以打开「表达提示」看看更自然的说法。",
      preSendMenuTitle: "我想说……",
      preSendMenuSubtitle: "把想法先说出来，我帮你变成自然日语",
      sceneMenuTitle: "街角对话场景",
      sceneMenuSubtitle: "选一个小情境，NPC 先开场，你接一句",
      topicIdeasMenuTitle: "找话题",
      topicIdeasMenuSubtitle: "不知道聊什么时，帮你续一个轻松话题",
      restartMenuTitle: "重新开始",
      restartMenuSubtitle: "清空当前对话，重新开始聊天",
      quickGuideSelectionHint: "选中聊天里的词句后，可以点查词并保存。",
      quickGuideExpressionHint: "发送后把鼠标移到自己的消息上，可以打开「表达提示」看看更自然的说法。",
    },
    feedback: {
      trigger: "表达提示",
      title: "表达提示",
      subtitle: "話し方を比べよう",
      close: "关闭表达提示",
      original: "你的原句",
      error: "表达提示生成失败，可以联系开发者解决~。",
      fallback: "表达提示暂时不可用，可以联系开发者解决~。",
      userRecording: "听自己的录音",
      creating: "正在生成表达提示…",
      listen: "听一下",
      listenFailure: "播放失败，可以联系开发者解决~。",
      recommended: "推荐表达",
      usageLabel: "使用场景",
      whyLabel: "为什么这样说",
      showDetails: "展开说明",
      hideDetails: "收起说明",
      saveExpression: "收藏表达",
      savedExpression: "已收藏",
      regenerate: "重新生成",
      levels: {
        casual: { label: "亲近自然", subtitle: "カジュアル" },
        business: { label: "普通自然", subtitle: "ふつう" },
        formal: { label: "更礼貌", subtitle: "フォーマル" },
      },
    },
    explain: {
      loading: "正在解释…",
      error: "解释失败，可以联系开发者解决~。",
      listen: "听一下",
      close: "关闭解释",
      shortMeaning: "简义",
      sentenceMeaning: "这句话里的意思",
      showExplanation: "展开解释",
      hideExplanation: "收起解释",
      saveWord: "收藏词语",
      savedWord: "已收藏",
      savedWordFeedback: "已保存 · 可在「收藏」或「复习单词」里查看",
    },
    summary: {
      title: "回顾卡片",
      subtitle: "ふりかえり",
      topic: "今天聊了什么",
      topicJp: "今日の話",
      reusable: "可直接复用的表达",
      reusableJp: "そのまま使える表現",
      upgrade: "下次可以这样说",
      upgradeJp: "次はこう言える",
      words: "今日词语",
      wordsJp: "今日のことば",
      nextTopic: "下次可以聊",
      nextTopicJp: "次に話してみること",
      original: "原表达",
      suggestion: "可以这样说",
      note: "学习点",
      fromHint: "来自表达提示",
      fromGap: "来自原句",
      fromConversation: "来自对话",
      lookedUp: "查过的词",
      readingLabel: "读音",
      meaningLabel: "意思",
      exampleLabel: "例句",
      duplicate: "这段对话已经生成过回顾卡片，已为你打开。",
      tooShort: "再聊几句后，就可以生成回顾卡片了。",
      createFailed: "回顾卡片生成失败，可以联系开发者解决~。",
      deleted: "回顾卡片已删除。",
      close: "关闭回顾卡片",
      delete: "删除这张卡片",
    },
    audio: {
      playNpc: "播放语音",
      play: "播放",
      listenRecording: "听录音",
      recordingFailure: "录音播放失败，可以联系开发者解决~。",
    },
  },
  en: {
    common: {
      close: "Close",
      working: "Working…",
      genericError: "Something went wrong. Please contact the developer to solve~.",
    },
    languageToggle: {
      ariaLabel: "Switch UI language",
      zh: "中文",
      en: "EN",
    },
    home: {
      talkToNpc: (npcName: string) => `Talk with ${npcName}`,
      cta: "Choose a place and talk with people in town.",
      talkAction: "Start chatting",
    },
    sidebar: {
      residents: "People in town",
      learningSection: "Learning",
      reviewTitle: "Review Cards",
      reviewSubtitle: "ふりかえり",
      reviewDescription: "Turn recent chat into a learning review",
      createReview: "Create review card",
      creatingReview: "Creating…",
      emptyReview: "After chatting for a while, use “+” to create a review card from recent chat.",
      backToMap: "Back to home",
      backToMapJp: "首页に戻る",
      navigationLabel: "People in town navigation",
      openMenu: "Open menu",
      closeMenu: "Close menu",
      moreActions: "More actions",
      reviewDisabledHint: "Chat a little more before creating a review card",
      savedSectionTitle: "Saved Items",
      savedTitle: "Saved",
      savedSubtitle: "Expressions & words",
      savedCount: (n: number) => `${n} saved items`,
      savedAll: "All",
      savedExpressions: "Expressions",
      savedWords: "Words",
      savedDelete: "Delete",
      savedEmpty: "No saved items yet. Save words or expressions from practice.",
      savedOpen: "View saved",
      savedBadgeLookup: "Looked up",
      savedBadgeSummary: "From conversation",
      savedBadgeFeedback: "From hints",
      savedOriginalLabel: "Original",
      savedNoteLabel: "Note",
      savedExpressionBadge: "Expression",
      savedWordBadge: "Word",
      reviewWordsTitle: "Review words",
      reviewWordsEmptyHint: "Look up selected words and save to review",
    },
    chat: {
      typing: "Replying…",
      placeholder: "Type in Chinese, English, or Japanese…",
      translate: "Translate",
      translating: "Translating…",
      translationFailed: "Translation failed. Please contact the developer to solve~.",
      send: "Send",
      sending: "Sending…",
      switchToVoice: "Switch to voice input",
      switchToText: "Switch to text input",
      voiceInput: "Voice input",
      textInput: "Text input",
      startRecording: "Start recording",
      stopRecording: "Stop recording",
      holdToTalk: "Hold to talk",
      recordingRelease: "Recording… release to send",
      noSpeech: "I couldn’t catch that. Try again or type instead.",
      sttError: "Voice recognition failed. You can keep typing instead.",
      micError: "Couldn’t access the microphone. Please allow recording in your browser.",
      onboardingHintLine1: "You do not need perfect Japanese. Mixing Chinese, English, and Japanese is okay.",
      onboardingHintLine2: "Select words in the chat, then use lookup to save them.",
      onboardingHintLine3: "After sending, hover over your own message to open Expression hint.",
      preSendMenuTitle: "I want to say…",
      preSendMenuSubtitle: "Say your idea first, and I’ll turn it into natural Japanese",
      sceneMenuTitle: "Street-corner scenario",
      sceneMenuSubtitle: "Choose a small scene. The NPC starts, and you reply",
      topicIdeasMenuTitle: "Find a topic",
      topicIdeasMenuSubtitle: "Not sure what to say? Continue with a light topic",
      restartMenuTitle: "Restart",
      restartMenuSubtitle: "Clear the current conversation and start again",
      quickGuideSelectionHint: "Select words in the chat, then use lookup to save them.",
      quickGuideExpressionHint: "After sending a message, hover over your own message to open Expression hint.",
    },
    feedback: {
      trigger: "Expression Hints",
      title: "Expression Hints",
      subtitle: "Compare ways to say it",
      close: "Close expression hints",
      original: "Your original message",
      error: "Expression hint generation failed. Please contact the developer to solve~.",
      fallback: "Expression hints temporarily unavailable. Please contact the developer to solve~.",
      userRecording: "Listen to your recording",
      creating: "Creating expression hints…",
      listen: "Listen",
      listenFailure: "Playback failed. Can’t play this recording. Please contact the developer to solve~",
      recommended: "Recommended expression",
      usageLabel: "Usage",
      whyLabel: "Why this works",
      showDetails: "Show details",
      hideDetails: "Hide details",
      saveExpression: "Save expression",
      savedExpression: "Saved",
      regenerate: "Regenerate",
      levels: {
        casual: { label: "Casual", subtitle: "カジュアル" },
        business: { label: "Neutral", subtitle: "ふつう" },
        formal: { label: "Polite", subtitle: "フォーマル" },
      },
    },
    explain: {
      loading: "Explaining…",
      error: "Explanation failed. Please contact the developer to solve~.",
      listen: "Listen",
      close: "Close explanation",
      shortMeaning: "Short meaning",
      sentenceMeaning: "Meaning in this sentence",
      showExplanation: "Show explanation",
      hideExplanation: "Hide explanation",
      saveWord: "Save word",
      savedWord: "Saved",
      savedWordFeedback: "Saved · Find it in Saved items or Review words",
    },
    summary: {
      title: "Review Card",
      subtitle: "ふりかえり",
      topic: "What you talked about",
      topicJp: "今日の話",
      reusable: "Reusable expressions",
      reusableJp: "そのまま使える表現",
      upgrade: "Try saying it this way",
      upgradeJp: "次はこう言える",
      words: "Words & phrases",
      wordsJp: "今日のことば",
      nextTopic: "What to talk about next",
      nextTopicJp: "次に話してみること",
      original: "Original expression",
      suggestion: "Try this",
      note: "Learning note",
      fromHint: "From expression hints",
      fromGap: "From your input",
      fromConversation: "From conversation",
      lookedUp: "Looked-up word",
      readingLabel: "Reading",
      meaningLabel: "Meaning",
      exampleLabel: "Example",
      duplicate: "This chat already has a review card. I opened it for you.",
      tooShort: "Chat a bit more before creating a review card.",
      createFailed: "Couldn't create a review card. Please contact the developer to solve~.",
      deleted: "Review card deleted.",
      close: "Close review card",
      delete: "Delete this card",
    },
    audio: {
      playNpc: "Play voice",
      play: "Play",
      listenRecording: "Listen to recording",
      recordingFailure: "Recording playback failed. Please contact the developer to solve~.",
    },
  },
} as const;

export type UiCopy = (typeof UI_COPY)[UiLanguage];

export function getUiCopy(language: UiLanguage): UiCopy {
  return UI_COPY[language];
}
