import type { UiLanguage } from "@/lib/ui-language";

export const UI_COPY = {
  zh: {
    common: {
      close: "关闭",
      working: "正在处理…",
      genericError: "处理失败，请稍后再试。",
    },
    languageToggle: {
      ariaLabel: "切换界面语言",
      zh: "中文",
      en: "EN",
    },
    home: {
      talkToNpc: (npcName: string) => `和${npcName}聊天`,
      cta: "点击感兴趣的小店，和店员聊聊天。",
      talkAction: "去聊聊",
    },
    sidebar: {
      residents: "店员",
      reviewTitle: "回顾卡片",
      reviewSubtitle: "ふりかえり",
      reviewDescription: "把这段聊天整理成复习卡片。",
      createReview: "生成本次回顾",
      creatingReview: "生成中…",
      emptyReview: "聊天后，回顾卡片会保存在这里。",
      backToMap: "返回地图",
      backToMapJp: "地図に戻る",
      navigationLabel: "店员导航",
      openMenu: "打开店员菜单",
      closeMenu: "关闭店员菜单",
    },
    chat: {
      typing: "正在回复…",
      placeholder: "输入消息，日中英都可以…",
      send: "发送",
      sending: "发送中…",
      switchToVoice: "切换到语音输入",
      switchToText: "切换到文字输入",
      voiceInput: "语音输入",
      textInput: "文字输入",
      startRecording: "开始录音",
      stopRecording: "停止录音",
      holdToTalk: "长按说话",
      recordingRelease: "录音中…松开发送",
      noSpeech: "没听清，可以再说一次，或直接输入文字。",
      sttError: "语音识别失败，可以继续用文字输入。",
      micError: "无法访问麦克风，请在浏览器里允许录音权限。",
    },
    feedback: {
      trigger: "表达提示",
      title: "表达提示",
      subtitle: "話し方を比べよう",
      close: "关闭表达提示",
      original: "你的原句",
      error: "表达提示生成失败，请稍后再试。",
      fallback: "表达提示暂时不可用。这里先保留你的原句，稍后可以再试一次。",
      userRecording: "听自己的录音",
      creating: "正在生成表达提示…",
      listen: "听一下",
      listenFailure: "播放失败，请稍后再试。",
      recommended: "推荐表达",
      showDetails: "展开说明",
      hideDetails: "收起说明",
      levels: {
        casual: { label: "亲近自然", subtitle: "カジュアル" },
        business: { label: "普通自然", subtitle: "ふつう" },
        formal: { label: "更礼貌", subtitle: "フォーマル" },
      },
    },
    explain: {
      loading: "正在解释…",
      error: "解释失败，请稍后再试。",
      listen: "听一下",
      close: "关闭解释",
      shortMeaning: "简义",
      sentenceMeaning: "这句话里的意思",
      showExplanation: "展开解释",
      hideExplanation: "收起解释",
    },
    summary: {
      title: "回顾卡片",
      subtitle: "ふりかえり",
      topic: "今天聊了什么",
      topicJp: "今日の話",
      reusable: "可直接复用的表达",
      reusableJp: "そのまま使える表現",
      upgrade: "下次可以这样说",
      upgradeJp: "次はこう言える",
      words: "今日词语",
      wordsJp: "今日のことば",
      nextTopic: "下次可以聊",
      nextTopicJp: "次に話してみること",
      original: "原表达",
      suggestion: "可以这样说",
      note: "学习点",
      fromHint: "来自表达提示",
      fromGap: "来自原句",
      fromConversation: "来自对话",
      lookedUp: "查过的词",
      readingLabel: "读音",
      meaningLabel: "意思",
      exampleLabel: "例句",
      duplicate: "这段对话已经生成过回顾卡片，已为你打开。",
      tooShort: "再聊几句后，就可以生成回顾卡片了。",
      createFailed: "回顾卡片生成失败，请稍后再试。",
      deleted: "回顾卡片已删除。",
      close: "关闭回顾卡片",
      delete: "删除这张卡片",
    },
    audio: {
      playNpc: "播放 NPC 语音",
      play: "播放",
      listenRecording: "听录音",
      recordingFailure: "录音播放失败，请稍后再试。",
    },
  },
  en: {
    common: {
      close: "Close",
      working: "Working…",
      genericError: "Something went wrong. Please try again.",
    },
    languageToggle: {
      ariaLabel: "Switch UI language",
      zh: "中文",
      en: "EN",
    },
    home: {
      talkToNpc: (npcName: string) => `Talk with ${npcName}`,
      cta: "Choose a shop and talk with the staff.",
      talkAction: "Start chatting",
    },
    sidebar: {
      residents: "Shop Staff",
      reviewTitle: "Review Cards",
      reviewSubtitle: "ふりかえり",
      reviewDescription: "Turn this chat into a review card.",
      createReview: "Create review",
      creatingReview: "Creating…",
      emptyReview: "Review cards will appear here after you chat.",
      backToMap: "Back to map",
      backToMapJp: "地図に戻る",
      navigationLabel: "Shop staff navigation",
      openMenu: "Open shop staff menu",
      closeMenu: "Close shop staff menu",
    },
    chat: {
      typing: "Replying…",
      placeholder: "Type in Chinese, English, or Japanese…",
      send: "Send",
      sending: "Sending…",
      switchToVoice: "Switch to voice input",
      switchToText: "Switch to text input",
      voiceInput: "Voice input",
      textInput: "Text input",
      startRecording: "Start recording",
      stopRecording: "Stop recording",
      holdToTalk: "Hold to talk",
      recordingRelease: "Recording… release to send",
      noSpeech: "I couldn’t catch that. Try again or type instead.",
      sttError: "Voice recognition failed. You can keep typing instead.",
      micError: "Couldn’t access the microphone. Please allow recording in your browser.",
    },
    feedback: {
      trigger: "Expression Hints",
      title: "Expression Hints",
      subtitle: "Compare ways to say it",
      close: "Close expression hints",
      original: "Your original message",
      error: "Couldn’t create expression hints. Please try again.",
      fallback: "Expression hints are temporarily unavailable. Keeping your original sentence for now.",
      userRecording: "Listen to your recording",
      creating: "Creating expression hints…",
      listen: "Listen",
      listenFailure: "Playback failed. Please try again.",
      recommended: "Recommended expression",
      showDetails: "Show details",
      hideDetails: "Hide details",
      levels: {
        casual: { label: "Casual", subtitle: "カジュアル" },
        business: { label: "Neutral", subtitle: "ふつう" },
        formal: { label: "Polite", subtitle: "フォーマル" },
      },
    },
    explain: {
      loading: "Explaining…",
      error: "Couldn’t explain this. Please try again.",
      listen: "Listen",
      close: "Close explanation",
      shortMeaning: "Short meaning",
      sentenceMeaning: "Meaning in this sentence",
      showExplanation: "Show explanation",
      hideExplanation: "Hide explanation",
    },
    summary: {
      title: "Review Card",
      subtitle: "ふりかえり",
      topic: "What you talked about",
      topicJp: "今日の話",
      reusable: "Reusable expressions",
      reusableJp: "そのまま使える表現",
      upgrade: "Try saying it this way",
      upgradeJp: "次はこう言える",
      words: "Words & phrases",
      wordsJp: "今日のことば",
      nextTopic: "What to talk about next",
      nextTopicJp: "次に話してみること",
      original: "Original expression",
      suggestion: "Try this",
      note: "Learning note",
      fromHint: "From expression hints",
      fromGap: "From your input",
      fromConversation: "From conversation",
      lookedUp: "Looked-up word",
      readingLabel: "Reading",
      meaningLabel: "Meaning",
      exampleLabel: "Example",
      duplicate: "This chat already has a review card. I opened it for you.",
      tooShort: "Chat a bit more before creating a review card.",
      createFailed: "Couldn’t create a review card. Please try again.",
      deleted: "Review card deleted.",
      close: "Close review card",
      delete: "Delete this card",
    },
    audio: {
      playNpc: "Play NPC voice",
      play: "Play",
      listenRecording: "Listen to recording",
      recordingFailure: "Recording playback failed. Please try again.",
    },
  },
} as const;

export type UiCopy = (typeof UI_COPY)[UiLanguage];

export function getUiCopy(language: UiLanguage): UiCopy {
  return UI_COPY[language];
}
